const cats=[['Alimentari','🛒','#64e695'],['Abbigliamento','👕','#b78cff'],['Casa','🏠','#6ea8ff'],['Bollette','💡','#ffd76b'],['Auto','🚗','#ffb86b'],['Svago','🎮','#ff7fa3'],['Salute','❤','#ff6b7a'],['Altro','•••','#93a0b4']];
const defaultState={salary:0,salaryDay:27,autoSalary:true,budgets:Object.fromEntries(cats.map(c=>[c[0],0])),movements:[]};
let loaded=JSON.parse(localStorage.getItem('portafoglioPC')||'null');let state=Object.assign({},defaultState,loaded||{});state.budgets=Object.assign({},defaultState.budgets,state.budgets||{});state.movements=Array.isArray(state.movements)?state.movements:[];
const $=id=>document.getElementById(id);function money(n){return new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(n||0)}function today(){let d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function save(renderNow=true){localStorage.setItem('portafoglioPC',JSON.stringify(state));if(renderNow)render()}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.navbtn,.mobileNav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));render()}
document.querySelectorAll('.navbtn,.mobileNav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));
function cycleBounds(ref=new Date()){let start=new Date(ref.getFullYear(),ref.getMonth(),state.salaryDay,0,0,0,0);if(ref<start)start=new Date(ref.getFullYear(),ref.getMonth()-1,state.salaryDay,0,0,0,0);let end=new Date(start.getFullYear(),start.getMonth()+1,state.salaryDay,0,0,0,0);return[start,end]}
function cycleKey(d=new Date()){let[s]=cycleBounds(d);return `${s.getFullYear()}-${String(s.getMonth()+1).padStart(2,'0')}-${String(s.getDate()).padStart(2,'0')}`}
function inCycle(m){let[s,e]=cycleBounds();let d=new Date(m.date+'T12:00:00');return d>=s&&d<e}
function totals(cycleOnly=false){let ms=cycleOnly?state.movements.filter(inCycle):state.movements;let inc=ms.filter(m=>m.type==='income').reduce((a,m)=>a+Number(m.amount||0),0);let exp=ms.filter(m=>m.type==='expense').reduce((a,m)=>a+Number(m.amount||0),0);return{inc,exp,bal:inc-exp}}
function nextSalary(){let now=new Date(),d=new Date(now.getFullYear(),now.getMonth(),state.salaryDay);if(d<now)d=new Date(now.getFullYear(),now.getMonth()+1,state.salaryDay);return d.toLocaleDateString('it-IT',{day:'2-digit',month:'long',year:'numeric'})}
function categoryInfo(name){return cats.find(c=>c[0]===name)||['Altro','•••','#93a0b4']}
function ensureSalaryTransaction(){if(!state.autoSalary||!state.salary)return;let[s]=cycleBounds(),key=cycleKey();let exists=state.movements.some(m=>m.autoSalaryKey===key);if(!exists&&new Date()>=s){state.movements.push({id:Date.now(),type:'income',amount:Number(state.salary),category:'Stipendio',date:`${s.getFullYear()}-${String(s.getMonth()+1).padStart(2,'0')}-${String(s.getDate()).padStart(2,'0')}`,description:'Stipendio',autoSalaryKey:key});save(false)}}
function render(){let t=totals(false),ct=totals(true);$('balance').textContent=money(t.bal);$('incomeSum').textContent=money(t.inc);$('expenseSum').textContent=money(t.exp);$('savePct').textContent=t.inc?Math.round(t.bal/t.inc*100)+'%':'0%';$('salaryAmount').textContent=money(state.salary);$('salaryDate').textContent=state.salary?nextSalary():'Non impostato';let[s,e]=cycleBounds(),pct=Math.max(0,Math.min(100,(Date.now()-s)/(e-s)*100));$('cycleProgress').style.width=pct+'%';$('cyclePct').textContent=Math.round(pct)+'%';let hr=new Date().getHours();$('greeting').textContent=(hr<13?'Buongiorno':hr<19?'Buon pomeriggio':'Buonasera')+' 👋';renderMovements();renderCats();renderSettings();renderStats()}
function movementHTML(m,del=false){let c=categoryInfo(m.category);return `<div class="movement" onclick="editMovement(${m.id})"><div class="icon">${m.category==='Stipendio'?'💶':c[1]}</div><div><div class="mname">${esc(m.description||m.category)}</div><div class="mmeta">${esc(m.category)} · ${new Date(m.date+'T12:00').toLocaleDateString('it-IT')}</div></div><div class="amountText ${m.type==='income'?'income':'expense'}">${m.type==='income'?'+':'-'}${money(m.amount)}</div>${del?`<button class="deleteMini" onclick="event.stopPropagation();deleteMovement(${m.id})">Elimina</button>`:''}</div>`}
function esc(v){return String(v??'').replace(/[&<>\"]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[s]))}
function renderMovements(){let sorted=[...state.movements].sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id);$('recent').innerHTML=sorted.slice(0,5).map(m=>movementHTML(m)).join('')||'<div class="empty">Nessun movimento registrato</div>';let q=($('searchMovement')?.value||'').toLowerCase(),f=$('filterMovement')?.value||'all';let filtered=sorted.filter(m=>(f==='all'||m.type===f)&&((m.description||'').toLowerCase().includes(q)||(m.category||'').toLowerCase().includes(q)));$('allMovements').innerHTML=filtered.map(m=>movementHTML(m,true)).join('')||'<div class="empty">Nessun movimento trovato</div>'}
function categorySpend(){let cycle=state.movements.filter(inCycle).filter(m=>m.type==='expense');return cats.map(c=>({...c,name:c[0],icon:c[1],color:c[2],spent:cycle.filter(m=>m.category===c[0]).reduce((a,m)=>a+Number(m.amount||0),0)}))}
function categoryCards(){return categorySpend().map(c=>{let bud=state.budgets[c.name]||0,pct=bud?Math.min(100,c.spent/bud*100):Math.min(100,c.spent?35:0);return `<div class="cat"><div class="row"><b>${c.icon} ${c.name}</b><small>${money(c.spent)}</small></div><div class="bar"><span style="width:${pct}%;background:${c.color}"></span></div><small>${bud?'Budget '+money(bud)+(c.spent>bud?' · superato':''):'Nessun budget'}</small></div>`}).join('')}
function renderCats(){$('catsHome').innerHTML=categoryCards();$('budgetStats').innerHTML=categoryCards()}
function renderSettings(){$('setSalary').value=state.salary||'';$('setDay').value=state.salaryDay||27;$('setAutoSalary').value=state.autoSalary?'yes':'no';$('budgetFields').innerHTML=cats.map(c=>`<div class="field"><label>${c[1]} ${c[0]}</label><input data-budget="${c[0]}" type="number" step="0.01" min="0" value="${state.budgets[c[0]]||''}" placeholder="0"></div>`).join('')}
function renderStats(){let t=totals(false),ct=totals(true);$('statBalance').textContent=money(t.bal);$('statIncome').textContent=money(t.inc);$('statExpense').textContent=money(t.exp);$('statSave').textContent=t.inc?Math.round(t.bal/t.inc*100)+'%':'0%';let now=new Date(),vals=[];for(let i=5;i>=0;i--){let d=new Date(now.getFullYear(),now.getMonth()-i,1),key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;let v=state.movements.filter(m=>m.type==='expense'&&m.date.startsWith(key)).reduce((a,m)=>a+Number(m.amount||0),0);vals.push([d.toLocaleDateString('it-IT',{month:'short'}),v])}let max=Math.max(1,...vals.map(v=>v[1]));$('chart').innerHTML=vals.map(v=>`<div class="col"><i style="height:${Math.max(3,v[1]/max*210)}px"></i>${v[0]}<br>${Math.round(v[1])}€</div>`).join('');let cs=categorySpend().filter(c=>c.spent>0),total=cs.reduce((a,c)=>a+c.spent,0);$('donutTotal').textContent=money(total);if(total){let acc=0,stops=[];cs.forEach(c=>{let start=acc;acc+=c.spent/total*100;stops.push(`${c.color} ${start.toFixed(1)}% ${acc.toFixed(1)}%`)});$('donut').style.background=`conic-gradient(${stops.join(',')})`;$('legend').innerHTML=cs.slice(0,6).map(c=>`<div class="legendItem"><span><i class="legendDot" style="background:${c.color}"></i>${c.name}</span><b>${Math.round(c.spent/total*100)}%</b></div>`).join('')}else{$('donut').style.background='#2b3240';$('legend').innerHTML='<span class="label">Nessuna spesa nel ciclo corrente</span>'}}
function openAdd(t){showView('add');$('type').value=t;$('date').value=today();$('category').value=t==='income'?'Altro':'Alimentari'}function clearForm(){$('amount').value='';$('description').value='';$('date').value=today();$('type').value='expense';$('category').value='Alimentari'}
function saveMovement(){let a=parseFloat($('amount').value);if(!a||a<=0){toast('Inserisci un importo valido');return}state.movements.push({id:Date.now(),type:$('type').value,amount:a,category:$('category').value,date:$('date').value||today(),description:$('description').value.trim()});save();clearForm();showView('home');toast('Movimento salvato')}
function deleteMovement(id){let m=state.movements.find(x=>x.id===id);if(m?.autoSalaryKey&&!confirm('Questo è un accredito automatico dello stipendio. Eliminarlo?'))return;state.movements=state.movements.filter(m=>m.id!==id);save();toast('Movimento eliminato')}
function editMovement(id){let m=state.movements.find(x=>x.id===id);if(!m)return;$('modalContent').innerHTML=`<div class="formGrid"><div class="field"><label>Tipo</label><select id="eType"><option value="expense" ${m.type==='expense'?'selected':''}>Spesa</option><option value="income" ${m.type==='income'?'selected':''}>Entrata</option></select></div><div class="field"><label>Importo</label><input id="eAmount" type="number" step="0.01" value="${m.amount}"></div><div class="field"><label>Categoria</label><select id="eCat">${cats.map(c=>`<option ${m.category===c[0]?'selected':''}>${c[0]}</option>`).join('')}<option ${m.category==='Stipendio'?'selected':''}>Stipendio</option></select></div><div class="field"><label>Data</label><input id="eDate" type="date" value="${m.date}"></div><div class="field full"><label>Descrizione</label><input id="eDesc" value="${esc(m.description||'')}"></div></div><div class="actions"><button class="secondary danger" onclick="deleteMovement(${m.id});closeModal()">Elimina</button><button class="primary" onclick="applyEdit(${m.id})">Salva modifiche</button></div>`;$('modalBack').classList.add('show')}
function applyEdit(id){let m=state.movements.find(x=>x.id===id),a=parseFloat($('eAmount').value);if(!a||a<=0){toast('Importo non valido');return}m.type=$('eType').value;m.amount=a;m.category=$('eCat').value;m.date=$('eDate').value;m.description=$('eDesc').value.trim();save();closeModal();toast('Modifiche salvate')}function closeModal(){$('modalBack').classList.remove('show')}
function saveSettings(){state.salary=parseFloat($('setSalary').value)||0;state.salaryDay=Math.min(28,Math.max(1,parseInt($('setDay').value)||27));state.autoSalary=$('setAutoSalary').value==='yes';document.querySelectorAll('[data-budget]').forEach(i=>state.budgets[i.dataset.budget]=parseFloat(i.value)||0);ensureSalaryTransaction();save();toast('Impostazioni salvate')}
function resetData(){if(confirm('Vuoi davvero cancellare tutti i dati? Questa operazione non può essere annullata.')){state=JSON.parse(JSON.stringify(defaultState));save();toast('Dati azzerati')}}
function exportData(){let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Portafoglio-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href);toast('Backup esportato')}
function importData(ev){let f=ev.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);if(!Array.isArray(d.movements))throw 0;state=Object.assign({},defaultState,d);state.budgets=Object.assign({},defaultState.budgets,d.budgets||{});save();toast('Backup importato')}catch{toast('Backup non valido')}ev.target.value=''};r.readAsText(f)}
function toast(msg){let t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),1900)}

function guessCategory(text){
  const s=(text||'').toLowerCase();
  const rules=[
    ['Alimentari',['conad','coop','lidl','esselunga','carrefour','eurospin','aldi','md ','supermerc','market','alimentari','ristorante','pizzeria','bar ','cafe','caffè']],
    ['Abbigliamento',['zara','h&m','hm ','primark','ovs','nike','adidas','zalando','abbigliamento']],
    ['Auto',['eni','q8','ip ','tamoil','esso','benzina','carburante','autostrade','telepass','parcheggio']],
    ['Casa',['ikea','leroy merlin','brico','casa']],
    ['Bollette',['enel','eni plenitude','tim','vodafone','windtre','iliad','fastweb','acea','bolletta']],
    ['Svago',['netflix','spotify','disney','amazon prime','cinema','steam','playstation','xbox']],
    ['Salute',['farmacia','parafarmacia','dentista','medico']]
  ];
  for(const [cat,words] of rules) if(words.some(w=>s.includes(w))) return cat;
  return 'Altro';
}
function receiveShortcutExpense(){
  const p=new URLSearchParams(location.search);
  const raw=p.get('amount')||p.get('importo');
  if(!raw) return;
  const amount=parseFloat(String(raw).replace(',','.').replace(/[^0-9.\-]/g,''));
  if(!amount || amount<=0) return;
  const merchant=p.get('merchant')||p.get('esercente')||p.get('description')||'Pagamento Wallet';
  const date=(p.get('date')||today()).slice(0,10);
  const source=p.get('source')||'shortcut';
  const signature=[amount.toFixed(2),merchant,date,source].join('|');
  const seenKey='portafoglio_last_shortcut';
  if(localStorage.getItem(seenKey)===signature){ history.replaceState({},'',location.pathname); return; }
  const m={id:Date.now(),type:'expense',amount,category:guessCategory(merchant),date,description:merchant,source};
  state.movements.push(m); localStorage.setItem(seenKey,signature); save(false); render();
  history.replaceState({},'',location.pathname); toast('Spesa Wallet aggiunta: '+money(amount));
}
if('serviceWorker' in navigator && location.protocol.startsWith('http')) navigator.serviceWorker.register('./sw.js').catch(()=>{});

$('category').innerHTML=cats.map(c=>`<option>${c[0]}</option>`).join('');$('date').value=today();ensureSalaryTransaction();render();receiveShortcutExpense();setTimeout(()=>$('splash').classList.add('hide'),650);setTimeout(()=>$('splash').remove(),1200);