const $=id=>document.getElementById(id);
const slotCats=['CPU','Motherboard','RAM','GPU','SSD','PSU','Case','Cooler'];
let parts=[],build=JSON.parse(localStorage.getItem('pdf_current_v2')||'{}'),xp=+localStorage.getItem('pdf_xp_v2')||0;
let garage=JSON.parse(localStorage.getItem('pdf_garage_v2')||'[]');
let feedUpdated='';
const money=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(t){const e=$('toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2100)}
function statusText(p){return p.status==='active'?'VERIFICATA':p.status==='changed'?'PREZZO CAMBIATO':'OFFERTA FINITA'}
function statusClass(p){return p.status==='active'?'hot':'warn'}
function ageText(v){if(!v)return '—';const d=new Date(v),h=Math.max(0,Math.round((Date.now()-d)/36e5));return h<1?'meno di 1 ora fa':h===1?'1 ora fa':`${h} ore fa`}
function dealScore(p){if(p.status!=='active')return 0;let s=72;if(p.shop==='BPM Power')s+=8;if((Date.now()-new Date(p.verifiedAt).getTime())<86400000)s+=10;return Math.min(100,s)}
function go(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id)?.classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='garage')renderGarage();if(id==='game')renderGame()}
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>go(b.dataset.view));
function card(p){const s=dealScore(p);return `<article class="card deal"><div class="dealTop"><span class="tag ${statusClass(p)}">${statusText(p)}</span><span class="tiny">${esc(p.cat)}</span></div><h3>${esc(p.name)}</h3><div class="meta">${esc(p.shop)} · controllata ${ageText(p.verifiedAt)}</div><div class="price">${money(p.price)}</div><div class="dealScore"><i style="width:${s}%"></i></div><div class="dealFoot"><span class="tiny">Trust score <b class="good">${s}/100</b></span><button class="iconBtn" onclick="openOffer('${p.id}')">Compra ↗</button></div></article>`}
function openOffer(id){const p=parts.find(x=>x.id===id);if(!p||p.status!=='active')return toast('Questa offerta non è più attiva');gainXp(5);window.open(p.url,'_blank','noopener')}
function renderHome(){const active=parts.filter(p=>p.status==='active'),sorted=[...active].sort((a,b)=>dealScore(b)-dealScore(a));$('homeDeals').innerHTML=sorted.slice(0,8).map(card).join('')||'<p class="meta">Nessuna offerta verificata disponibile.</p>';$('statDeals').textContent=active.length;$('statAvg').textContent='LIVE';$('statBuilds').textContent=garage.length;$('statBest').textContent=sorted[0]?dealScore(sorted[0])+'/100':'—'}
function initFilters(){const cats=[...new Set(parts.map(x=>x.cat))];$('catFilter').innerHTML='<option value="all">Tutte le categorie</option>'+cats.map(c=>`<option>${c}</option>`).join('');const importBtn=[...document.querySelectorAll('button')].find(b=>b.textContent.includes('Importa offerta'));if(importBtn){importBtn.textContent='✓ Solo offerte verificate';importBtn.onclick=()=>toast('Le offerte manuali sono disattivate: entrano solo link verificati.')};}
function renderMarket(){const q=($('search').value||'').toLowerCase(),cat=$('catFilter').value,sort=$('sort').value;let a=parts.filter(p=>(cat==='all'||p.cat===cat)&&p.name.toLowerCase().includes(q));a.sort(sort==='price'?(a,b)=>a.price-b.price:(a,b)=>dealScore(b)-dealScore(a));$('marketDeals').innerHTML=a.map(card).join('')||'<p class="meta">Nessun componente verificato trovato.</p>'}
function renderSlots(){const root=$('slots');root.innerHTML=slotCats.map(cat=>{const opts=parts.filter(p=>p.cat===cat&&p.status==='active'),sel=build[cat]&&parts.find(p=>p.id===build[cat].id);if(build[cat]&&!sel)build[cat]={...build[cat],status:'expired'};return `<div class="card slot"><div class="slothead"><b>${cat}</b><span>${sel?'✓ verificata':build[cat]?'⚠ scaduta':'Vuoto'}</span></div>${build[cat]?`<div class="choice"><strong>${esc(build[cat].name)}</strong><small>${money(build[cat].price)} · ${esc(build[cat].shop||'')}</small></div>`:'<div class="choice"><small>Scegli un componente verificato</small></div>'}<select class="selectPart" onchange="pick('${cat}',this.value)"><option value="">— scegli —</option>${opts.map(p=>`<option value="${p.id}" ${build[cat]?.id===p.id?'selected':''}>${esc(p.name)} · ${money(p.price)}</option>`).join('')}</select></div>`}).join('');analyze();renderBuyList()}
function pick(cat,id){if(!id)delete build[cat];else{const p=parts.find(x=>x.id===id);build[cat]={...p,selectedPrice:p.price}}localStorage.setItem('pdf_current_v2',JSON.stringify(build));renderSlots()}
function analyze(){const b=build,issues=[],warn=[];if(b.CPU&&b.Motherboard&&b.CPU.socket!==b.Motherboard.socket)issues.push(`Socket ${b.CPU.socket} ≠ ${b.Motherboard.socket}`);if(b.RAM&&b.Motherboard&&b.RAM.ram!==b.Motherboard.ram)issues.push(`RAM ${b.RAM.ram} incompatibile con ${b.Motherboard.ram}`);if(b.Case&&b.Motherboard&&!b.Case.form?.includes(b.Motherboard.form))issues.push(`Case incompatibile con ${b.Motherboard.form}`);if(b.Case&&b.GPU&&b.GPU.length>b.Case.gpuMax)issues.push('GPU troppo lunga per il case');if(b.CPU&&b.Cooler&&!b.Cooler.sockets?.includes(b.CPU.socket))warn.push('Verifica il kit di montaggio del dissipatore per questo socket');const draw=(b.CPU?.tdp||0)+(b.GPU?.watts||0)+100,need=Math.ceil(draw*1.4/50)*50;if(b.PSU&&b.PSU.watts<need)issues.push(`PSU insufficiente: consigliati almeno ${need}W`);const count=slotCats.filter(c=>b[c]).length,active=slotCats.filter(c=>b[c]?.status==='active').length,cost=slotCats.reduce((s,c)=>s+(b[c]?.price||0),0);const score=Math.max(0,Math.min(100,Math.round((count/8)*55+(active/8)*35-issues.length*25-warn.length*5+(count===8&&issues.length===0?10:0))));$('compat').innerHTML=[...issues.map(x=>`<div class="check bad">✕ ${esc(x)}</div>`),...warn.map(x=>`<div class="check warn">⚠ ${esc(x)}</div>`),...(count&&issues.length===0?['<div class="check">✓ Compatibilità critica OK</div>']:[])].join('')||'<div class="tiny">Aggiungi componenti per iniziare l’analisi.</div>';$('scoreRing').style.setProperty('--p',score);$('scoreText').textContent=score;$('costMini').textContent=money(cost);$('valueMini').textContent='—';$('marginMini').textContent='GAME';$('buildTotal').textContent=money(cost);$('buildStatus').textContent=count<8?`${count}/8 componenti`:issues.length?'Build incompatibile':active<8?'Build con offerte scadute':'BUILD READY 🔥';$('buildSubtitle').textContent=count===8&&active===8&&issues.length===0?'Tutto verificato: lista acquisti pronta':issues.length?`${issues.length} conflitti`:active<8?'Sostituisci le offerte terminate':'Solo offerte reali verificate';return {count,active,cost,score,issues}}
function renderBuyList(){let box=$('buyList');if(!box){box=document.createElement('div');box.id='buyList';box.className='card';box.style.marginTop='16px';const builder=document.querySelector('#builder .builder');builder?.after(box)}const a=analyze();if(!a.count){box.innerHTML='<h3>🛒 Lista acquisti</h3><p class="meta">Completa la build e qui compariranno i link diretti.</p>';return}box.innerHTML=`<div class="sectionTitle"><div><h2>🛒 Lista acquisti</h2><p>${a.count===8?'Build completa':'Completa gli 8 slot'} · ${a.active}/${a.count} offerte attive</p></div>${a.count===8&&a.active===8&&!a.issues.length?'<button class="btn" onclick="openAllOffers()">Apri tutti i negozi</button>':''}</div><div>${slotCats.filter(c=>build[c]).map(c=>{const p=parts.find(x=>x.id===build[c].id),active=p?.status==='active';return `<div class="check ${active?'':'bad'}"><b>${c}</b> · ${esc(build[c].name)} · ${money(p?.price??build[c].price)} ${active?`<a href="${esc(p.url)}" target="_blank" rel="noopener" style="margin-left:auto">Compra ↗</a>`:'<span style="margin-left:auto">OFFERTA FINITA</span>'}</div>`}).join('')}</div>`}
function openAllOffers(){const a=analyze();if(a.count!==8||a.active!==8||a.issues.length)return toast('La build deve essere completa, compatibile e con offerte attive');slotCats.forEach((c,i)=>setTimeout(()=>{const p=parts.find(x=>x.id===build[c]?.id);if(p)window.open(p.url,'_blank','noopener')},i*180));gainXp(40);toast('Shopping raid +40 XP')}
function saveBuild(){const a=analyze();if(a.count!==8)return toast('Completa tutti gli 8 componenti');const item={id:Date.now(),name:$('buildName').value||'Build',savedAt:new Date().toISOString(),score:a.score,parts:slotCats.map(c=>({id:build[c].id,name:build[c].name,cat:c,savedPrice:build[c].price,url:build[c].url}))};garage.unshift(item);localStorage.setItem('pdf_garage_v2',JSON.stringify(garage));gainXp(a.active===8&&!a.issues.length?120:50);toast(a.active===8&&!a.issues.length?'Build READY salvata +120 XP':'Build salvata +50 XP');renderHome()}
function currentState(saved){const p=parts.find(x=>x.id===saved.id);if(!p||p.status!=='active')return {type:'expired',label:'💀 OFFERTA FINITA'};if(Math.abs(p.price-saved.savedPrice)>.99)return {type:'changed',label:`📈 PREZZO ${money(saved.savedPrice)} → ${money(p.price)}`};return {type:'ok',label:'🟢 ATTIVA'} }
function renderGarage(){if(!garage.length){$('garageRows').innerHTML='<tr><td colspan="7" class="meta">Garage vuoto. Completa una build e salvala.</td></tr>';return}$('garageRows').innerHTML=garage.map(g=>{const states=g.parts.map(currentState),dead=states.filter(x=>x.type==='expired').length,changed=states.filter(x=>x.type==='changed').length,status=dead?`💀 ${dead} offerte finite`:changed?`📈 ${changed} prezzi cambiati`:'🔥 Tutte attive';return `<tr><td><b>${esc(g.name)}</b><div class="tiny">${status}</div></td><td>${g.parts.map((p,i)=>`<div class="tiny">${esc(p.cat)}: ${esc(p.name)} · ${states[i].label}</div>`).join('')}</td><td>${money(g.parts.reduce((s,p)=>s+p.savedPrice,0))}</td><td>—</td><td>${dead?'MISSIONE: RIPARA':'READY'}</td><td>${g.score}</td><td><button class="iconBtn" onclick="loadGarage(${g.id})">Carica</button> <button class="iconBtn" onclick="removeBuild(${g.id})">✕</button></td></tr>`}).join('')}
function loadGarage(id){const g=garage.find(x=>x.id===id);if(!g)return;build={};g.parts.forEach(sp=>{const p=parts.find(x=>x.id===sp.id);build[sp.cat]=p?{...p,selectedPrice:sp.savedPrice}:{...sp,status:'expired',price:sp.savedPrice}});localStorage.setItem('pdf_current_v2',JSON.stringify(build));$('buildName').value=g.name+' · rebuild';go('builder');renderSlots();gainXp(15);toast('Build caricata: sostituisci le offerte finite +15 XP')}
function removeBuild(id){garage=garage.filter(x=>x.id!==id);localStorage.setItem('pdf_garage_v2',JSON.stringify(garage));renderGarage();renderHome()}
function clearGarage(){if(confirm('Svuotare il garage?')){garage=[];localStorage.setItem('pdf_garage_v2','[]');renderGarage();renderHome()}}
function clearBuild(){build={};localStorage.removeItem('pdf_current_v2');renderSlots()}
function randomBuild(){build={};slotCats.forEach(c=>{const a=parts.filter(p=>p.cat===c&&p.status==='active');if(a.length)build[c]={...a[Math.floor(Math.random()*a.length)]}});localStorage.setItem('pdf_current_v2',JSON.stringify(build));renderSlots();gainXp(10);toast('Loot crate aperta +10 XP')}
function gainXp(n){xp+=n;localStorage.setItem('pdf_xp_v2',xp);renderXp()}
function renderXp(){const lv=Math.floor(xp/500)+1,cur=xp%500;$('xpPill').textContent=`LV ${lv} · ${xp} XP`;$('gameLevel').textContent=`LV ${lv}`;$('xpText').textContent=`${cur} / 500 XP`;$('xpBar').style.width=(cur/5)+'%'}
function renderGame(){const a=analyze(),expired=garage.reduce((n,g)=>n+g.parts.filter(p=>currentState(p).type==='expired').length,0),active=parts.filter(p=>p.status==='active').length;const missions=[['🧩 Assemblatore',a.count===8,'Completa tutti gli 8 slot',80],['🛡 Compat Master',a.count===8&&!a.issues.length,'Completa una build senza conflitti critici',120],['⚡ Live Hunter',a.count===8&&a.active===8,'Usa solo offerte attive verificate',150],['🏎 Budget Run',a.count===8&&a.cost<3000,'Build completa sotto 3.000 €',100],['🏚 Salvage Run',expired>0,'Hai almeno un’offerta finita nel Garage: ricarica e ripara la build',90],['🛒 Shopping Raid',active>=8,'Il radar contiene abbastanza componenti per una build reale',50]];$('missions').innerHTML=missions.map(m=>`<div class="card mission"><div><b>${m[0]}</b><div class="meta">${m[2]}</div></div><span class="tag ${m[1]?'hot':''}">${m[1]?'COMPLETATA':'+'+m[3]+' XP'}</span></div>`).join('');$('badges').innerHTML=[xp>=100?'🏅 Deal Scout':'🔒 Deal Scout',garage.length?'🏆 Garage Owner':'🔒 Garage Owner',a.count===8&&a.active===8?'🔥 Live Builder':'🔒 Live Builder',expired?'💀 Deal Survivor':'🔒 Deal Survivor',xp>=1000?'👑 PC Flipper':'🔒 PC Flipper'].map(x=>`<span>${x}</span>`).join('')}
function openImport(){toast('Import manuale disattivato: solo offerte verificate.')}
function closeImport(){$('importModal')?.classList.remove('show')}
function importDeal(){toast('Import manuale disattivato.')}
async function loadFeed(){try{const r=await fetch('./offers-live.json?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('feed');const data=await r.json();parts=data.offers||[];feedUpdated=data.updatedAt||'';}catch(e){parts=[];toast('Radar live non disponibile: nessun prezzo non verificato verrà mostrato.')}initFilters();renderHome();renderMarket();syncBuild();renderSlots();renderXp();renderGame()}
function syncBuild(){for(const c of slotCats){if(!build[c])continue;const live=parts.find(p=>p.id===build[c].id);if(live)build[c]={...live,selectedPrice:build[c].selectedPrice??build[c].price};else build[c]={...build[c],status:'expired'}}localStorage.setItem('pdf_current_v2',JSON.stringify(build))}
window.go=go;window.openOffer=openOffer;window.pick=pick;window.saveBuild=saveBuild;window.clearBuild=clearBuild;window.randomBuild=randomBuild;window.clearGarage=clearGarage;window.loadGarage=loadGarage;window.removeBuild=removeBuild;window.openAllOffers=openAllOffers;window.openImport=openImport;window.closeImport=closeImport;window.importDeal=importDeal;window.renderMarket=renderMarket;
loadFeed();