const byId=(id)=>document.getElementById(id);
const compat=byId('compat'),scoreRing=byId('scoreRing'),scoreText=byId('scoreText'),buildTotal=byId('buildTotal'),costMini=byId('costMini'),valueMini=byId('valueMini'),marginMini=byId('marginMini'),buildStatus=byId('buildStatus'),buildSubtitle=byId('buildSubtitle'),xpPill=byId('xpPill'),gameLevel=byId('gameLevel'),xpText=byId('xpText'),xpBar=byId('xpBar'),missionsEl=byId('missions'),badges=byId('badges'),garageRows=byId('garageRows'),buildName=byId('buildName'),impName=byId('impName'),impPrice=byId('impPrice'),impRef=byId('impRef'),impCat=byId('impCat'),impShop=byId('impShop'),impUrl=byId('impUrl');
const snapshotDate='21/08/2026';
const parts=[
{id:'cpu1',cat:'CPU',name:'AMD Ryzen 7 9800X3D',price:352.11,ref:430,shop:'Idealo',socket:'AM5',tdp:120,score:91,reliability:88,url:'https://www.idealo.it/'},
{id:'cpu2',cat:'CPU',name:'AMD Ryzen 5 9600X',price:172.89,ref:230,shop:'bpm-power',socket:'AM5',tdp:65,score:88,reliability:94,url:'https://www.bpm-power.com/'},
{id:'cpu3',cat:'CPU',name:'Intel Core Ultra 7 265K',price:307.41,ref:390,shop:'Sferaufficio',socket:'LGA1851',tdp:125,score:80,reliability:88,url:'https://www.sferaufficio.com/'},
{id:'cpu4',cat:'CPU',name:'AMD Ryzen 7 9700X',price:285,ref:350,shop:'Market snapshot',socket:'AM5',tdp:65,score:78,reliability:76,url:'https://www.trovaprezzi.it/'},
{id:'gpu1',cat:'GPU',name:'ASUS Prime RTX 5070 Ti OC 16GB',price:802.50,ref:1040,shop:'Opendeel',watts:300,length:304,score:92,reliability:86,url:'https://www.opendeel.com/'},
{id:'gpu2',cat:'GPU',name:'MSI RTX 5080 Inspire 3X OC 16GB',price:980,ref:1320,shop:'Opendeel',watts:360,length:288,score:93,reliability:82,url:'https://www.opendeel.com/'},
{id:'gpu3',cat:'GPU',name:'Sapphire Pulse RX 9070 XT 16GB',price:491.90,ref:760,shop:'Opendeel',watts:304,length:320,score:97,reliability:79,url:'https://www.opendeel.com/'},
{id:'gpu4',cat:'GPU',name:'ASUS GeForce RTX 5070 12GB',price:694.90,ref:820,shop:'Idealo',watts:250,length:304,score:70,reliability:92,url:'https://www.idealo.it/'},
{id:'mb1',cat:'Motherboard',name:'Gigabyte B650 Eagle AX',price:137.48,ref:165,shop:'Amazon Marketplace',socket:'AM5',ram:'DDR5',form:'ATX',score:78,reliability:93,url:'https://www.amazon.it/'},
{id:'mb2',cat:'Motherboard',name:'Gigabyte B850 Gaming WIFI6',price:154.22,ref:205,shop:'bpm-power',socket:'AM5',ram:'DDR5',form:'ATX',score:89,reliability:93,url:'https://www.bpm-power.com/'},
{id:'mb3',cat:'Motherboard',name:'MSI B850 Gaming Plus WIFI',price:179,ref:220,shop:'Amazon.it',socket:'AM5',ram:'DDR5',form:'ATX',score:83,reliability:96,url:'https://www.amazon.it/'},
{id:'mb4',cat:'Motherboard',name:'MSI Z890 Gaming Plus WIFI',price:239,ref:295,shop:'Market snapshot',socket:'LGA1851',ram:'DDR5',form:'ATX',score:76,reliability:82,url:'https://www.trovaprezzi.it/'},
{id:'ram1',cat:'RAM',name:'Kingston Fury Beast RGB 32GB DDR5-6000 CL30',price:172.05,ref:220,shop:'Idealo',ram:'DDR5',gb:32,score:81,reliability:90,url:'https://www.idealo.it/'},
{id:'ram2',cat:'RAM',name:'Corsair Vengeance 32GB DDR5-6400 CL36',price:249,ref:285,shop:'Idealo',ram:'DDR5',gb:32,score:62,reliability:91,url:'https://www.idealo.it/'},
{id:'ram3',cat:'RAM',name:'G.Skill Flare X5 32GB DDR5-6000 CL30',price:149,ref:190,shop:'Market snapshot',ram:'DDR5',gb:32,score:86,reliability:78,url:'https://www.trovaprezzi.it/'},
{id:'ssd1',cat:'SSD',name:'Lexar NM790 2TB NVMe Gen4',price:129.99,ref:180,shop:'Andrea Lolli Web',gb:2000,score:92,reliability:88,url:'https://www.andrealolli.it/'},
{id:'ssd2',cat:'SSD',name:'Crucial P310 2TB NVMe Gen4',price:154,ref:195,shop:'Market snapshot',gb:2000,score:82,reliability:84,url:'https://www.idealo.it/'},
{id:'ssd3',cat:'SSD',name:'Samsung 990 EVO Plus 2TB',price:174,ref:215,shop:'Market snapshot',gb:2000,score:77,reliability:86,url:'https://www.trovaprezzi.it/'},
{id:'psu1',cat:'PSU',name:'MSI MAG A850GLS PCIE5 850W Gold',price:134.64,ref:165,shop:'Market snapshot',watts:850,atx31:true,score:82,reliability:86,url:'https://www.trovaprezzi.it/'},
{id:'psu2',cat:'PSU',name:'Corsair RM850x 850W ATX 3.1 Gold',price:149,ref:185,shop:'Market snapshot',watts:850,atx31:true,score:80,reliability:86,url:'https://www.trovaprezzi.it/'},
{id:'psu3',cat:'PSU',name:'be quiet! Pure Power 12 M 1000W',price:169,ref:205,shop:'Market snapshot',watts:1000,atx31:true,score:79,reliability:84,url:'https://www.idealo.it/'},
{id:'case1',cat:'Case',name:'NZXT H7 Flow (2024)',price:99.90,ref:130,shop:'Market snapshot',form:['ATX','mATX','ITX'],gpuMax:410,score:84,reliability:89,url:'https://www.trovaprezzi.it/'},
{id:'case2',cat:'Case',name:'DeepCool CH690',price:87.95,ref:120,shop:'hq2.it',form:['ATX','mATX','ITX'],gpuMax:450,score:88,reliability:90,url:'https://www.hq2.it/'},
{id:'case3',cat:'Case',name:'Fractal North XL',price:169,ref:195,shop:'Market snapshot',form:['ATX','mATX','ITX'],gpuMax:413,score:73,reliability:84,url:'https://www.idealo.it/'},
{id:'cool1',cat:'Cooler',name:'ARCTIC Liquid Freezer III Pro 360',price:80.99,ref:105,shop:'Market snapshot',sockets:['AM5','LGA1851'],score:90,reliability:86,url:'https://www.trovaprezzi.it/'},
{id:'cool2',cat:'Cooler',name:'Thermalright Phantom Spirit 120 EVO',price:49,ref:65,shop:'Market snapshot',sockets:['AM5','LGA1851'],score:92,reliability:82,url:'https://www.idealo.it/'},
{id:'cool3',cat:'Cooler',name:'Noctua NH-D15 G2',price:139,ref:150,shop:'Market snapshot',sockets:['AM5','LGA1851'],score:63,reliability:90,url:'https://www.trovaprezzi.it/'}
];
let extra=JSON.parse(localStorage.getItem('pdf_extra')||'[]'); let catalog=()=>[...parts,...extra];
const slotCats=['CPU','Motherboard','RAM','GPU','SSD','PSU','Case','Cooler']; let build=JSON.parse(localStorage.getItem('pdf_current')||'{}'); let xp=+localStorage.getItem('pdf_xp')||0;
const cats=[...new Set(parts.map(x=>x.cat))];
function money(n){return new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n||0)}
function discount(p){return Math.max(0,Math.round((1-p.price/p.ref)*100))}
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function go(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'}); if(id==='garage')renderGarage(); if(id==='game')renderGame()}
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>go(b.dataset.view));
function card(p){let d=discount(p), rel=p.reliability??75;return `<article class="card deal"><div class="dealTop"><span class="tag ${d>=25?'hot':rel<75?'warn':''}">${p.cat}</span><span class="tiny">${rel}% fid.</span></div><h3>${p.name}</h3><div class="meta">${p.shop} · rilevato ${snapshotDate}</div><div class="price">${money(p.price)} <span class="strike">${money(p.ref)}</span></div><div class="dealScore"><i style="width:${p.score||70}%"></i></div><div class="dealFoot"><span class="tiny"><b class="good">-${d}%</b> · Deal ${p.score||70}/100</span><button class="iconBtn" onclick="window.open('${p.url||'#'}','_blank')">Apri ↗</button></div></article>`}
function renderHome(){const c=catalog().slice().sort((a,b)=>(b.score||0)-(a.score||0));document.getElementById('homeDeals').innerHTML=c.slice(0,8).map(card).join('');document.getElementById('statDeals').textContent=c.length;document.getElementById('statAvg').textContent=Math.round(c.reduce((s,p)=>s+discount(p),0)/c.length)+'%';document.getElementById('statBuilds').textContent=JSON.parse(localStorage.getItem('pdf_garage')||'[]').length;document.getElementById('statBest').textContent=c[0]?.score+'/100'}
function initFilters(){document.getElementById('catFilter').innerHTML='<option value="all">Tutte le categorie</option>'+cats.map(c=>`<option>${c}</option>`).join('');document.getElementById('impCat').innerHTML=cats.map(c=>`<option>${c}</option>`).join('')}
function renderMarket(){let q=document.getElementById('search').value.toLowerCase(),cat=document.getElementById('catFilter').value,sort=document.getElementById('sort').value;let a=catalog().filter(p=>(cat==='all'||p.cat===cat)&&p.name.toLowerCase().includes(q));a.sort(sort==='price'?(a,b)=>a.price-b.price:sort==='discount'?(a,b)=>discount(b)-discount(a):(a,b)=>(b.score||0)-(a.score||0));document.getElementById('marketDeals').innerHTML=a.map(card).join('')||'<p class="meta">Nessun componente trovato.</p>'}
function openImport(){document.getElementById('importModal').classList.add('show')}function closeImport(){document.getElementById('importModal').classList.remove('show')}
function importDeal(){let n=impName.value.trim(),pr=+impPrice.value,rf=+impRef.value;if(!n||!pr||!rf)return toast('Completa nome, prezzo e riferimento');let d=Math.round((1-pr/rf)*100);let item={id:'x'+Date.now(),cat:impCat.value,name:n,price:pr,ref:rf,shop:impShop.value||'Offerta manuale',url:impUrl.value||'#',score:Math.max(30,Math.min(99,55+d)),reliability:75};extra.push(item);localStorage.setItem('pdf_extra',JSON.stringify(extra));closeImport();renderMarket();renderHome();gainXp(25);toast('Offerta importata +25 XP')}
function renderSlots(){document.getElementById('slots').innerHTML=slotCats.map(cat=>{let opts=catalog().filter(p=>p.cat===cat);let sel=build[cat];return `<div class="card slot"><div class="slothead"><b>${cat}</b><span>${sel?'Selezionato':'Vuoto'}</span></div>${sel?`<div class="choice"><strong>${sel.name}</strong><small>${money(sel.price)} · ${sel.shop}</small></div>`:'<div class="choice"><small>Scegli un componente</small></div>'}<select class="selectPart" onchange="pick('${cat}',this.value)"><option value="">— scegli —</option>${opts.map(p=>`<option value="${p.id}" ${sel?.id===p.id?'selected':''}>${p.name} · ${money(p.price)}</option>`).join('')}</select></div>`}).join('');analyze()}
function pick(cat,id){if(!id)delete build[cat];else build[cat]=catalog().find(p=>p.id===id);localStorage.setItem('pdf_current',JSON.stringify(build));renderSlots()}
function analyze(){let issues=[],warnings=[];const b=build;if(b.CPU&&b.Motherboard&&b.CPU.socket!==b.Motherboard.socket)issues.push(`Socket CPU ${b.CPU.socket} ≠ motherboard ${b.Motherboard.socket}`);if(b.RAM&&b.Motherboard&&b.RAM.ram!==b.Motherboard.ram)issues.push(`RAM ${b.RAM.ram} incompatibile con ${b.Motherboard.ram}`);if(b.Case&&b.Motherboard&&!b.Case.form.includes(b.Motherboard.form))issues.push(`Il case non supporta form factor ${b.Motherboard.form}`);if(b.Case&&b.GPU&&b.GPU.length>b.Case.gpuMax)issues.push(`GPU ${b.GPU.length}mm > spazio case ${b.Case.gpuMax}mm`);if(b.CPU&&b.Cooler&&!b.Cooler.sockets.includes(b.CPU.socket))issues.push('Dissipatore non compatibile col socket CPU');let draw=(b.CPU?.tdp||0)+(b.GPU?.watts||0)+90;let need=Math.ceil(draw*1.35/50)*50;if(b.PSU&&b.PSU.watts<need)issues.push(`PSU ${b.PSU.watts}W insufficiente: consigliati ≥ ${need}W`);if(b.PSU&&!b.PSU.atx31&&(b.GPU?.watts||0)>=300)warnings.push('Per GPU moderne è preferibile PSU ATX 3.1');if(b.CPU?.name.includes('9800X3D')&&b.GPU&&b.GPU.price<650)warnings.push('Build CPU-heavy: potresti spostare budget dalla CPU alla GPU');let count=slotCats.filter(c=>b[c]).length;let cost=slotCats.reduce((s,c)=>s+(b[c]?.price||0),0);let baseRef=slotCats.reduce((s,c)=>s+(b[c]?.ref||0),0);let resale=baseRef*.92;let margin=resale-cost;let dealAvg=count?slotCats.reduce((s,c)=>s+(b[c]?.score||0),0)/count:0;let score=Math.round(Math.max(0,Math.min(100,dealAvg-(issues.length*25)-(warnings.length*5)+(count===8?8:0))));compat.innerHTML=[...issues.map(x=>`<div class="check bad">✕ ${x}</div>`),...warnings.map(x=>`<div class="check warn">⚠ ${x}</div>`),...(issues.length===0&&count?['<div class="check">✓ Nessun conflitto critico rilevato</div>']:[])].join('')||'<div class="check warn">Aggiungi componenti per analizzare la build</div>';scoreRing.style.setProperty('--p',score);scoreText.textContent=score;buildTotal.textContent=money(cost);costMini.textContent=money(cost);valueMini.textContent=money(resale);marginMini.textContent=(margin>=0?'+':'')+money(margin);marginMini.className=margin>=0?'good':'badText';buildStatus.textContent=issues.length?'Build incompatibile':count===8?'Build pronta':'Build incompleta';buildSubtitle.textContent=count===8?`${issues.length?issues.length+' problemi':warnings.length?warnings.length+' avvisi':'Compatibilità OK'} · PSU target ${need}W`:`${count}/8 componenti selezionati`;return{cost,resale,margin,score,issues,count}}
function saveBuild(){let a=analyze();if(a.count<5)return toast('Seleziona almeno 5 componenti');let garage=JSON.parse(localStorage.getItem('pdf_garage')||'[]');garage.unshift({id:Date.now(),name:buildName.value||'Build',parts:JSON.parse(JSON.stringify(build)),...a,date:new Date().toLocaleDateString('it-IT')});localStorage.setItem('pdf_garage',JSON.stringify(garage));gainXp(a.issues.length?20:100);renderHome();toast(a.issues.length?'Build salvata +20 XP':'Build compatibile salvata +100 XP')}
function clearBuild(){build={};localStorage.setItem('pdf_current','{}');renderSlots()}
function randomBuild(){build={};slotCats.forEach(c=>{let a=catalog().filter(p=>p.cat===c);build[c]=a[Math.floor(Math.random()*a.length)]});localStorage.setItem('pdf_current',JSON.stringify(build));renderSlots();gainXp(10)}
function renderGarage(){let g=JSON.parse(localStorage.getItem('pdf_garage')||'[]');garageRows.innerHTML=g.map(x=>`<tr><td><b>${x.name}</b><div class="tiny">${x.date}</div></td><td>${Object.keys(x.parts).length}/8</td><td>${money(x.cost)}</td><td>${money(x.resale)}</td><td class="${x.margin>=0?'good':'badText'}">${x.margin>=0?'+':''}${money(x.margin)}</td><td>${x.score}/100</td><td><button class="iconBtn" onclick="loadBuild(${x.id})">Apri</button></td></tr>`).join('')||'<tr><td colspan="7" class="meta">Garage vuoto. Salva la tua prima build.</td></tr>'}
function loadBuild(id){let g=JSON.parse(localStorage.getItem('pdf_garage')||'[]'),x=g.find(y=>y.id===id);if(!x)return;build=x.parts;buildName.value=x.name;localStorage.setItem('pdf_current',JSON.stringify(build));renderSlots();go('builder')}
function clearGarage(){localStorage.setItem('pdf_garage','[]');renderGarage();renderHome()}
const missions=[{t:'Affare chirurgico',d:'Trova/importa un componente con almeno 25% di sconto.',xp:120,test:()=>catalog().some(p=>discount(p)>=25)},{t:'Build completa',d:'Salva una build con tutti gli 8 componenti.',xp:250,test:()=>JSON.parse(localStorage.getItem('pdf_garage')||'[]').some(x=>Object.keys(x.parts).length===8)},{t:'Flip profittevole',d:'Salva una build con margine stimato positivo.',xp:300,test:()=>JSON.parse(localStorage.getItem('pdf_garage')||'[]').some(x=>x.margin>0)},{t:'Compatibilità perfetta',d:'Salva una build senza conflitti critici.',xp:350,test:()=>JSON.parse(localStorage.getItem('pdf_garage')||'[]').some(x=>x.issues?.length===0&&Object.keys(x.parts).length===8)}];
function gainXp(n){xp+=n;localStorage.setItem('pdf_xp',xp);renderXp()}
function renderXp(){let lv=Math.floor(xp/500)+1, rem=xp%500;xpPill.textContent=`LV ${lv} · ${xp} XP`;gameLevel.textContent='LV '+lv;xpText.textContent=`${rem} / 500 XP al prossimo livello`;xpBar.style.width=(rem/5)+'%'}
function renderGame(){missionsEl.innerHTML=missions.map((m,i)=>{let ok=m.test();return `<div class="card mission"><div class="eyebrow">Missione ${i+1}</div><h3>${m.t}</h3><div class="meta">${m.d}</div><div class="progress"><span style="width:${ok?100:20}%"></span></div><div class="dealFoot"><span class="tiny">Ricompensa ${m.xp} XP</span><span class="tag ${ok?'hot':''}">${ok?'COMPLETA':'IN CORSO'}</span></div></div>`}).join('');let g=JSON.parse(localStorage.getItem('pdf_garage')||'[]'),bad=[['Primo assemblaggio',g.length>0],['Cacciatore di deal',catalog().some(p=>discount(p)>=25)],['Flipper',g.some(x=>x.margin>0)],['Perfect build',g.some(x=>x.issues?.length===0&&Object.keys(x.parts).length===8)],['Garage master',g.length>=5],['Livello 5',xp>=2000]];badges.innerHTML=bad.map(([n,ok])=>`<div class="badge ${ok?'':'lock'}">${ok?'🏆':'🔒'} <b>${n}</b></div>`).join('');renderXp()}
initFilters();renderHome();renderMarket();renderSlots();renderGame();
