(()=>{
const tierNames={ECONOMY:['RUSH','🟢'],MID:['STRIKE','🔵'],HIGH:['APEX','🟣'],ULTRA:['OVERKILL','🔴']};
const cheapest=(arr)=>[...arr].sort((a,b)=>a.price-b.price)[0];
const priciest=(arr)=>[...arr].sort((a,b)=>b.price-a.price)[0];
const find=(arr,re)=>arr.find(p=>re.test(p.name));
function activeCat(cat){return parts.filter(p=>p.status==='active'&&p.cat===cat)}
function cpuFor(t){const a=activeCat('CPU');if(t==='ECONOMY')return find(a,/Ryzen 5 7600/i)||cheapest(a.filter(p=>p.socket==='AM5'));if(t==='MID')return find(a,/Ryzen 7 9700X/i)||find(a,/Ryzen 7 7800X3D/i)||cheapest(a.filter(p=>p.socket==='AM5'));if(t==='HIGH')return find(a,/Ryzen 7 9800X3D/i)||find(a,/Ryzen 7 7800X3D/i)||priciest(a.filter(p=>p.socket==='AM5'));return find(a,/Ryzen 7 9800X3D/i)||priciest(a.filter(p=>p.socket==='AM5'))}
function gpuFor(t){const a=activeCat('GPU');if(t==='ECONOMY')return cheapest(a.filter(p=>p.price<=500))||cheapest(a);if(t==='MID')return find(a,/RTX 5070/i)||find(a,/RX 9070 XT/i)||cheapest(a.filter(p=>p.price<=800))||cheapest(a);if(t==='HIGH')return find(a,/RX 9070 XT/i)||find(a,/RTX 5070/i)||priciest(a.filter(p=>p.price<=900))||priciest(a);return find(a,/RTX 5080/i)||priciest(a)}
function chooseComplete(t){const cpu=cpuFor(t),gpu=gpuFor(t);if(!cpu||!gpu)return null;const mb=cheapest(activeCat('Motherboard').filter(p=>p.socket===cpu.socket));if(!mb)return null;const ramType=mb.ram||cpu.ram||'DDR5';const ramChoices=activeCat('RAM').filter(p=>!p.ram||p.ram===ramType);const ram=t==='ULTRA'?priciest(ramChoices):cheapest(ramChoices);const ssds=activeCat('SSD');const ssd=t==='ULTRA'?priciest(ssds):t==='HIGH'?(find(ssds,/Gen5|T705/i)||priciest(ssds)):cheapest(ssds);const need=(gpu.watts||250)+400;const psus=activeCat('PSU').filter(p=>(p.watts||0)>=need);const psu=t==='ULTRA'?priciest(psus):cheapest(psus);const cases=activeCat('Case').filter(p=>!gpu.length||!p.gpuMax||p.gpuMax>=gpu.length);const cs=t==='ULTRA'?priciest(cases):cheapest(cases);const coolers=activeCat('Cooler').filter(p=>!p.sockets||p.sockets.includes(cpu.socket));const cool=t==='ULTRA'?priciest(coolers):cheapest(coolers);const list=[cpu,mb,ram,gpu,ssd,psu,cs,cool];if(list.some(x=>!x))return null;const b={name:t,list,total:list.reduce((s,p)=>s+p.price,0),score:Math.round(list.reduce((s,p)=>s+score(p),0)/8)};return compatible(Object.fromEntries(list.map(p=>[p.cat,p]))).length?null:b}
pickTier=function(t){return chooseComplete(t)||{name:t,list:[],total:0,score:0,incomplete:true}};
buildCard=function(t,i){const b=pickTier(t);const [title,orb]=tierNames[t];if(b.list.length!==8)return `<article class="buildCard blocked"><div class="buildBody"><div class="tier ${t.toLowerCase()}">${t}</div><div class="buildTitle">${title}</div><div class="priceBig">⚠️</div><div class="tiny">LOADOUT IN RIGENERAZIONE</div></div></article>`;const hero=b.list.find(p=>p.cat==='GPU')||b.list[0],im=imgFor(hero)||pics.GPU;return `<article class="buildCard"><img src="${im}" alt=""><div class="buildBody"><div style="display:flex;justify-content:space-between;align-items:center;gap:8px"><div class="tier ${t.toLowerCase()}">${t}</div><span class="badge hot">${orb} 8/8</span></div><div class="buildTitle">${title}</div><div class="priceBig">${money(b.total)}</div><div class="buildIcons">${b.list.map(p=>`<span class="lootIcon" title="${p.name}">${icon[p.cat]}</span>`).join('')}</div><button class="btn" onclick="loadDaily('${t}')">EQUIPAGGIA ⚔️</button></div></article>`};
loadDaily=function(t){const b=pickTier(t);if(b.list.length!==8)return alert('La build del giorno si sta rigenerando: manca un componente reale compatibile.');build={};b.list.forEach(p=>build[p.cat]=p);localStorage.setItem('pdf_v3_build',JSON.stringify(build));gain(40);nav('builder')};
})();