(()=>{
'use strict';
const A=window.TMAPP,C=window.TM91,G=window.TM112;if(!A||!C||!G){document.getElementById('app').innerHTML='<p>Errore caricamento moduli.</p>';return}
if(!A.requireUser(true))return;A.installDisplayToggle();
const app=document.getElementById('app'),DRAFT='tm_v91_draft',ABS='tm_v125_absences',REQ='tm_v125_requests';
const PEOPLE=['Umberto','Fabio','Emanuele','Stefania B','Stefania F','Romina','Giada','Giuliano','Manuel','Daniele','Paolo','Marco'];
let state={draft:read(DRAFT,null),week:0,graphDay:0,busy:false};
function read(k,d){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))??d}catch{return d}}
function write(k,v){if(v===null)localStorage.removeItem(k);else localStorage.setItem(k,JSON.stringify(v))}
function labelDate(d){return C.dateLabel?C.dateLabel(d):new Intl.DateTimeFormat('it-IT',{weekday:'short',day:'numeric',month:'short'}).format(new Date(d+'T12:00:00'))}
function weekTitle(w,i){return `Settimana ${i+1} · ${labelDate(w.dates[0])} – ${labelDate(w.dates[6])}`}
function requests(){return read(REQ,[]).filter(x=>x?.status==='ACCETTATA')}
function absences(){return read(ABS,[])}
function absencePanel(){const a=absences();return `<section class="card"><h2>🏖️ Assenze</h2><p>Ferie, malattia e permesso. Quando cambi un'assenza la bozza viene invalidata, ma la pagina non si ricarica.</p><div class="form-row"><select id="absEmployee">${PEOPLE.map(n=>`<option>${A.esc(n)}</option>`).join('')}</select><select id="absType"><option>FERIE</option><option>MALATTIA</option><option>PERMESSO</option></select><input id="absFrom" type="date"><input id="absTo" type="date"><button class="btn blue" id="absAdd" type="button">Aggiungi</button></div><div class="absence-list">${a.length?a.map((x,i)=>`<div class="absence-row"><div><b>${A.esc(x.employee)}</b> · ${A.esc(x.type||'FERIE')}<br><small>${A.esc(x.from)} → ${A.esc(x.to)}</small></div><button class="btn ghost" data-abs-del="${i}" type="button">Rimuovi</button></div>`).join(''):'<div class="notice">Nessuna assenza inserita.</div>'}</div></section>`}
function requestPanel(){const q=requests();return `<section class="card"><h2>📨 Richieste accettate</h2><div class="request-list">${q.length?q.slice().sort((a,b)=>String(a.created_at).localeCompare(String(b.created_at))).map(x=>`<div class="request-item"><b>${A.esc(x.employee)}</b><small>${A.esc(x.message||'Richiesta accettata')}</small></div>`).join(''):'<div class="notice">Nessuna richiesta accettata.</div>'}</div></section>`}
function table(w){return `<section class="card"><h2>Turnazione</h2><div class="week-table"><table><thead><tr><th>Persona</th>${w.dates.map(d=>`<th>${A.esc(labelDate(d))}</th>`).join('')}<th>Ore</th></tr></thead><tbody>${PEOPLE.map(n=>`<tr><td><b>${A.esc(n)}</b><br><small>${A.esc(C.role?.(n)||'')}</small></td>${w.dates.map((d,i)=>{const s=w.schedule?.[n]?.[i]||'RIPOSO',off=C.OFF?.has?.(String(s).trim())||['RIPOSO','FERIE','PERMESSO','MALATTIA','MATERNITÀ','—'].includes(s);return `<td><button class="shift-btn ${off?'off':''}" type="button" data-edit="${A.esc(n)}" data-day="${i}">${A.esc(s)}</button></td>`}).join('')}<td class="hours">${C.weekHours(w,n)}h</td></tr>`).join('')}</tbody></table></div></section>`}
function graph(w){const START=C.hm('06:30'),END=C.hm('20:30'),R=END-START,pct=v=>Math.max(0,Math.min(100,(v-START)/R*100)),d=Math.min(state.graphDay,6);return `<section class="card"><h2>Grafico giornaliero · Presenza personale</h2><div class="graph-days">${w.dates.map((x,i)=>`<button class="${i===d?'active':''}" type="button" data-graph-day="${i}">${A.esc(labelDate(x))}</button>`).join('')}</div><div class="graph-scroll"><div class="graph">${PEOPLE.map(n=>{const s=w.schedule?.[n]?.[d]||'RIPOSO',sp=C.spans(s);return `<div class="graph-row"><div class="graph-name"><b>${A.esc(n)}</b><br><small>${A.esc(s)}</small></div><div class="graph-track">${sp.map(([x,y])=>`<div class="graph-bar" style="left:${pct(x)}%;width:${Math.max(.5,pct(y)-pct(x))}%"><span>${C.fmtHm(x)}–${C.fmtHm(y)}</span></div>`).join('')}</div></div>`}).join('')}</div></div></section>`}
function render(){const d=state.draft?.weeks?.length===3?state.draft:null;if(!d)state.week=0;const w=d?.weeks?.[Math.min(state.week,2)];app.innerHTML=`<main class="app-shell"><div class="topbar"><a href="index.html">← Home</a><b>Nuovi Turni</b></div><section class="hero"><h1>Nuovi turni · 3 settimane</h1><p>Versione modulare: una sola interfaccia, niente reload automatici e niente cache PWA.</p></section><div class="grid2">${requestPanel()}${absencePanel()}</div><section class="card"><div class="toolbar"><input id="startDate" type="date" value="${A.esc(w?.dates?.[0]||A.nextMonday())}"><button class="btn primary" id="generate" type="button" ${state.busy?'disabled':''}>${state.busy?'Generazione…':d?'Rigenera da zero':'Genera 3 settimane'}</button></div></section>${d?`<div class="tabs">${d.weeks.map((x,i)=>`<button type="button" data-week="${i}" class="${i===state.week?'active':''}">${A.esc(weekTitle(x,i))}</button>`).join('')}</div>${graph(w)}${table(w)}<div class="actions"><button class="btn ghost" id="clearDraft" type="button">Cancella bozza</button><button class="btn blue" id="publish" type="button">Pubblica turni</button></div>`:'<section class="card"><div class="notice">Nessuna bozza. Inserisci eventuali assenze e genera le 3 settimane.</div></section>'}</main>`}
function invalidateDraft(){state.draft=null;state.week=0;state.graphDay=0;write(DRAFT,null)}
function addAbsence(){const employee=document.getElementById('absEmployee')?.value,type=document.getElementById('absType')?.value,from=document.getElementById('absFrom')?.value,to=document.getElementById('absTo')?.value||from;if(!employee||!from||!to||to<from){alert('Controlla le date dell’assenza.');return}const a=absences();a.push({employee,type,from,to,created_at:new Date().toISOString()});write(ABS,a);invalidateDraft();render()}
function removeAbsence(i){const a=absences();a.splice(i,1);write(ABS,a);invalidateDraft();render()}
function generate(){if(state.busy)return;const start=document.getElementById('startDate')?.value||A.nextMonday();if(state.draft&&!confirm('Rigenerare tutte e 3 le settimane da zero?'))return;state.busy=true;render();setTimeout(()=>{try{const out=G.generate(start);if(!out?.weeks||out.weeks.length!==3)throw new Error('Il generatore non ha restituito 3 settimane.');state.draft=out;state.week=0;state.graphDay=0;write(DRAFT,out)}catch(e){alert('Generazione non riuscita: '+(e?.message||e))}finally{state.busy=false;render()}},30)}
function editor(name,day){const w=state.draft?.weeks?.[state.week];if(!w)return;const cur=w.schedule?.[name]?.[day]||'RIPOSO',choices=[...new Set([cur,...(C.QUICK||[])])];document.body.insertAdjacentHTML('beforeend',`<div class="editor-back" id="editor"><div class="editor"><h3>${A.esc(name)} · ${A.esc(labelDate(w.dates[day]))}</h3><select id="editShift">${choices.map(x=>`<option ${x===cur?'selected':''}>${A.esc(x)}</option>`).join('')}</select><div class="actions"><button class="btn ghost" id="editCancel" type="button">Annulla</button><button class="btn primary" id="editSave" type="button">Salva</button></div></div></div>`);document.getElementById('editCancel').onclick=()=>document.getElementById('editor')?.remove();document.getElementById('editSave').onclick=()=>{w.schedule[name][day]=document.getElementById('editShift').value;write(DRAFT,state.draft);document.getElementById('editor')?.remove();render()}}
async function publish(){if(!state.draft)return;const b=document.getElementById('publish');if(b)b.disabled=true;try{const issues=G.validateSchedule?.(state.draft)||[];if(issues.length&&!confirm('La validazione interna segnala delle anomalie. Vuoi pubblicare comunque?'))return;const data=JSON.parse(JSON.stringify(state.draft));data.updated=new Date().toISOString();await A.api('save_schedule',{method:'POST',body:{data}});invalidateDraft();alert('Turni pubblicati.');location.href='index.html'}catch(e){alert('Pubblicazione non riuscita: '+(e?.message||e))}finally{if(b)b.disabled=false}}
app.addEventListener('click',e=>{const t=e.target.closest('button,a');if(!t)return;if(t.id==='generate'){generate();return}if(t.id==='absAdd'){addAbsence();return}if(t.dataset.absDel!==undefined){removeAbsence(+t.dataset.absDel);return}if(t.dataset.week!==undefined){state.week=+t.dataset.week;state.graphDay=0;render();return}if(t.dataset.graphDay!==undefined){state.graphDay=+t.dataset.graphDay;render();return}if(t.dataset.edit){editor(t.dataset.edit,+t.dataset.day);return}if(t.id==='clearDraft'){if(confirm('Cancellare la bozza?')){invalidateDraft();render()}return}if(t.id==='publish'){publish();return}});
render();
})();