const u=requireUser(true),app=document.getElementById('app');let data,week=0;
async function boot(){if(!u)return;data=await loadSchedule();render()}
function render(){const w=data.weeks[week],names=Object.keys(w.schedule);app.innerHTML=`<div class="app-shell"><div class="brandbar"></div><header class="topbar"><div class="toprow"><a class="back" href="index.html">‹ Turni</a><div class="brand-mini"><div class="mini-mark">E</div><div><strong>Amministratore</strong><span>Solo account Eurospin</span></div></div><button class="logout" onclick="logout()">Esci</button></div></header><main class="main"><section class="hero adminhero"><div class="eyebrow">Gestione turni</div><h2>Modifica semplice</h2><p>Scegli settimana, persona, giorno e turno. Nessun codice.</p></section><div class="chips">${data.weeks.map((x,i)=>`<button class="chip ${i===week?'active':''}" data-w="${i}">${x.label}</button>`).join('')}</div><section class="admin-editor"><div class="field"><label>Dipendente</label><select id="person">${names.map(n=>`<option>${esc(n)}</option>`).join('')}</select></div><div class="field"><label>Giorno</label><select id="day">${w.dates.map((d,i)=>`<option value="${i}">${fmtDate(d)}</option>`).join('')}</select></div><div class="field"><label>Turno</label><select id="shift">${SHIFT_OPTIONS.map(s=>`<option>${esc(s)}</option>`).join('')}</select></div><button class="primary" id="apply">Applica modifica</button><div class="notice">Le modifiche restano in questa anteprima finché non premi <b>Pubblica turni</b>. Pubblicandole diventano visibili a tutti i telefoni.</div></section><div class="section-title"><h3>Anteprima settimana</h3><span>${w.label}</span></div><div class="employee-grid">${names.map(n=>`<section class="employee-week"><div class="employee-head"><div><strong>${esc(n)}</strong><small>${esc(ROLES[n]||'')}</small></div></div><div class="mini-days">${w.dates.map((d,i)=>`<button class="editcell" data-p="${esc(n)}" data-d="${i}"><span>${fmtDate(d).slice(0,3)}</span><b>${esc(w.schedule[n][i]||'—')}</b></button>`).join('')}</div></section>`).join('')}</div><div class="sticky-actions"><button class="secondary" id="reload">Ricarica ufficiali</button><button class="primary" id="publish">Pubblica turni</button></div><div id="saveResult"></div></main></div>`;
  document.querySelectorAll('[data-w]').forEach(b=>b.onclick=()=>{week=+b.dataset.w;render()});
  document.querySelectorAll('.editcell').forEach(b=>b.onclick=()=>{document.getElementById('person').value=b.dataset.p;document.getElementById('day').value=b.dataset.d;document.getElementById('shift').value=w.schedule[b.dataset.p][+b.dataset.d]||'—';scrollTo({top:150,behavior:'smooth'})});
  document.getElementById('apply').onclick=()=>{const p=document.getElementById('person').value,d=+document.getElementById('day').value,s=document.getElementById('shift').value;w.schedule[p][d]=s;render()};
  document.getElementById('reload').onclick=async()=>{data=await loadSchedule();render()};
  document.getElementById('publish').onclick=async()=>{const btn=document.getElementById('publish');btn.disabled=true;btn.textContent='Pubblicazione…';try{data.updated=new Intl.DateTimeFormat('it-IT',{dateStyle:'long',timeStyle:'short'}).format(new Date());await api('save_schedule',{method:'POST',body:{data}});alert('Turni pubblicati. Ora tutti i telefoni vedono questa versione.')}catch(e){alert(e.message)}finally{btn.disabled=false;btn.textContent='Pubblica turni'}};
}
boot();
