const app=document.getElementById('app');let state={user:getSession(),week:0,data:null,ann:[],openRequests:0};
function loginView(err=''){app.innerHTML=`<div class="login"><div class="brandbar"></div><div class="login-inner"><div class="logo"><div class="logo-mark">E</div><div><h1>Eurospin Torre Maura</h1><small>Portale turnazioni personale</small></div></div><div class="login-card"><h2>Accedi ai tuoi turni</h2><p>Inserisci nome e password.</p><form id="loginForm"><div class="field"><label>Nome</label><input id="name" autocapitalize="words" autocomplete="username" placeholder="Es. Manuel" required></div><div class="field"><label>Password</label><input id="pass" type="password" inputmode="numeric" autocomplete="current-password" placeholder="••" required></div><button class="primary">Accedi</button>${err?`<div class="error">${err}</div>`:''}</form></div></div></div>`;document.getElementById('loginForm').onsubmit=e=>{e.preventDefault();const raw=document.getElementById('name').value.trim().toLowerCase(),key=Object.keys(USERS).find(k=>k.toLowerCase()===raw),pass=document.getElementById('pass').value;if(!key||USERS[key].password!==pass)return loginView('Nome o password non corretti.');state.user={key,...USERS[key]};setSession(state.user);boot()}}
async function boot(){if(!state.user)return loginView();state.data=await loadSchedule();try{state.ann=(await api('list_announcements')).announcements||[]}catch{}if(state.user.admin){try{const r=await api('list_requests');state.openRequests=(r.requests||[]).filter(x=>!x.replied_at).length}catch{state.openRequests=0}}render()}
function dayCards(w,n){return w.dates.map((d,i)=>{const s=(w.schedule[n]||[])[i]||'—';return `<article class="day"><div class="day-head"><span class="dow">${fmtDate(d).split(' ')[0]}</span><span class="date">${new Date(d+'T12:00:00').getDate()}</span></div><div class="shift">${esc(s)}</div><span class="status ${statusClass(s)}">${s==='RIPOSO'?'Riposo':s==='FERIE'?'Ferie':s==='MATERNITÀ'?'Maternità':'Turno'}</span><div class="role">${esc(ROLES[n]||'')}</div></article>`}).join('')}
function hoursBox(w,n){const h=weekHours(w,n),t=target(n),extra=Math.max(0,h-t);return `<div class="hours-summary compact-hours"><div><span>Settimana</span><strong>${h}h</strong></div><div><span>Contratto</span><strong>${t}h</strong></div><div class="${extra?'over':''}"><span>Extra</span><strong>${extra?`+${extra}h`:'0h'}</strong></div><div><span>Mese</span><strong>${monthHours(state.data,n)}h</strong></div></div>`}
function announcements(){if(!state.ann.length)return'';return `<section class="announcement slim-announcement"><div><div class="eyebrow">Avviso</div><strong>${esc(state.ann[0].message)}</strong></div><small>${formatDateTime(state.ann[0].created_at)}</small></section>`}
function todayBox(n){const today=new Date().toLocaleDateString('sv-SE');for(const w of state.data.weeks){for(let i=0;i<w.dates.length;i++){if(w.dates[i]===today){const s=(w.schedule[n]||[])[i]||'—';return `<section class="today-focus"><div><span>Turno di oggi</span><strong>${esc(s)}</strong><small>${esc(ROLES[n]||'')}</small></div><div class="today-dot">★</div></section>`}}}return''}
function rows(names,w,monthly=false){return names.map(n=>{const h=monthly?monthHours(state.data,n):weekHours(w,n),e=monthly?0:Math.max(0,h-target(n));return `<div class="hours-row"><div><b>${esc(n)}</b><small>${esc(ROLES[n]||'')}</small></div><strong>${h}h</strong><span class="${e?'extra':''}">${monthly?'mese':FORF.has(n)?'forf.':e?`+${e}h`:'0'}</span></div>`}).join('')}
function employeeSchedule(w,n){return `<section class="schedule-focus"><div class="schedule-heading"><div><span class="kicker">I tuoi turni</span><h2>${w.label}</h2></div><div class="week-arrows"><button id="prev">‹</button><button id="next">›</button></div></div><div class="chips compact-chips">${state.data.weeks.map((x,i)=>`<button class="chip ${i===state.week?'active':''}" data-w="${i}">${x.label}</button>`).join('')}</div><section class="calendar primary-calendar">${dayCards(w,n)}</section></section>`}
function adminSchedule(w){const names=Object.keys(w.schedule);return `<section class="admin-schedule-focus"><div class="schedule-heading"><div><span class="kicker">Turni del negozio</span><h2>${w.label}</h2></div><div class="week-arrows"><button id="prev">‹</button><button id="next">›</button></div></div><div class="chips compact-chips">${state.data.weeks.map((x,i)=>`<button class="chip ${i===state.week?'active':''}" data-w="${i}">${x.label}</button>`).join('')}</div><div class="admin-turn-list">${names.map(n=>`<article class="admin-person"><div class="admin-person-head"><div><strong>${esc(n)}</strong><small>${esc(ROLES[n]||'')}</small></div><div class="hours-pill">${weekHours(w,n)}h</div></div><div class="admin-week-strip">${w.dates.map((d,i)=>`<div><span>${fmtDate(d).split(' ')[0]}</span><b>${esc((w.schedule[n]||[])[i]||'—')}</b></div>`).join('')}</div></article>`).join('')}</div></section>`}
function employeeHeader(u){return `<header class="topbar clean-topbar"><div class="toprow"><div class="brand-mini"><div class="mini-mark">E</div><div><strong>Eurospin Torre Maura</strong><span>${esc(u.display)}</span></div></div><div class="header-actions"><a class="header-icon" href="requests.html" aria-label="Richieste">✉️</a><a class="header-icon" href="avvisi.html" aria-label="Avvisi">📢</a><button class="header-icon logout-icon" id="logout" aria-label="Esci">↗</button></div></div></header>`}
function adminHeader(){return `<header class="topbar clean-topbar"><div class="toprow"><div class="brand-mini"><div class="mini-mark">E</div><div><strong>Eurospin Torre Maura</strong><span>Account Eurospin</span></div></div><div class="header-actions"><a class="header-icon request-icon" href="inbox.html" aria-label="Richieste">✉️${state.openRequests?`<i>${state.openRequests}</i>`:''}</a><a class="header-icon" href="avvisi.html" aria-label="Avvisi">📢</a><button class="header-icon logout-icon" id="logout" aria-label="Esci">↗</button></div></div></header>`}
function employeeHome(u,w){return `${todayBox(u.employee)}${employeeSchedule(w,u.employee)}${hoursBox(w,u.employee)}${announcements()}`}
function adminHome(w){return `<section class="admin-command"><div><span class="kicker">Pannello responsabili</span><h1>Gestione turni</h1><p>Turnazioni in primo piano. Le altre funzioni sono qui quando servono.</p></div><div class="admin-command-actions"><a href="admin.html"><span>✎</span><b>Modifica turni</b></a><a href="inbox.html"><span>✉</span><b>Richieste</b>${state.openRequests?`<em>${state.openRequests}</em>`:''}</a><a href="avvisi.html"><span>☰</span><b>Avvisi</b></a></div></section>${adminSchedule(w)}<details class="admin-hours-details"><summary>Riepilogo ore della settimana</summary><div class="hours-table">${rows(Object.keys(w.schedule),w,false)}</div></details>${announcements()}`}
function render(){const u=state.user,w=state.data.weeks[state.week];app.innerHTML=`<div class="app-shell"><div class="brandbar"></div>${u.admin?adminHeader():employeeHeader(u)}<main class="main focused-main">${u.admin?adminHome(w):employeeHome(u,w)}</main></div>`;document.getElementById('logout').onclick=logout;document.querySelectorAll('[data-w]').forEach(b=>b.onclick=()=>{state.week=+b.dataset.w;render()});document.getElementById('prev').onclick=()=>{state.week=Math.max(0,state.week-1);render()};document.getElementById('next').onclick=()=>{state.week=Math.min(state.data.weeks.length-1,state.week+1);render()}}
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(console.warn);boot();