(()=>{
 const style=document.createElement('style');style.textContent=`body:has(.topbar) #displayModeBtn{display:none!important}.header-actions>.header-icon,.header-actions>.logout-icon{display:none!important}.home-hamb{width:40px;height:40px;border:1px solid rgba(255,255,255,.28);background:rgba(255,255,255,.12);color:#fff;border-radius:12px;font-size:22px;font-weight:900;display:grid;place-items:center}.home-menu-back{position:fixed;inset:0;z-index:10000;background:rgba(0,31,65,.35);display:flex;justify-content:flex-end;align-items:flex-start;padding:max(58px,calc(env(safe-area-inset-top) + 52px)) 10px 10px}.home-menu{width:min(320px,calc(100vw - 20px));background:#fff;border-radius:18px;box-shadow:0 18px 55px rgba(0,34,72,.25);overflow:hidden;border:1px solid #d7e2ea}.home-menu-head{background:#0067b1;color:#fff;padding:14px 15px;border-bottom:4px solid #ffd100}.home-menu-head strong,.home-menu-head small{display:block}.home-menu-list{padding:8px}.home-menu-list a,.home-menu-list button{width:100%;box-sizing:border-box;display:flex;align-items:center;gap:11px;border:0;background:#fff;color:#003c78;text-decoration:none;padding:12px;border-radius:12px;font:inherit;font-weight:900;text-align:left}.home-menu-list .ico{width:29px;height:29px;border-radius:9px;background:#eef6fc;display:grid;place-items:center}.home-menu-list .badge{margin-left:auto;background:#ffd100;color:#003c78;border-radius:999px;padding:3px 7px;font-size:10px}.menu-sep{height:1px;background:#e6edf2;margin:6px 4px}.menu-danger{color:#8b2b2b!important}.menu-mode strong{margin-left:auto;font-size:11px;background:#ffd100;padding:4px 7px;border-radius:999px;color:#003c78}.home-menu-close{position:absolute;inset:0;z-index:-1}.mode-tools-row{display:none!important}`;document.head.appendChild(style);
 function currentMode(){return localStorage.getItem('tm_display_mode')||((window.innerWidth>=900)?'pc':'phone')}
 function applyMode(mode){localStorage.setItem('tm_display_mode',mode);document.documentElement.dataset.displayMode=mode;document.body.classList.toggle('mode-pc',mode==='pc');document.body.classList.toggle('mode-phone',mode==='phone')}
 async function deleteWeeks(){
  document.getElementById('homeMenuBack')?.remove();
  try{
   const r=await api('get_schedule');
   const data=r?.data&&Array.isArray(r.data.weeks)?r.data:await loadSchedule();
   const total=data?.weeks?.length||0;
   if(!total){alert('Non ci sono settimane pubblicate da cancellare.');return}
   const raw=prompt(`Ci sono ${total} settimane pubblicate.\nQuante delle settimane più recenti vuoi cancellare?`,String(total));
   if(raw===null)return;
   const n=Number(raw);
   if(!Number.isInteger(n)||n<1||n>total){alert(`Inserisci un numero da 1 a ${total}.`);return}
   const removed=data.weeks.slice(total-n).map(w=>w.label||`${w.dates?.[0]||''} / ${w.dates?.at?.(-1)||''}`);
   if(!confirm(`Confermi la cancellazione di ${n} ${n===1?'settimana':'settimane'}?\n\n${removed.join('\n')}\n\nQuesta operazione rimuove i turni pubblicati.`))return;
   data.weeks=data.weeks.slice(0,total-n);
   data.updated=data.weeks.length?new Intl.DateTimeFormat('it-IT',{dateStyle:'long',timeStyle:'short'}).format(new Date()):'';
   await api('save_schedule',{method:'POST',body:{data}});
   alert(`${n} ${n===1?'settimana cancellata':'settimane cancellate'} correttamente.`);
   location.reload();
  }catch(e){alert('Cancellazione non riuscita: '+(e?.message||e))}
 }
 function openMenu(){const u=getSession();if(!u)return;document.getElementById('homeMenuBack')?.remove();const admin=!!u.admin,mode=currentMode();const items=admin?`<a href="inbox.html"><span class="ico">✉️</span>Richieste ${typeof state!=='undefined'&&state.openRequests?`<span class="badge">${state.openRequests}</span>`:''}</a><a href="turnations.html"><span class="ico">✓</span>Vedi Turnazioni</a><a href="new-turns.html"><span class="ico">🗓️</span>Nuovi Turni</a><a href="admin.html"><span class="ico">✎</span>Modifica turni</a><a href="hours-summary.html"><span class="ico">⏱️</span>Conteggio ore</a><button class="menu-danger" id="menuDeleteWeeks"><span class="ico">🗑️</span>Cancella settimane</button><a href="avvisi.html"><span class="ico">📢</span>Avvisi</a>`:`<a href="calendar-request.html"><span class="ico">📅</span>Calendario richieste</a><a href="requests.html"><span class="ico">✉️</span>Le mie richieste</a><a href="avvisi.html"><span class="ico">📢</span>Avvisi</a>`;document.body.insertAdjacentHTML('beforeend',`<div class="home-menu-back" id="homeMenuBack"><div class="home-menu-close" id="homeMenuClose"></div><div class="home-menu"><div class="home-menu-head"><strong>Eurospin Torre Maura</strong><small>${admin?'Account Eurospin':esc(u.display)}</small></div><div class="home-menu-list">${items}<div class="menu-sep"></div><button id="menuNotify"><span class="ico">🔔</span>Notifiche</button><button class="menu-mode" id="menuMode"><span class="ico">${mode==='pc'?'💻':'📱'}</span>Visualizzazione <strong>${mode==='pc'?'PC':'Telefono'}</strong></button><div class="menu-sep"></div><button class="menu-danger" id="menuLogout"><span class="ico">↗</span>Esci dall’account</button></div></div></div>`);document.getElementById('homeMenuClose').onclick=()=>document.getElementById('homeMenuBack')?.remove();document.getElementById('menuLogout').onclick=logout;document.getElementById('menuNotify').onclick=()=>{document.getElementById('homeMenuBack')?.remove();if(typeof enablePush==='function')enablePush()};document.getElementById('menuMode').onclick=()=>{applyMode(currentMode()==='pc'?'phone':'pc');document.getElementById('homeMenuBack')?.remove();setTimeout(openMenu,50)};if(admin)document.getElementById('menuDeleteWeeks').onclick=deleteWeeks}
 function mount(){const actions=document.querySelector('.header-actions');if(!actions)return;let b=actions.querySelector('.home-hamb');if(!b){b=document.createElement('button');b.className='home-hamb';b.type='button';b.innerHTML='☰';b.onclick=openMenu;actions.appendChild(b)}}new MutationObserver(mount).observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();