(()=>{
'use strict';
const u=requireUser(true),app=document.getElementById('app');if(!u)return;
const ABS=new Set(['RIPOSO','FERIE','MALATTIA','MATERNITÀ','PERMESSO','—','']);
function mins(t){const m=String(t||'').match(/^(\d{1,2}):(\d{2})$/);return m?(+m[1]*60)+(+m[2]):NaN}
function shiftHours(s){if(!s||ABS.has(String(s).trim()))return 0;return String(s).split('/').map(x=>x.trim()).reduce((z,p)=>{const m=p.match(/^(\d{1,2}:\d{2})\s*-\s*(\d{1,2}:\d{2})$/);if(!m)return z;const a=mins(m[1]),b=mins(m[2]);return Number.isFinite(a)&&Number.isFinite(b)&&b>a?z+(b-a)/60:z},0)}
function fmt(n){return Number.isInteger(n)?String(n):n.toFixed(1).replace('.',',')}
function monthName(ym){const[y,m]=ym.split('-').map(Number);return new Intl.DateTimeFormat('it-IT',{month:'long',year:'numeric'}).format(new Date(y,m-1,1)).replace(/^./,c=>c.toUpperCase())}
function role(n){return (typeof ROLES!=='undefined'&&ROLES[n])||''}
async function boot(){let data;try{const r=await api('get_schedule');data=r?.data?.weeks?r.data:await loadSchedule()}catch{data=await loadSchedule()}const weeks=data?.weeks||[];const names=[...new Set(weeks.flatMap(w=>Object.keys(w.schedule||{})))];const monthly={};for(const w of weeks)for(let d=0;d<(w.dates||[]).length;d++){const ym=w.dates[d].slice(0,7);monthly[ym] ||= Object.fromEntries(names.map(n=>[n,0]));for(const n of names)monthly[ym][n]=(monthly[ym][n]||0)+shiftHours(w.schedule?.[n]?.[d])}
const latest=weeks.length-1;app.innerHTML=`<div class="hours-page"><header><a href="index.html">‹ Home</a><div><small>Amministrazione</small><h1>Conteggio ore</h1></div></header><section class="hours-intro"><b>Riepilogo delle ore inserite nei turni</b><span>Settimane, mesi, giorni lavorati e spezzati in un'unica pagina.</span></section>${weeks.length?`<section class="hours-card"><h2>Settimane</h2><div class="hours-week-tabs">${weeks.map((w,i)=>`<button data-week="${i}" class="${i===latest?'active':''}">${esc(w.label||`Settimana ${i+1}`)}</button>`).join('')}</div><div id="weekTable"></div></section>`:'<section class="hours-card">Nessuna turnazione pubblicata.</section>'}${Object.keys(monthly).length?`<section class="hours-card"><h2>Totali mensili</h2>${Object.keys(monthly).sort().reverse().map(ym=>`<details ${ym===Object.keys(monthly).sort().at(-1)?'open':''}><summary>${monthName(ym)}</summary><div class="hours-grid">${names.map(n=>`<div class="hours-person"><div><b>${esc(n)}</b><small>${esc(role(n))}</small></div><strong>${fmt(monthly[ym][n]||0)}h</strong></div>`).join('')}</div></details>`).join('')}</section>`:''}</div>`;
function renderWeek(i){const w=weeks[i],box=document.getElementById('weekTable');if(!w||!box)return;box.innerHTML=`<div class="hours-grid">${names.map(n=>{const shifts=w.schedule?.[n]||[],h=shifts.reduce((z,s)=>z+shiftHours(s),0),days=shifts.filter(s=>shiftHours(s)>0).length,splits=shifts.filter(s=>String(s||'').includes('/')).length,t=typeof target==='function'?target(n):null,diff=t==null?null:h-t;return `<article class="hours-person full"><div><b>${esc(n)}</b><small>${esc(role(n))}</small></div><div class="hours-metrics"><span><i>Ore</i><strong>${fmt(h)}h</strong></span>${t!=null?`<span><i>Contratto</i><strong>${fmt(t)}h</strong></span><span class="${diff>0?'over':diff<0?'under':''}"><i>Differenza</i><strong>${diff>0?'+':''}${fmt(diff)}h</strong></span>`:''}<span><i>Giorni</i><strong>${days}</strong></span><span><i>Spezzati</i><strong>${splits}</strong></span></div></article>`}).join('')}</div>`;document.querySelectorAll('[data-week]').forEach(b=>b.classList.toggle('active',+b.dataset.week===i))}
document.querySelectorAll('[data-week]').forEach(b=>b.onclick=()=>renderWeek(+b.dataset.week));if(weeks.length)renderWeek(latest)}
const style=document.createElement('style');style.textContent=`.hours-page{max-width:1100px;margin:auto;padding:12px 12px 80px;color:#173d58}.hours-page header{display:flex;align-items:center;gap:12px;background:#0067b1;color:#fff;padding:14px 16px;border-radius:18px;border-bottom:5px solid #ffd100}.hours-page header a{color:#fff;text-decoration:none;font-weight:900}.hours-page header h1{margin:1px 0 0;font-size:22px}.hours-page header small{color:#ffd100;font-weight:900}.hours-intro,.hours-card{background:#fff;border:1px solid #dbe5ec;border-radius:18px;padding:14px;margin-top:11px;box-shadow:0 7px 20px rgba(0,60,100,.05)}.hours-intro b,.hours-intro span{display:block}.hours-intro span{font-size:12px;color:#6f8390;margin-top:3px}.hours-card h2{margin:0 0 10px;color:#003d7c}.hours-week-tabs{display:flex;gap:6px;overflow:auto;margin-bottom:10px}.hours-week-tabs button{white-space:nowrap;border:1px solid #c9d9e5;background:#fff;color:#003d7c;border-radius:999px;padding:8px 10px;font-weight:900}.hours-week-tabs button.active{background:#0067b1;color:#fff}.hours-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.hours-person{border:1px solid #e0e8ee;border-radius:13px;padding:10px;background:#fafdff;display:flex;align-items:center;justify-content:space-between;gap:8px}.hours-person b,.hours-person small{display:block}.hours-person b{color:#003d7c}.hours-person small{font-size:9px;color:#7a8d99;margin-top:2px}.hours-person>strong{color:#0067b1}.hours-person.full{display:block}.hours-metrics{display:grid;grid-template-columns:repeat(5,1fr);gap:5px;margin-top:8px}.hours-metrics span{background:#fff;border:1px solid #e1e8ed;border-radius:9px;padding:7px;text-align:center}.hours-metrics i,.hours-metrics strong{display:block}.hours-metrics i{font-style:normal;font-size:8px;color:#7a8d99}.hours-metrics strong{font-size:12px;color:#003d7c;margin-top:2px}.hours-metrics .over strong{color:#a23a2a}.hours-metrics .under strong{color:#876700}.hours-card details{border-top:1px solid #edf1f4}.hours-card details:first-of-type{border-top:0}.hours-card summary{padding:10px 0;font-weight:950;color:#003d7c;cursor:pointer}@media(max-width:650px){.hours-grid{grid-template-columns:1fr}.hours-metrics{grid-template-columns:repeat(3,1fr)}.hours-page{padding:8px 8px 70px}}`;document.head.appendChild(style);boot();
})();