const u=requireUser(true),app=document.getElementById('app');
const css=document.createElement('style');css.textContent=`.nt{max-width:860px;margin:auto;padding:12px}.nt-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}.nt-head a{color:#0067b1;font-weight:900}.card{background:#fff;border:1px solid #dbe5ec;border-radius:18px;padding:14px;margin-bottom:10px}.card h2,.card h3{margin:0 0 8px;color:#003d7c}.reqline{padding:8px 0;border-top:1px solid #e8eef2}.reqline:first-of-type{border-top:0}.statusok{background:#ecf9ef;border:1px solid #a8d8b2;color:#17602a;border-radius:14px;padding:12px;font-weight:900}.statusbad{background:#fff3c4;border:1px solid #e6c94e;color:#6b5600;border-radius:14px;padding:12px;font-weight:900}.actions{display:grid;gap:8px}.actions a,.actions button{padding:13px;border-radius:13px;text-align:center;font-weight:950}.publish{border:0;background:#0067b1;color:#fff}.view{background:#ffd500;color:#003d7c;border:0}.miniweek{display:grid;grid-template-columns:110px repeat(7,1fr);gap:3px;overflow:auto}.miniweek div{padding:7px;background:#f8fafc;border:1px solid #e0e7ec;font-size:10px;min-width:80px}.miniweek .name{font-weight:900;color:#003d7c;position:sticky;left:0;background:#fff;z-index:1}@media(max-width:620px){.nt{padding:8px}.miniweek{grid-template-columns:92px repeat(7,88px)}}`;document.head.appendChild(css);
let official=null,requests=[],draft=null,locked=new Set(),nextDates=[];
function dateRangeAfter(last){const d=new Date(last+'T12:00:00');d.setDate(d.getDate()+1);return Array.from({length:7},(_,i)=>{const x=new Date(d);x.setDate(d.getDate()+i);return x.toLocaleDateString('sv-SE')})}
function emptyWeek(dates){const names=['Umberto','Stefania B','Giada','Giuliano','Daniele','Manuel','Fabio','Emanuele','Romina','Stefania F','Paolo','Marco'],s={};for(const n of names)s[n]=Array(7).fill('—');return{label:`${new Date(dates[0]+'T12:00:00').getDate()}–${new Date(dates[6]+'T12:00:00').getDate()} ${new Intl.DateTimeFormat('it-IT',{month:'short'}).format(new Date(dates[0]+'T12:00:00')).replace('.','')}`,dates,schedule:s}}
function set(w,n,i,v){w.schedule[n][i]=v}
function buildBase(prev){const dates=dateRangeAfter(prev.dates.at(-1)),w=emptyWeek(dates),prevA=weekAfternoonGroup(prev),afternoon=prevA===T1?T2:T1,morning=afternoon===T1?T2:T1;nextDates=dates;
for(let i=0;i<6;i++){if(morning===T1){set(w,'Umberto',i,'06:30-13:30');set(w,'Stefania B',i,'06:30-13:30');set(w,'Giada',i,'09:00-14:00');const salas=['Giuliano','Daniele','Manuel'];if([0,2,3].includes(i)){const c=salas[[0,1,2][[0,2,3].indexOf(i)]%3];for(const n of salas)set(w,n,i,n===c?(i===2?'11:00-18:00':'10:00-17:00'):'07:00-14:00')}else for(const n of salas)set(w,n,i,'07:00-14:00')}else{set(w,'Fabio',i,'06:30-13:30');set(w,'Emanuele',i,'06:30-13:30');set(w,'Romina',i,'07:00-14:00');set(w,'Stefania F',i,'07:00-14:00');set(w,'Paolo',i,[0,2,3].includes(i)?(i===2?'11:00-18:00':'10:00-17:00'):'07:00-14:00')}
if(afternoon===T2){const rests=['Fabio','Emanuele','Romina','Stefania F','Paolo'];const r=i<5?rests[i]:null;for(const n of T2){if(n===r)set(w,n,i,'RIPOSO');else set(w,n,i,'13:30-20:30')}if(i===5)set(w,'Paolo',i,'14:00-20:00')}else{const rest=i===0?'Giuliano':i===1?'Daniele':i===2?'Manuel':i===3?'Umberto':null;for(const n of T1){if(n===rest)set(w,n,i,'RIPOSO');else set(w,n,i,'14:00-20:00')}if(rest==='Umberto'){set(w,'Emanuele',i,'06:30-13:30 / 17:00-20:30');set(w,'Stefania B',i,'13:30-20:30');set(w,'Giuliano',i,'13:30-20:30');set(w,'Daniele',i,'13:30-20:30')}else{set(w,'Umberto',i,'13:30-20:30');set(w,'Stefania B',i,'13:30-20:30');const avail=['Giuliano','Daniele','Manuel'].filter(n=>n!==rest);for(const n of avail.slice(0,2))set(w,n,i,'13:30-20:30')}if(i===4||i===5){set(w,'Umberto',i,'13:30-20:30');set(w,'Stefania B',i,'13:30-20:30');set(w,'Giuliano',i,'13:30-20:30');set(w,'Daniele',i,'13:30-20:30');set(w,'Giada',i,'14:00-20:00');set(w,'Manuel',i,'14:00-20:00')}}set(w,'Marco',i,[0,2,3,5].includes(i)?(i===5?'16:00-20:00':'16:30-20:30'):'—')}
for(const n of Object.keys(w.schedule))set(w,n,6,'RIPOSO');if(afternoon===T1){for(const n of ['Umberto','Giuliano','Daniele','Manuel'])set(w,n,6,'08:00-13:00')}else{for(const n of ['Fabio','Emanuele','Romina','Stefania F'])set(w,n,6,'08:00-13:00')}return w}
function parseAccepted(x){if(x.status!=='ACCETTATA'||!x.replied_at)return null;const m=String(x.message||''),g=m.match(/Giorno:\s*([^\n]+).*?Turno richiesto:\s*([^\n]+)/s);if(!g)return null;return{employee:x.employee,dateLabel:g[1].trim(),wanted:g[2].trim(),id:x.id}}
function applyAccepted(w){const used=[];for(const x of requests){const p=parseAccepted(x);if(!p)continue;const di=w.dates.findIndex(d=>fmtDate(d)===p.dateLabel);if(di<0||!w.schedule[p.employee])continue;w.schedule[p.employee][di]=p.wanted;locked.add(`${p.employee}|${di}`);used.push(p)}return used}
function candidates(n,cur){const a=['06:30-13:30','07:00-14:00','09:00-14:00','10:00-17:00','11:00-18:00','13:30-20:30','14:00-20:00','14:00-20:30','07:00-13:00 / 17:00-20:30','06:30-13:30 / 17:00-20:30','08:00-13:00','RIPOSO'];if(CASH.has(n))return [cur,'06:30-13:30','07:00-14:00','09:00-14:00','13:30-20:30','14:00-20:30','08:00-13:00','RIPOSO'];if(RESP.has(n))return [cur,'06:30-13:30','13:30-20:30','06:30-13:30 / 17:00-20:30','08:00-13:00','RIPOSO'];return [cur,...a]}
function repair(w){for(let pass=0;pass<5;pass++){let base=validateWeek(w).length;if(!base)break;let improved=false,best=null;for(let di=0;di<7;di++){for(const n of Object.keys(w.schedule)){if(locked.has(`${n}|${di}`))continue;const old=w.schedule[n][di];for(const s of candidates(n,old)){if(s===old)continue;w.schedule[n][di]=s;const score=validateWeek(w).length;if(score<base&&(!best||score<best.score))best={n,di,s,old,score};w.schedule[n][di]=old}}}if(best){w.schedule[best.n][best.di]=best.s;improved=true}if(!improved)break}return w}
function checkedIssues(w){let last=[];for(let i=0;i<5;i++)last=validateWeek(w);return last}
function draw(used){const issues=checkedIssues(draft),w=draft;localStorage.setItem('tm_planner_draft',JSON.stringify({week:w,issues,createdAt:new Date().toISOString()}));app.innerHTML=`<div class="app-shell"><div class="brandbar"></div><main class="nt"><div class="nt-head"><a href="index.html">‹ Home</a><strong>Nuovi Turni</strong><span></span></div><section class="card"><h2>${esc(w.label)}</h2><div>${used.length?used.map(r=>`<div class="reqline"><b>${esc(r.employee)}</b> · ${esc(r.dateLabel)} → ${esc(r.wanted)}</div>`).join(''):'<div class="reqline">Nessuna richiesta accettata per questa settimana.</div>'}</div></section><section class="card"><h3>Controllo regole</h3><div class="${issues.length?'statusbad':'statusok'}">${issues.length?`${issues.length} problemi rimasti dopo 5 controlli automatici.`:'✓ Tutte le regole risultano rispettate dopo 5 controlli.'}</div></section><section class="card"><div class="miniweek"><div></div>${w.dates.map(d=>`<div><b>${fmtDate(d).slice(0,3)}</b><br>${new Date(d+'T12:00:00').getDate()}</div>`).join('')}${Object.keys(w.schedule).map(n=>`<div class="name">${esc(n)}</div>${w.schedule[n].map(s=>`<div>${esc(s)}</div>`).join('')}`).join('')}</div></section><div class="actions">${issues.length?`<a class="view" href="turnations.html?draft=1">Vedi Turnazioni</a>`:`<button class="publish" id="publish">Pubblica settimana</button>`}</div></main></div>`;const b=document.getElementById('publish');if(b)b.onclick=publish}
async function publish(){const issues=checkedIssues(draft);if(issues.length)return location.href='turnations.html?draft=1';const data=structuredClone(official),idx=data.weeks.findIndex(x=>x.dates[0]===draft.dates[0]);if(idx>=0)data.weeks[idx]=draft;else data.weeks.push(draft);data.weeks.sort((a,b)=>a.dates[0].localeCompare(b.dates[0]));data.updated=new Intl.DateTimeFormat('it-IT',{dateStyle:'long',timeStyle:'short'}).format(new Date());try{await api('save_schedule',{method:'POST',body:{data}});localStorage.removeItem('tm_planner_draft');alert('Nuova settimana pubblicata. Regole controllate e richieste accettate applicate.');location.href='index.html'}catch(e){alert(e.message)}}
async function boot(){if(!u)return;try{official=await loadSchedule();const r=await api('list_requests');requests=r.requests||[];const prev=official.weeks.at(-1);draft=buildBase(prev);const used=applyAccepted(draft);repair(draft);draw(used)}catch(e){app.innerHTML=`<div class="error" style="margin:20px">${esc(e.message)}</div>`}}boot();