(()=>{
'use strict';
const CLEAN='https://dlqrhteqodkdkvmrwktu.supabase.co/functions/v1/turni-clean-api';
const TOOLS='https://dlqrhteqodkdkvmrwktu.supabase.co/functions/v1/turni-admin-tools-api';
const PEOPLE=['Umberto','Fabio','Emanuele','Stefania B','Stefania F','Romina','Giada','Giuliano','Manuel','Daniele','Paolo','Marco'];
const SHIFTS=['06:30-13:30','06:30-14:00','06:30-14:30','07:00-12:00','07:00-13:00','07:00-14:00','07:00-14:30','07:00-15:00','09:00-14:00','09:00-15:00','09:00-16:00','09:00-17:00','10:00-15:00','10:00-17:00','11:00-16:00','11:00-17:00','11:00-19:00','11:30-20:30','12:00-17:00','12:00-20:30','12:30-20:30','13:00-20:30','13:30-20:00','13:30-20:30','14:00-20:30','14:30-19:30','14:30-20:30','15:00-20:00','15:30-20:30','16:00-20:00','16:30-20:30','07:00-13:00 / 17:00-20:00','07:00-13:00 / 17:00-20:30','08:00-13:00','RIPOSO','FERIE','PERMESSO','MALATTIA'];
const token=()=>localStorage.getItem('tm2_token')||'';
const user=()=>{try{return JSON.parse(localStorage.getItem('tm2_user')||'{}')}catch{return{}}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const hm=t=>{const[a,b]=String(t).split(':').map(Number);return a*60+b};
const hours=s=>['RIPOSO','FERIE','PERMESSO','MALATTIA','MATERNITÀ','—'].includes(String(s||'').toUpperCase())?0:String(s||'').split('/').reduce((z,p)=>{const[a,b]=p.trim().split('-').map(x=>x.trim()),aa=hm(a),bb=hm(b);return z+(bb>aa?(bb-aa)/60:0)},0);
const fmt=d=>new Intl.DateTimeFormat('it-IT',{weekday:'short',day:'numeric',month:'short'}).format(new Date(d+'T12:00:00'));
async function req(url,method='GET',body){const r=await fetch(url,{method,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({error:'Risposta non valida'}));if(!r.ok)throw new Error(d.error||'Errore');return d}
async function tool(action,body){return req(`${TOOLS}?action=${encodeURIComponent(action)}`,'POST',body||{})}
let editor=null,week=0;
async function openEditor(){try{const d=await req(`${CLEAN}?action=get_schedule`),row=d.schedule;if(!row?.data?.weeks?.length)throw new Error('Nessun turno pubblicato');editor={id:row.id,data:JSON.parse(JSON.stringify(row.data))};week=0;renderEditor()}catch(e){alert(e.message)}}
function renderEditor(){document.getElementById('publishedEditBack')?.remove();const w=editor.data.weeks[week];const back=document.createElement('div');back.id='publishedEditBack';back.className='modalback';back.style.zIndex='12000';back.innerHTML=`<div class="modal" style="width:min(98vw,1200px);max-width:1200px;max-height:94vh;overflow:auto"><div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap"><div><h2 style="margin:0">✏️ Modifica turni pubblicati</h2><small>Le ore si aggiornano automaticamente.</small></div><button class="btn ghost" id="pubEditClose" style="margin-left:auto">Chiudi</button></div><div class="tabs" style="margin-top:12px">${editor.data.weeks.map((x,i)=>`<button class="${i===week?'active':''}" data-pubweek="${i}">Settimana ${i+1} · ${esc(fmt(x.dates[0]))}</button>`).join('')}</div><div class="tablewrap" style="margin-top:10px"><table class="turntable"><thead><tr><th>Persona</th>${w.dates.map(d=>`<th>${esc(fmt(d))}</th>`).join('')}<th>Ore</th></tr></thead><tbody>${PEOPLE.map(n=>`<tr><td><b>${esc(n)}</b></td>${w.dates.map((d,i)=>{const s=w.schedule[n]?.[i]||'RIPOSO';return `<td><button class="shift ${hours(s)?'':'off'}" data-pubedit="${esc(n)}" data-day="${i}" style="cursor:pointer">${esc(s)}</button></td>`}).join('')}<td class="hours"><b>${(w.schedule[n]||[]).reduce((z,s)=>z+hours(s),0)}h</b></td></tr>`).join('')}</tbody></table></div><div class="toolbar" style="margin-top:14px"><button class="btn blue" id="pubEditSave">Salva modifiche e aggiorna i dipendenti</button></div></div>`;document.body.appendChild(back);back.querySelector('#pubEditClose').onclick=()=>back.remove();back.querySelectorAll('[data-pubweek]').forEach(b=>b.onclick=()=>{week=+b.dataset.pubweek;renderEditor()});back.querySelectorAll('[data-pubedit]').forEach(b=>b.onclick=()=>editShift(b.dataset.pubedit,+b.dataset.day));back.querySelector('#pubEditSave').onclick=saveEditor;back.onclick=e=>{if(e.target===back)back.remove()}}
function editShift(name,day){const w=editor.data.weeks[week],cur=w.schedule[name]?.[day]||'RIPOSO';document.getElementById('shiftPickBack')?.remove();const back=document.createElement('div');back.id='shiftPickBack';back.className='modalback';back.style.zIndex='12100';back.innerHTML=`<div class="modal" style="max-width:430px"><h3>${esc(name)} · ${esc(fmt(w.dates[day]))}</h3><div class="field"><label>Nuovo turno</label><select id="pubShiftPick">${[...new Set([cur,...SHIFTS])].map(s=>`<option ${s===cur?'selected':''}>${esc(s)}</option>`).join('')}</select></div><div class="toolbar"><button class="btn ghost" id="pubPickCancel">Annulla</button><button class="btn primary" id="pubPickSave">Applica</button></div></div>`;document.body.appendChild(back);back.querySelector('#pubPickCancel').onclick=()=>back.remove();back.querySelector('#pubPickSave').onclick=()=>{w.schedule[name][day]=back.querySelector('#pubShiftPick').value;back.remove();renderEditor()}}
async function saveEditor(){if(!confirm('Salvare le modifiche ai turni pubblicati? I dipendenti vedranno subito la nuova turnazione.'))return;const b=document.getElementById('pubEditSave');b.disabled=true;b.textContent='Salvataggio…';try{const d=await tool('update_schedule',{scheduleId:editor.id,data:editor.data});alert(`Turni aggiornati.${d.push?.sent?` Notifiche inviate: ${d.push.sent}.`:''}`);location.reload()}catch(e){alert(e.message);b.disabled=false;b.textContent='Salva modifiche e aggiorna i dipendenti'}}
function mountSchedule(){if(user().role!=='admin'||location.hash!=='#schedule')return;if(document.getElementById('publishedEditBtn'))return;const hero=[...document.querySelectorAll('.hero')].find(x=>/Turni pubblicati/i.test(x.textContent||''));if(!hero)return;const b=document.createElement('button');b.id='publishedEditBtn';b.className='btn primary';b.type='button';b.style.marginTop='10px';b.textContent='✏️ Modifica turni pubblicati';b.onclick=openEditor;hero.appendChild(b)}
function mountAnnouncements(){if(user().role!=='admin'||location.hash!=='#announcements')return;const send=document.getElementById('sendAnn');if(send&&!send.dataset.pushEnhanced){const clone=send.cloneNode(true);clone.dataset.pushEnhanced='1';send.replaceWith(clone);clone.onclick=async()=>{const m=document.getElementById('annMsg')?.value.trim();if(!m)return;clone.disabled=true;clone.textContent='Pubblicazione…';try{await req(`${CLEAN}?action=create_announcement`,'POST',{message:m});const p=await tool('notify_employees',{title:'Nuovo avviso',message:m,url:'/Portafoglio/turni-v2/#announcements'});alert(`Avviso pubblicato.${p.sent?` Notifiche inviate: ${p.sent}.`:''}`);location.reload()}catch(e){alert(e.message);clone.disabled=false;clone.textContent='Pubblica'}}}
if(!document.getElementById('publishTurnsNotice')){const card=send?.closest('.card')||document.querySelector('#annMsg')?.closest('.card');if(card){const b=document.createElement('button');b.id='publishTurnsNotice';b.className='btn primary';b.type='button';b.style.marginLeft='8px';b.textContent='📅 Pubblica turni';b.onclick=async()=>{if(!confirm('Inviare ai dipendenti la notifica che i nuovi turni sono stati pubblicati?'))return;b.disabled=true;try{const d=await tool('publish_turns_notice',{});alert(`Avviso creato.${d.push?.sent?` Notifiche inviate: ${d.push.sent}.`:''}`);location.reload()}catch(e){alert(e.message);b.disabled=false}};card.appendChild(b)}}}
function mount(){mountSchedule();mountAnnouncements()}
new MutationObserver(mount).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('hashchange',()=>setTimeout(mount,0));setTimeout(mount,200);
})();
