(()=>{
'use strict';

const API='https://dlqrhteqodkdkvmrwktu.supabase.co/functions/v1/turni-clean-api';
const SAFE='https://dlqrhteqodkdkvmrwktu.supabase.co/functions/v1/turni-safe-generate-v1';
const ONE_FERIE='https://dlqrhteqodkdkvmrwktu.supabase.co/functions/v1/turni-one-ferie-manual-v1';
const ALT='https://dlqrhteqodkdkvmrwktu.supabase.co/functions/v1/turni-alt-generate-guard-v1';
const DELETE='https://dlqrhteqodkdkvmrwktu.supabase.co/functions/v1/turni-delete-weeks-v1';
const TOOLS='https://dlqrhteqodkdkvmrwktu.supabase.co/functions/v1/turni-admin-tools-api';
const LOGO='https://upload.wikimedia.org/wikipedia/commons/5/57/Eurospin_New_Logo.svg';

const PEOPLE=['Umberto','Fabio','Emanuele','Stefania B','Stefania F','Romina','Giada','Giuliano','Manuel','Daniele','Paolo','Daniele2'];
const ROLE={Umberto:'Responsabile',Fabio:'Responsabile',Emanuele:'Responsabile','Stefania B':'Cassa','Stefania F':'Cassa',Romina:'Cassa',Giada:'Cassa',Giuliano:'Sala',Manuel:'Sala',Daniele:'Sala',Paolo:'Sala',Daniele2:'Sala'};
const TARGET={Giada:30,Daniele2:30};
const CASH_ENABLED=new Set(['Stefania B','Stefania F','Romina','Giada','Giuliano','Manuel','Daniele']);
const OFF=new Set(['RIPOSO','FERIE','PERMESSO','MALATTIA','MATERNITÀ','—','']);
const SHIFTS=['06:30-13:30','06:30-14:00','06:30-14:30','07:00-12:00','07:00-13:00','07:00-14:00','07:00-14:30','07:00-15:00','08:00-13:00','09:00-14:00','09:00-15:00','09:00-16:00','09:00-17:00','10:00-15:00','10:00-17:00','10:00-18:00','11:00-16:00','11:00-17:00','11:00-19:00','11:00-20:00','11:30-20:30','12:00-17:00','12:00-20:30','12:30-20:30','13:00-20:30','13:30-20:00','13:30-20:30','14:00-20:30','14:30-19:30','14:30-20:30','15:00-20:00','15:30-20:30','16:00-20:00','16:30-20:30','07:00-13:00 / 17:00-20:00','07:00-13:00 / 17:00-20:30','RIPOSO','FERIE','PERMESSO','MALATTIA'];

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ymd=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const date=s=>new Date(`${s}T12:00:00`);
const isMonday=s=>/^\d{4}-\d{2}-\d{2}$/.test(String(s||''))&&date(s).getDay()===1;
const add=(s,n)=>{const d=date(s);d.setDate(d.getDate()+n);return ymd(d)};
const fmt=(s,opt={weekday:'short',day:'numeric',month:'short'})=>new Intl.DateTimeFormat('it-IT',opt).format(date(s));
const hm=t=>{const [h,m]=String(t).split(':').map(Number);return h*60+m};
const spans=s=>OFF.has(String(s||'').trim().toUpperCase())?[]:String(s||'').split('/').map(x=>x.trim()).map(x=>x.split('-').map(y=>y.trim())).map(([a,b])=>[hm(a),hm(b)]).filter(([a,b])=>Number.isFinite(a)&&Number.isFinite(b)&&b>a);
const hours=s=>spans(s).reduce((z,[a,b])=>z+(b-a)/60,0);
const weekHours=(w,n)=>(w?.schedule?.[n]||[]).reduce((z,s)=>z+hours(s),0);
const isAdmin=()=>S.user?.role==='admin';
const token=()=>S.token||localStorage.getItem('tm2_token')||'';

const S={token:localStorage.getItem('tm2_token')||'',user:null,route:(location.hash||'#home').slice(1),schedule:null,requests:[],absences:[],announcements:[],draft:null,week:0,day:0,createStep:'choice',busy:false};
let modalSeq=0;

async function call(url,{method='GET',body}={}){
  const r=await fetch(url,{method,cache:'no-store',headers:{'Content-Type':'application/json',...(token()?{Authorization:`Bearer ${token()}`}:{})},body:body?JSON.stringify(body):undefined});
  const d=await r.json().catch(()=>({error:'Risposta non valida'}));
  if(!r.ok)throw new Error(d.error||`Errore ${r.status}`);
  return d;
}
const api=(action,opts={})=>call(`${API}?action=${encodeURIComponent(action)}`,opts);
const tool=(action,body)=>call(`${TOOLS}?action=${encodeURIComponent(action)}`,{method:'POST',body:body||{}});

function saveAuth(d){S.token=d.token;S.user=d.user;localStorage.setItem('tm2_token',S.token);localStorage.setItem('tm2_user',JSON.stringify(S.user))}
function clearAuth(){S.token='';S.user=null;localStorage.removeItem('tm2_token');localStorage.removeItem('tm2_user')}
function go(r){S.route=r;location.hash=r;render()}
function toast(msg,type='ok'){let e=$('#toast');if(!e){e=document.createElement('div');e.id='toast';document.body.appendChild(e)}e.className=`toast ${type}`;e.textContent=msg;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2200)}
function modal(html){const b=document.createElement('div');b.className='modalback';b.dataset.modal=String(++modalSeq);b.style.zIndex=String(200+modalSeq);b.innerHTML=`<div class="modal">${html}</div>`;document.body.appendChild(b);b.addEventListener('click',e=>{if(e.target===b)b.remove()});return b}
function confirmBox(title,text,yes='Conferma'){return new Promise(resolve=>{const b=modal(`<div class="modal-head"><h3>${esc(title)}</h3><button data-close>×</button></div><p class="modal-text">${esc(text)}</p><div class="modal-actions"><button class="btn secondary" data-close>Annulla</button><button class="btn danger" id="modalYes">${esc(yes)}</button></div>`);b.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>{b.remove();resolve(false)});b.querySelector('#modalYes').onclick=()=>{b.remove();resolve(true)}})}

async function hydrate(){
  const jobs=[loadSchedule(),loadRequests(),loadAnnouncements()];
  if(isAdmin())jobs.push(loadAbsences());
  await Promise.all(jobs.map(p=>p.catch(()=>{})));
}
async function loadSchedule(){const d=await api('get_schedule');S.schedule=d.schedule||null;return S.schedule}
async function loadRequests(){const d=await api('my_requests');S.requests=d.requests||[];return S.requests}
async function loadAbsences(){if(!isAdmin())return[];const d=await api('absences');S.absences=d.absences||[];return S.absences}
async function loadAnnouncements(){const d=await api('announcements');S.announcements=d.announcements||[];return S.announcements}

function nav(){return isAdmin()?[['home','⌂','Home'],['schedule','▣','Turni'],['create','＋','Crea'],['requests','▤','Richieste'],['more','☰','Altro']]:[['home','⌂','Home'],['schedule','▣','Turni'],['requests','▤','Richieste'],['announcements','♢','Avvisi'],['more','☰','Altro']]}
function headerTitle(){const map={home:isAdmin()?'Area responsabile':'',schedule:isAdmin()?'Turni pubblicati':'I miei turni',create:'Crea turni',requests:'Richieste',announcements:'Avvisi',absences:'Ferie e assenze',hours:'Conteggio ore',more:'Altro'};return map[S.route]||'Eurospin'}
function shell(content){
  const n=nav(),home=S.route==='home';
  return `<div class="app-shell"><header class="app-header ${home?'home-header':''}">${home?`<img class="brand-logo" src="${LOGO}" alt="Eurospin"><div class="hello"><strong>${isAdmin()?'Ciao, '+esc(S.user.displayName||'Responsabile'):'Ciao, '+esc(S.user.displayName||S.user.employeeName||'')}</strong><small>${isAdmin()?'Gestione negozio · Torre Maura':'Buon lavoro!'}</small></div><button class="avatar" data-go="more" aria-label="Altro">●</button>`:`<button class="back" data-back>‹</button><strong class="page-title">${esc(headerTitle())}</strong><span class="head-spacer"></span>`}</header><main class="app-main">${content}</main><nav class="bottom-nav">${n.map(([r,i,t])=>`<button data-go="${r}" class="${S.route===r?'active':''}"><span>${i}</span><small>${t}</small></button>`).join('')}</nav></div>`
}
function bindShell(){
  $$('[data-go]').forEach(x=>x.onclick=()=>go(x.dataset.go));
  $('[data-back]')?.addEventListener('click',()=>go('home'));
}

function loginView(){
  return `<div class="login-page"><section class="login-visual"><img src="${LOGO}" class="login-logo" alt="Eurospin"><div class="login-copy"><h1>Benvenuto</h1><p>Accedi alla tua area riservata</p></div><div class="store-shape"></div></section><section class="login-panel"><label class="login-field"><span>◎</span><input id="loginUser" autocomplete="username" placeholder="Matricola o email"></label><label class="login-field"><span>▣</span><input id="loginPass" type="password" inputmode="numeric" autocomplete="current-password" placeholder="Password"><button type="button" id="showPass">◉</button></label><div class="login-meta"><label><input type="checkbox" checked> Ricordami</label><span>Area riservata dipendenti</span></div><button class="btn primary wide" id="loginBtn">Accedi</button><div id="loginMsg"></div><div class="login-slogan">Persone. Turni. Un unico obiettivo.<i></i></div></section></div>`
}
async function doLogin(){const b=$('#loginBtn'),m=$('#loginMsg');b.disabled=true;b.textContent='Accesso…';try{const d=await api('login',{method:'POST',body:{username:$('#loginUser').value.trim(),password:$('#loginPass').value}});saveAuth(d);S.route='home';location.hash='home';await hydrate();render()}catch(e){m.innerHTML=`<div class="inline-error">${esc(e.message)}</div>`}finally{b.disabled=false;b.textContent='Accedi'}}
function bindLogin(){
  $('#loginBtn').onclick=doLogin;$('#loginPass').onkeydown=e=>{if(e.key==='Enter')doLogin()};
  $('#showPass').onclick=()=>{const p=$('#loginPass');p.type=p.type==='password'?'text':'password'};
}

function nextShift(){const d=S.schedule?.data;if(!d?.weeks?.length||!S.user?.employeeName)return null;const today=ymd(new Date()),rows=[];d.weeks.forEach(w=>w.dates.forEach((x,i)=>rows.push({date:x,shift:w.schedule?.[S.user.employeeName]?.[i]||'RIPOSO'})));return rows.filter(x=>x.date>=today&&!OFF.has(String(x.shift).toUpperCase())).sort((a,b)=>a.date.localeCompare(b.date))[0]||null}
function employeeHome(){
  const x=nextShift(),openReq=S.requests.filter(r=>r.status==='DA_VALUTARE').length,ann=S.announcements.length;
  return shell(`<section class="next-card"><div class="section-title"><span class="iconbox">▣</span><strong>Il tuo prossimo turno</strong></div>${x?`<button class="next-shift" id="nextShiftBtn"><small>${esc(fmt(x.date,{weekday:'long',day:'numeric',month:'long'}))}</small><strong>${esc(x.shift)}</strong><span>${esc(ROLE[S.user.employeeName]||'Turno')} · Torre Maura</span><b>›</b></button>`:`<div class="empty-mini">Nessun turno programmato.</div>`}<button class="btn primary wide" data-go="schedule">Vedi tutti i turni</button></section><section class="quick-grid"><button data-go="schedule"><span>▣</span><b>I miei turni</b><small>Consulta settimana e dettagli</small></button><button data-go="requests"><span>▤</span><b>Richieste</b><small>${openReq?`${openReq} in valutazione`:'Ferie, permessi, cambi'}</small></button><button data-go="announcements"><span>♢</span><b>Avvisi</b><small>${ann?`${ann} comunicazioni attive`:'Comunicazioni negozio'}</small></button><button id="myHours"><span>◷</span><b>Le mie ore</b><small>Ore delle settimane pubblicate</small></button></section><section class="brand-banner"><div><strong>Un grande lavoro,<br>ogni giorno.</strong><p>La spesa intelligente siamo noi.</p></div><img src="${LOGO}" alt="Eurospin"></section>`)
}
function adminHome(){
  const w=S.schedule?.data?.weeks?.length||0,open=S.requests.filter(r=>r.status==='DA_VALUTARE').length,abs=S.absences.length;
  return shell(`<section class="admin-hero"><div><small>EUROSPIN · TORRE MAURA</small><h1>La squadra che fa la differenza</h1><p>Persone. Turni. Un unico obiettivo.</p></div><img src="${LOGO}" alt="Eurospin"></section><section class="stats"><div><b>${w}</b><small>settimane pubblicate</small></div><div><b>${open}</b><small>richieste aperte</small></div><div><b>${abs}</b><small>assenze inserite</small></div></section><section class="admin-actions"><button data-go="create"><span>＋</span><div><b>Crea turni</b><small>Genera automaticamente o crea da zero</small></div><i>›</i></button><button data-go="schedule"><span>▣</span><div><b>Turni pubblicati</b><small>Consulta, modifica e gestisci settimane</small></div><i>›</i></button><button data-go="requests"><span>▤</span><div><b>Richieste dipendenti</b><small>Accetta, rifiuta o rimetti in valutazione</small></div><i>›</i></button><button data-go="absences"><span>☂</span><div><b>Ferie e assenze</b><small>Gestisci ferie, permessi e malattie</small></div><i>›</i></button><button data-go="hours"><span>◷</span><div><b>Conteggio ore</b><small>Contratti, ore settimanali e scostamenti</small></div><i>›</i></button><button data-go="announcements"><span>♢</span><div><b>Avvisi</b><small>Comunicazioni e notifiche al personale</small></div><i>›</i></button></section>`)
}
function homeView(){return isAdmin()?adminHome():employeeHome()}

function scheduleData(){return S.draft||S.schedule?.data||null}
function weekPicker(data){return `<div class="week-picker">${data.weeks.map((w,i)=>`<button data-week="${i}" class="${S.week===i?'active':''}"><b>Settimana ${i+1}</b><small>${esc(fmt(w.dates[0]))} – ${esc(fmt(w.dates[6]))}</small></button>`).join('')}</div>`}
function employeeSchedule(){
  const data=S.schedule?.data;if(!data?.weeks?.length)return shell(`<div class="empty-state"><span>▣</span><h2>Nessun turno pubblicato</h2><p>Quando verrà pubblicata una turnazione la vedrai qui.</p></div>`);
  S.week=Math.max(0,Math.min(S.week,data.weeks.length-1));const w=data.weeks[S.week],n=S.user.employeeName;
  return shell(`${weekPicker(data)}<section class="day-strip">${w.dates.map((d,i)=>`<button data-day="${i}" class="${S.day===i?'active':''}"><small>${esc(fmt(d,{weekday:'short'}).replace('.',''))}</small><b>${date(d).getDate()}</b></button>`).join('')}</section><section class="shift-list">${w.dates.map((d,i)=>{const s=w.schedule?.[n]?.[i]||'RIPOSO',off=OFF.has(String(s).toUpperCase());return `<button class="shift-row ${off?'off':''}" data-detail="${i}"><i></i><div class="shift-date"><small>${esc(fmt(d,{weekday:'long'}))}</small><b>${esc(fmt(d,{day:'numeric',month:'short'}))}</b></div><div class="shift-time"><b>${esc(s)}</b>${off?'':`<small>${esc(ROLE[n]||'Turno')} · ${CASH_ENABLED.has(n)?'Abilitato cassa':'Sala'}</small>`}</div><span>›</span></button>`}).join('')}</section>`)
}
function adminSchedule(){
  const row=S.schedule,data=row?.data;if(!data?.weeks?.length)return shell(`<div class="empty-state"><span>▣</span><h2>Nessun turno pubblicato</h2><p>Crea o genera una nuova turnazione.</p><button class="btn primary" data-go="create">Crea turni</button></div>`);
  S.week=Math.max(0,Math.min(S.week,data.weeks.length-1));const w=data.weeks[S.week];
  return shell(`<section class="screen-actions"><button class="btn primary" id="editPublished">✎ Modifica turni</button><button class="btn secondary" id="manageWeeks">▣ Gestisci settimane</button><button class="btn secondary" data-go="create">＋ Nuovi turni</button></section>${weekPicker(data)}<section class="coverage-card"><div><b>${esc(fmt(w.dates[0],{day:'numeric',month:'long'}))} – ${esc(fmt(w.dates[6],{day:'numeric',month:'long'}))}</b><small>Controllo rapido della settimana</small></div><div class="coverage-tags"><span>4 chiusura</span><span>2 cassa alle 20</span><span>Paolo/Daniele2 separati</span></div></section>${adminScheduleTable(w)}`)
}
function adminScheduleTable(w,editable=false){return `<section class="schedule-table-card"><div class="table-scroll"><table class="schedule-table"><thead><tr><th>Dipendente</th>${w.dates.map(d=>`<th>${esc(fmt(d,{weekday:'short',day:'numeric'}))}</th>`).join('')}<th>Ore</th></tr></thead><tbody>${PEOPLE.map(n=>`<tr><td><b>${esc(n)}</b><small>${esc(ROLE[n])}${CASH_ENABLED.has(n)?' · Cassa':''}</small></td>${w.dates.map((d,i)=>`<td>${editable?`<button class="shift-cell" data-person="${esc(n)}" data-index="${i}">${esc(w.schedule?.[n]?.[i]||'RIPOSO')}</button>`:`<span class="shift-cell static">${esc(w.schedule?.[n]?.[i]||'RIPOSO')}</span>`}</td>`).join('')}<td><b>${weekHours(w,n)}h</b><small>target ${TARGET[n]||40}h</small></td></tr>`).join('')}</tbody></table></div></section>`}
function scheduleView(){return isAdmin()?adminSchedule():employeeSchedule()}

function shiftDetail(w,i,n){const s=w.schedule?.[n]?.[i]||'RIPOSO',d=w.dates[i],off=OFF.has(String(s).toUpperCase());const b=modal(`<div class="modal-head"><h3>Dettaglio turno</h3><button data-close>×</button></div><section class="detail-summary"><div class="datebox"><small>${esc(fmt(d,{weekday:'short'}).toUpperCase())}</small><b>${date(d).getDate()}</b><span>${esc(fmt(d,{month:'long'}))}</span></div><div><strong>${esc(s)}</strong><span>${esc(ROLE[n]||'Turno')}</span>${off?'':'<em>Confermato</em>'}</div></section><div class="detail-list"><div><span>●</span><small>Negozio</small><b>Roma · Torre Maura</b></div><div><span>▣</span><small>Reparto</small><b>${esc(ROLE[n]||'Turno')}</b></div><div><span>⌁</span><small>Cassa</small><b>${CASH_ENABLED.has(n)?'Abilitato':'Non abilitato'}</b></div></div>${!off?`<div class="detail-actions"><button data-action="swap">⇄ Scambia turno <b>›</b></button><button data-action="edit">✎ Richiedi modifica <b>›</b></button><button class="danger" data-action="absence">! Segnala indisponibilità <b>›</b></button></div>`:''}`);b.querySelector('[data-close]').onclick=()=>b.remove();b.querySelectorAll('[data-action]').forEach(x=>x.onclick=()=>{sessionStorage.setItem('tm_req_date',d);sessionStorage.setItem('tm_req_kind',x.dataset.action==='absence'?'ALTRO':'TURNO');sessionStorage.setItem('tm_req_msg',x.dataset.action==='absence'?'Segnalo indisponibilità per questo turno.':x.dataset.action==='edit'?'Richiedo una modifica del turno.':'Richiedo uno scambio turno.');b.remove();go('requests')})}

function createChoice(){return shell(`<section class="create-intro"><h1>Come vuoi creare i turni?</h1><p>Scegli il metodo. In entrambi i casi potrai controllare e modificare la bozza prima di pubblicarla.</p></section><section class="choice-grid"><button id="chooseGenerate"><span>✦</span><b>GENERA</b><small>Il sistema costruisce automaticamente la turnazione rispettando regole, ferie e richieste.</small><i>Generazione automatica ›</i></button><button id="chooseManual"><span>✎</span><b>CREA</b><small>Parti da una turnazione vuota e assegna personalmente ogni turno.</small><i>Creazione manuale ›</i></button></section><section class="help-card"><b>Prima di iniziare</b><p>Le ferie e le richieste accettate vengono considerate dalla generazione automatica. La creazione manuale resta completamente sotto il tuo controllo.</p></section>`)}
function defaultStart(){const end=S.schedule?.end_date||S.schedule?.data?.endDate;if(end)return add(end,1);const d=new Date();d.setHours(12,0,0,0);const q=(8-d.getDay())%7||7;d.setDate(d.getDate()+q);return ymd(d)}
function generatePage(){
  const start=defaultStart();
  const relAbs=S.absences.filter(a=>a.date_to>=start&&a.date_from<=add(start,20));
  const req=S.requests.filter(r=>r.status==='ACCETTATA'&&['RIPOSO','TURNO'].includes(String(r.kind).toUpperCase())&&r.request_date>=start&&r.request_date<=add(start,20));
  return shell(`<section class="subnav"><button id="backCreate">‹ Metodo</button><strong>Generazione automatica</strong></section><section class="form-card"><label><span>Lunedì iniziale</span><input id="genStart" type="date" value="${esc(start)}"></label><div class="generation-status"><div><b>${relAbs.length}</b><small>assenze nel periodo</small></div><div><b>${req.length}</b><small>richieste accettate</small></div></div><button class="btn primary wide" id="runGenerate" ${S.busy?'disabled':''}>${S.busy?'Calcolo in corso…':'Genera 3 settimane'}</button><div id="genMessage"></div></section><section class="form-card"><div class="section-heading"><div><h3>Ferie e assenze</h3><p>Puoi gestirle qui senza uscire dalla creazione turni.</p></div><button class="btn secondary small" data-go="absences">Gestisci</button></div>${relAbs.length?`<div class="compact-list">${relAbs.slice(0,5).map(a=>`<div><b>${esc(a.employee_name)}</b><span>${esc(a.absence_type)} · ${esc(a.date_from)} → ${esc(a.date_to)}</span></div>`).join('')}</div>`:'<div class="empty-mini">Nessuna assenza nel periodo.</div>'}</section>`)
}
function manualSetupPage(){return shell(`<section class="subnav"><button id="backCreate">‹ Metodo</button><strong>Creazione manuale</strong></section><section class="form-card"><label><span>Lunedì iniziale</span><input id="manualStart" type="date" value="${esc(defaultStart())}"></label><label><span>Numero settimane</span><select id="manualWeeks"><option value="1">1 settimana</option><option value="2">2 settimane</option><option value="3" selected>3 settimane</option></select></label><div class="manual-note">La bozza parte con tutti in <b>RIPOSO</b>. Tocca ogni persona per assegnare il turno. Le ore si aggiornano subito.</div><button class="btn primary wide" id="startManual">Crea bozza manuale</button></section>`)}
function createView(){if(S.createStep==='generate')return generatePage();if(S.createStep==='manualSetup')return manualSetupPage();if(S.createStep==='editor'&&S.draft)return draftEditor();return createChoice()}

function makeBlank(start,count){const weeks=[];for(let wi=0;wi<count;wi++){const ws=add(start,wi*7),dates=Array.from({length:7},(_,i)=>add(ws,i)),schedule={};PEOPLE.forEach(n=>schedule[n]=Array(7).fill('RIPOSO'));weeks.push({label:`Settimana ${wi+1}`,dates,schedule,meta:{manual:true}})}return{startDate:start,endDate:add(start,count*7-1),generatedAt:new Date().toISOString(),manual:true,weeks}}
function draftEditor(){const d=S.draft;S.week=Math.max(0,Math.min(S.week,d.weeks.length-1));S.day=Math.max(0,Math.min(S.day,6));const w=d.weeks[S.week];return shell(`<section class="draft-top"><div><small>${d.manual?'CREAZIONE MANUALE':'BOZZA GENERATA'}</small><h2>Controlla e modifica</h2></div><button class="btn secondary small" id="discardDraft">Annulla</button></section>${weekPicker(d)}<section class="day-strip editor-days">${w.dates.map((x,i)=>`<button data-day="${i}" class="${S.day===i?'active':''}"><small>${esc(fmt(x,{weekday:'short'}).replace('.',''))}</small><b>${date(x).getDate()}</b></button>`).join('')}</section><section class="manual-editor"><div class="editor-date"><b>${esc(fmt(w.dates[S.day],{weekday:'long',day:'numeric',month:'long'}))}</b><small>Tocca un turno per modificarlo</small></div>${PEOPLE.map(n=>{const s=w.schedule[n]?.[S.day]||'RIPOSO';return `<button class="person-shift" data-edit-person="${esc(n)}"><div><b>${esc(n)}</b><small>${esc(ROLE[n])}${CASH_ENABLED.has(n)?' · Cassa':''}</small></div><span class="${OFF.has(String(s).toUpperCase())?'off':''}">${esc(s)}</span><i>›</i></button>`}).join('')}</section><section class="hours-overview"><h3>Ore settimana</h3><div>${PEOPLE.map(n=>{const h=weekHours(w,n),t=TARGET[n]||40;return `<span class="${h>t?'over':''}"><b>${esc(n)}</b><em>${h}h / ${t}h</em></span>`}).join('')}</div></section><div class="sticky-actions"><button class="btn primary" id="publishDraft">Pubblica ${d.weeks.length===1?'settimana':'turnazione'}</button></div>`)}
function editDraftShift(name){const w=S.draft.weeks[S.week],cur=w.schedule[name][S.day];const b=modal(`<div class="modal-head"><h3>${esc(name)}</h3><button data-close>×</button></div><p class="modal-text">${esc(fmt(w.dates[S.day],{weekday:'long',day:'numeric',month:'long'}))}</p><label class="modal-field"><span>Turno</span><select id="draftShift">${[...new Set([cur,...SHIFTS])].map(s=>`<option ${s===cur?'selected':''}>${esc(s)}</option>`).join('')}</select></label><div class="modal-actions"><button class="btn secondary" data-close>Annulla</button><button class="btn primary" id="saveDraftShift">Salva</button></div>`);b.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>b.remove());b.querySelector('#saveDraftShift').onclick=()=>{w.schedule[name][S.day]=b.querySelector('#draftShift').value;b.remove();render()}}

async function generateAutomatic(){
  if(S.busy)return;
  const start=$('#genStart').value;
  if(!/^\d{4}-\d{2}-\d{2}$/.test(start))return toast('Data non valida','error');
  if(!isMonday(start))return toast('La data iniziale deve essere un lunedì','error');
  S.busy=true;render();
  try{
    await Promise.all([loadAbsences(),loadRequests()]);const end=add(start,20),abs=S.absences.filter(a=>a.date_from<=end&&a.date_to>=start),accepted=S.requests.filter(r=>r.status==='ACCETTATA'&&['RIPOSO','TURNO'].includes(String(r.kind).toUpperCase())&&r.request_date>=start&&r.request_date<=end);const ferie=abs.filter(a=>String(a.absence_type).toUpperCase()==='FERIE');
    const byWeek=[0,1,2].map(i=>{const a=add(start,i*7),z=add(a,6);return[...new Set(ferie.filter(x=>x.date_from<=z&&x.date_to>=a).map(x=>x.employee_name))]});
    let d;
    if(!abs.length&&!accepted.length){d=await call(SAFE,{method:'POST',body:{startDate:start}})}
    else if(byWeek.some(x=>x.length===2)){const firstTwo=byWeek.findIndex(x=>x.length===2);if(firstTwo!==0||byWeek.slice(1).some(x=>x.length>1))throw new Error('Con 2 persone in FERIE è disponibile la generazione alternativa della singola settimana. Riduci il periodo o crea manualmente.');d=await call(ALT,{method:'POST',body:{startDate:start}})}
    else if(ferie.length&&byWeek.every(x=>x.length<=1)){d=await call(ONE_FERIE,{method:'POST',body:{startDate:start}})}
    else{d=await api('generate',{method:'POST',body:{startDate:start}})}
    S.busy=false;S.draft=d.schedule;S.week=0;S.day=0;S.createStep='editor';render();
  }catch(e){S.busy=false;S.createStep='generate';render();setTimeout(()=>{const m=$('#genMessage');if(m)m.innerHTML=`<div class="inline-error">${esc(e.message)}</div>`},0)}
}
async function publishDraft(){if(!S.draft)return;const ok=await confirmBox('Pubblicare turnazione?','I dipendenti vedranno subito i nuovi turni nell’app.','Pubblica');if(!ok)return;try{await api('publish',{method:'POST',body:{schedule:S.draft}});S.draft=null;S.schedule=null;S.createStep='choice';await loadSchedule();toast('Turni pubblicati');go('schedule')}catch(e){toast(e.message,'error')}}

function requestsEmployee(){
  return shell(`<section class="request-tabs"><button class="active" data-rtab="new">Nuova richiesta</button><button data-rtab="mine">Le mie richieste</button></section><section id="reqNew"><div class="request-menu"><button data-kind="FERIE"><span class="green">☂</span><b>Ferie</b><i>›</i></button><button data-kind="PERMESSO"><span>▤</span><b>Permesso</b><i>›</i></button><button data-kind="TURNO"><span>⇄</span><b>Cambio turno</b><i>›</i></button><button data-kind="RIPOSO"><span>▣</span><b>Giorno di riposo</b><i>›</i></button><button data-kind="ALTRO"><span>◷</span><b>Disponibilità / altro</b><i>›</i></button><button data-kind="ABSENCE" class="danger"><span>!</span><b>Segnala assenza</b><i>›</i></button></div><div class="info-box">ⓘ Le richieste sono soggette ad approvazione del responsabile di negozio.</div></section><section id="reqMine" hidden>${employeeRequestHistory()}</section>`)
}
function employeeRequestHistory(){return S.requests.length?`<div class="history-list">${S.requests.map(r=>`<div class="history-card"><div><b>${esc(r.kind)}</b>${requestBadge(r.status)}</div><small>${r.request_date?esc(fmt(r.request_date,{day:'numeric',month:'long',year:'numeric'})):'Senza data'}</small>${r.wanted_shift?`<p>Turno: <b>${esc(r.wanted_shift)}</b></p>`:''}${r.message?`<p>${esc(r.message)}</p>`:''}${r.reply?`<div class="reply">Risposta: ${esc(r.reply)}</div>`:''}</div>`).join('')}</div>`:'<div class="empty-state small"><span>▤</span><h3>Nessuna richiesta</h3></div>'}
function requestBadge(s){return `<span class="status ${s==='ACCETTATA'?'ok':s==='RIFIUTATA'?'no':'wait'}">${s==='ACCETTATA'?'Accettata':s==='RIFIUTATA'?'Rifiutata':'In valutazione'}</span>`}
function requestForm(kind){const real=kind==='ABSENCE'?'ALTRO':kind,presetDate=sessionStorage.getItem('tm_req_date')||'',presetMsg=sessionStorage.getItem('tm_req_msg')||(kind==='ABSENCE'?'Segnalo assenza/indisponibilità: ':'');sessionStorage.removeItem('tm_req_date');sessionStorage.removeItem('tm_req_kind');sessionStorage.removeItem('tm_req_msg');const b=modal(`<div class="modal-head"><h3>${kind==='ABSENCE'?'Segnala assenza':kind==='TURNO'?'Cambio turno':kind.charAt(0)+kind.slice(1).toLowerCase()}</h3><button data-close>×</button></div><div class="request-form"><label><span>Giorno</span><input id="reqDate" type="date" value="${esc(presetDate)}"></label>${['FERIE','PERMESSO'].includes(real)?`<label><span>Fino al</span><input id="reqEnd" type="date" value="${esc(presetDate)}"></label>`:''}${real==='TURNO'?`<label><span>Turno richiesto</span><select id="reqShift">${SHIFTS.filter(x=>!['FERIE','PERMESSO','MALATTIA'].includes(x)).map(x=>`<option>${esc(x)}</option>`).join('')}</select></label>`:''}<label><span>Messaggio</span><textarea id="reqMsg" placeholder="Aggiungi dettagli…">${esc(presetMsg)}</textarea></label></div><div class="modal-actions"><button class="btn secondary" data-close>Annulla</button><button class="btn primary" id="sendRequest">Invia richiesta</button></div>`);b.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>b.remove());b.querySelector('#sendRequest').onclick=async()=>{const d=b.querySelector('#reqDate').value,end=b.querySelector('#reqEnd')?.value||d,shift=b.querySelector('#reqShift')?.value||null,msg=b.querySelector('#reqMsg').value.trim();if(!d&&real!=='ALTRO')return toast('Seleziona il giorno','error');try{await api('create_request',{method:'POST',body:{kind:real,requestDate:d||null,endDate:end||null,wantedShift:shift,message:msg}});b.remove();await loadRequests();toast('Richiesta inviata');render()}catch(e){toast(e.message,'error')}}}
function requestsAdmin(){const open=S.requests.filter(r=>r.status==='DA_VALUTARE'),closed=S.requests.filter(r=>r.status!=='DA_VALUTARE');return shell(`<section class="request-summary"><div><b>${open.length}</b><small>Da valutare</small></div><div><b>${closed.length}</b><small>Chiuse</small></div></section><section class="admin-request-list"><h3>Da valutare</h3>${open.length?open.map(r=>adminRequestCard(r,true)).join(''):'<div class="empty-mini">Nessuna richiesta aperta.</div>'}<h3 class="section-gap">Storico</h3>${closed.length?closed.slice(0,50).map(r=>adminRequestCard(r,false)).join(''):'<div class="empty-mini">Nessuna richiesta chiusa.</div>'}</section>`)}
function adminRequestCard(r,actions){return `<article class="request-card"><div class="request-card-top"><div><b>${esc(r.employee_name)}</b><small>${esc(r.kind)} · ${r.request_date?esc(fmt(r.request_date,{day:'numeric',month:'short'})):'senza data'}</small></div>${requestBadge(r.status)}</div>${r.wanted_shift?`<p>Turno richiesto: <b>${esc(r.wanted_shift)}</b></p>`:''}${r.message?`<p>${esc(r.message)}</p>`:''}${actions?`<div class="request-actions"><button class="btn primary small" data-resolve="${r.id}" data-status="ACCETTATA">Accetta</button><button class="btn danger small" data-resolve="${r.id}" data-status="RIFIUTATA">Rifiuta</button></div>`:`<button class="text-btn" data-resolve="${r.id}" data-status="DA_VALUTARE">Rimetti in valutazione</button>`}</article>`}
function requestsView(){return isAdmin()?requestsAdmin():requestsEmployee()}

function absencesView(){return shell(`<section class="form-card"><h3>Aggiungi assenza</h3><div class="form-grid"><label><span>Dipendente</span><select id="absPerson">${PEOPLE.map(n=>`<option>${esc(n)}</option>`).join('')}</select></label><label><span>Tipo</span><select id="absType"><option>FERIE</option><option>PERMESSO</option><option>MALATTIA</option></select></label><label><span>Dal</span><input id="absFrom" type="date"></label><label><span>Al</span><input id="absTo" type="date"></label></div><button class="btn primary" id="addAbs">Aggiungi</button></section><section class="list-card"><h3>Assenze inserite</h3>${S.absences.length?`<div class="absence-list">${S.absences.map(a=>`<div><span class="absence-icon">☂</span><div><b>${esc(a.employee_name)}</b><small>${esc(a.absence_type)} · ${esc(a.date_from)} → ${esc(a.date_to)}</small></div><button data-delabs="${a.id}">×</button></div>`).join('')}</div>`:'<div class="empty-mini">Nessuna assenza inserita.</div>'}</section>`)}

function hoursView(){const d=S.schedule?.data;if(!d?.weeks?.length)return shell('<div class="empty-state"><span>◷</span><h2>Nessun turno pubblicato</h2></div>');S.week=Math.max(0,Math.min(S.week,d.weeks.length-1));return shell(`${weekPicker(d)}<section class="hours-list">${PEOPLE.map(n=>{const h=weekHours(d.weeks[S.week],n),t=TARGET[n]||40,delta=h-t;return `<div><div><b>${esc(n)}</b><small>${esc(ROLE[n])}</small></div><div class="hour-meter"><span style="width:${Math.min(100,h/t*100)}%"></span></div><strong class="${delta>0?'over':delta<0?'under':''}">${h}h <small>/ ${t}h</small></strong></div>`}).join('')}</section>`)}

function announcementsView(){return shell(`${isAdmin()?`<section class="form-card"><h3>Nuovo avviso</h3><label><span>Messaggio</span><textarea id="annMsg" placeholder="Scrivi una comunicazione…"></textarea></label><div class="button-row"><button class="btn primary" id="sendAnn">Pubblica e notifica</button><button class="btn secondary" id="turnsNotice">Avvisa: nuovi turni</button></div></section>`:`<section class="notice-enable"><div><b>Notifiche push</b><small>Ricevi aggiornamenti quando vengono pubblicati o modificati i turni.</small></div><button class="btn secondary small" id="enablePush">${'Notification'in window&&Notification.permission==='granted'?'Attive':'Attiva'}</button></section>`}<section class="announcement-list">${S.announcements.length?S.announcements.map(a=>`<article><span>♢</span><div><small>${new Intl.DateTimeFormat('it-IT',{dateStyle:'medium',timeStyle:'short'}).format(new Date(a.created_at))}</small><p>${esc(a.message)}</p></div>${isAdmin()?`<button data-archive="${a.id}">×</button>`:''}</article>`).join(''):'<div class="empty-state small"><span>♢</span><h3>Nessun avviso</h3></div>'}</section>`)}

function moreView(){return shell(`<section class="more-list">${isAdmin()?`<button data-go="hours"><span>◷</span><div><b>Conteggio ore</b><small>Ore e target contrattuali</small></div><i>›</i></button><button data-go="absences"><span>☂</span><div><b>Ferie e assenze</b><small>Gestione assenze</small></div><i>›</i></button><button data-go="announcements"><span>♢</span><div><b>Avvisi e notifiche</b><small>Comunicazioni ai dipendenti</small></div><i>›</i></button>`:`<button data-go="announcements"><span>♢</span><div><b>Avvisi</b><small>Comunicazioni del negozio</small></div><i>›</i></button><button id="moreHours"><span>◷</span><div><b>Le mie ore</b><small>Riepilogo settimane pubblicate</small></div><i>›</i></button>`}<button id="logout" class="logout-row"><span>↪</span><div><b>Esci dall’account</b><small>Termina la sessione su questo dispositivo</small></div><i>›</i></button></section><section class="app-info"><img src="${LOGO}" alt="Eurospin"><div><b>Eurospin Torre Maura · Turni</b><small>Versione attuale · interfaccia unificata</small></div></section>`)}

async function enablePush(){try{if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window))throw new Error('Notifiche non supportate su questo dispositivo.');if(Notification.permission==='default'){const p=await Notification.requestPermission();if(p!=='granted')throw new Error('Permesso non concesso.')}if(Notification.permission!=='granted')throw new Error('Notifiche non autorizzate.');const reg=await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub){const k=await call(`${TOOLS}?action=vapid_public`);const raw=k.publicKey,p='='.repeat((4-raw.length%4)%4),x=(raw+p).replace(/-/g,'+').replace(/_/g,'/'),bin=atob(x),arr=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)arr[i]=bin.charCodeAt(i);sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:arr})}await tool('register_push',{subscription:sub.toJSON(),userAgent:navigator.userAgent});toast('Notifiche attivate');render()}catch(e){toast(e.message,'error')}}

async function manageWeeks(){const data=S.schedule?.data?.weeks||[];if(!data.length)return toast('Nessuna settimana pubblicata','error');const b=modal(`<div class="modal-head"><h3>Gestisci settimane</h3><button data-close>×</button></div><p class="modal-text">Elimina una singola settimana oppure tutte. Ferie, richieste e dipendenti non vengono toccati.</p><div class="manage-weeks">${data.map((w,i)=>`<div><div><b>Settimana ${i+1}</b><small>${esc(fmt(w.dates[0]))} – ${esc(fmt(w.dates[6]))}</small></div><button class="btn danger small" data-delete-week="${i}">Cancella</button></div>`).join('')}</div><button class="btn danger wide" id="deleteAll">Cancella tutte le settimane</button>`);b.querySelector('[data-close]').onclick=()=>b.remove();b.querySelectorAll('[data-delete-week]').forEach(x=>x.onclick=async()=>{const i=+x.dataset.deleteWeek,ok=await confirmBox('Cancellare settimana?',`Verrà rimossa la Settimana ${i+1}.`,'Cancella');if(!ok)return;try{await call(DELETE,{method:'POST',body:{mode:'one',weekIndex:i}});b.remove();S.schedule=null;await loadSchedule();toast('Settimana cancellata');render()}catch(e){toast(e.message,'error')}});b.querySelector('#deleteAll').onclick=async()=>{const ok=await confirmBox('Cancellare tutte le settimane?','Verranno rimossi soltanto i turni pubblicati.','Cancella tutto');if(!ok)return;try{await call(DELETE,{method:'POST',body:{mode:'all'}});b.remove();S.schedule=null;await loadSchedule();toast('Settimane cancellate');render()}catch(e){toast(e.message,'error')}}}

function editPublished(){const row=S.schedule;if(!row?.data?.weeks?.length)return;const d=JSON.parse(JSON.stringify(row.data)),b=modal(`<div class="modal-head"><h3>Modifica turni pubblicati</h3><button data-close>×</button></div><div id="pubEditor"></div><div class="modal-actions sticky"><button class="btn secondary" data-close>Chiudi</button><button class="btn primary" id="savePublished">Salva modifiche</button></div>`);let wi=0,di=0;const host=b.querySelector('#pubEditor');function draw(){const w=d.weeks[wi];host.innerHTML=`<div class="week-picker mini">${d.weeks.map((x,i)=>`<button data-ew="${i}" class="${i===wi?'active':''}"><b>Sett. ${i+1}</b><small>${esc(fmt(x.dates[0]))}</small></button>`).join('')}</div><div class="day-strip editor-days">${w.dates.map((x,i)=>`<button data-ed="${i}" class="${i===di?'active':''}"><small>${esc(fmt(x,{weekday:'short'}).replace('.',''))}</small><b>${date(x).getDate()}</b></button>`).join('')}</div><div class="modal-person-list">${PEOPLE.map(n=>`<button data-ep="${esc(n)}"><div><b>${esc(n)}</b><small>${esc(ROLE[n])}</small></div><span>${esc(w.schedule[n]?.[di]||'RIPOSO')}</span><i>›</i></button>`).join('')}</div>`;host.querySelectorAll('[data-ew]').forEach(x=>x.onclick=()=>{wi=+x.dataset.ew;di=0;draw()});host.querySelectorAll('[data-ed]').forEach(x=>x.onclick=()=>{di=+x.dataset.ed;draw()});host.querySelectorAll('[data-ep]').forEach(x=>x.onclick=()=>{const n=x.dataset.ep,cur=w.schedule[n][di],p=modal(`<div class="modal-head"><h3>${esc(n)}</h3><button data-close>×</button></div><label class="modal-field"><span>Turno</span><select id="pubShift">${[...new Set([cur,...SHIFTS])].map(s=>`<option ${s===cur?'selected':''}>${esc(s)}</option>`).join('')}</select></label><div class="modal-actions"><button class="btn secondary" data-close>Annulla</button><button class="btn primary" id="applyPub">Applica</button></div>`);p.querySelectorAll('[data-close]').forEach(z=>z.onclick=()=>p.remove());p.querySelector('#applyPub').onclick=()=>{w.schedule[n][di]=p.querySelector('#pubShift').value;p.remove();draw()}})}draw();b.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>b.remove());b.querySelector('#savePublished').onclick=async()=>{const ok=await confirmBox('Salvare le modifiche?','I dipendenti vedranno subito la turnazione aggiornata.','Salva');if(!ok)return;try{await tool('update_schedule',{scheduleId:row.id,data:d});b.remove();S.schedule=null;await loadSchedule();toast('Turni aggiornati');render()}catch(e){toast(e.message,'error')}}}

function myHoursModal(){const d=S.schedule?.data;if(!d?.weeks?.length)return toast('Nessun turno pubblicato','error');const n=S.user.employeeName;const b=modal(`<div class="modal-head"><h3>Le mie ore</h3><button data-close>×</button></div><div class="my-hours">${d.weeks.map((w,i)=>`<div><small>Settimana ${i+1}</small><b>${weekHours(w,n)}h</b><span>${esc(fmt(w.dates[0]))} – ${esc(fmt(w.dates[6]))}</span></div>`).join('')}</div>`);b.querySelector('[data-close]').onclick=()=>b.remove()}

function bindView(){bindShell();
  $$('[data-week]').forEach(x=>x.onclick=()=>{S.week=+x.dataset.week;S.day=0;render()});$$('[data-day]').forEach(x=>x.onclick=()=>{S.day=+x.dataset.day;render()});
  if(S.route==='home'&&!isAdmin()){$('#nextShiftBtn')?.addEventListener('click',()=>go('schedule'));$('#myHours')?.addEventListener('click',myHoursModal)}
  if(S.route==='schedule'&&!isAdmin()){const d=S.schedule?.data,w=d?.weeks?.[S.week],n=S.user.employeeName;$$('[data-detail]').forEach(x=>x.onclick=()=>shiftDetail(w,+x.dataset.detail,n))}
  if(S.route==='schedule'&&isAdmin()){$('#manageWeeks')?.addEventListener('click',manageWeeks);$('#editPublished')?.addEventListener('click',editPublished)}
  if(S.route==='create'){
    $('#chooseGenerate')?.addEventListener('click',()=>{S.createStep='generate';render()});$('#chooseManual')?.addEventListener('click',()=>{S.createStep='manualSetup';render()});$('#backCreate')?.addEventListener('click',()=>{S.createStep='choice';render()});$('#runGenerate')?.addEventListener('click',generateAutomatic);$('#startManual')?.addEventListener('click',()=>{const st=$('#manualStart').value,c=+$('#manualWeeks').value;if(!st)return;if(!isMonday(st))return toast('La data iniziale deve essere un lunedì','error');S.draft=makeBlank(st,c);S.week=0;S.day=0;S.createStep='editor';render()});$('#discardDraft')?.addEventListener('click',async()=>{if(await confirmBox('Annullare la bozza?','Le modifiche non pubblicate andranno perse.','Annulla bozza')){S.draft=null;S.createStep='choice';render()}});$$('[data-edit-person]').forEach(x=>x.onclick=()=>editDraftShift(x.dataset.editPerson));$('#publishDraft')?.addEventListener('click',publishDraft)
  }
  if(S.route==='requests'&&!isAdmin()){$$('[data-rtab]').forEach(x=>x.onclick=()=>{const mine=x.dataset.rtab==='mine';$$('[data-rtab]').forEach(z=>z.classList.toggle('active',z===x));$('#reqNew').hidden=mine;$('#reqMine').hidden=!mine});$$('[data-kind]').forEach(x=>x.onclick=()=>requestForm(x.dataset.kind));const pk=sessionStorage.getItem('tm_req_kind');if(pk){sessionStorage.removeItem('tm_req_kind');setTimeout(()=>requestForm(pk),0)}}
  if(S.route==='requests'&&isAdmin()){$$('[data-resolve]').forEach(x=>x.onclick=async()=>{const id=+x.dataset.resolve,status=x.dataset.status,ok=await confirmBox('Aggiornare richiesta?',status==='ACCETTATA'?'Accettare questa richiesta?':status==='RIFIUTATA'?'Rifiutare questa richiesta?':'Rimettere la richiesta in valutazione?','Conferma');if(!ok)return;try{await api('resolve_request',{method:'POST',body:{id,status,reply:status==='ACCETTATA'?'Richiesta accettata da Eurospin.':status==='RIFIUTATA'?'Richiesta rifiutata da Eurospin.':'Richiesta rimessa in valutazione.'}});await Promise.all([loadRequests(),loadAbsences().catch(()=>{})]);toast('Richiesta aggiornata');render()}catch(e){toast(e.message,'error')}})}
  if(S.route==='absences'){$('#addAbs')?.addEventListener('click',async()=>{const p=$('#absPerson').value,t=$('#absType').value,f=$('#absFrom').value,z=$('#absTo').value||f;if(!f||z<f)return toast('Controlla le date','error');try{await api('add_absence',{method:'POST',body:{employeeName:p,type:t,from:f,to:z}});await loadAbsences();toast('Assenza aggiunta');render()}catch(e){toast(e.message,'error')}});$$('[data-delabs]').forEach(x=>x.onclick=async()=>{if(!await confirmBox('Rimuovere assenza?','Questa assenza verrà eliminata.','Rimuovi'))return;try{await api('delete_absence',{method:'POST',body:{id:+x.dataset.delabs}});await loadAbsences();toast('Assenza rimossa');render()}catch(e){toast(e.message,'error')}})}
  if(S.route==='announcements'){if(isAdmin()){$('#sendAnn')?.addEventListener('click',async()=>{const m=$('#annMsg').value.trim();if(!m)return;try{await api('create_announcement',{method:'POST',body:{message:m}});await tool('notify_employees',{title:'Nuovo avviso',message:m,url:'/Portafoglio/turni-v2/#announcements'}).catch(()=>{});await loadAnnouncements();toast('Avviso pubblicato');render()}catch(e){toast(e.message,'error')}});$('#turnsNotice')?.addEventListener('click',async()=>{try{await tool('publish_turns_notice',{});await loadAnnouncements();toast('Notifica inviata');render()}catch(e){toast(e.message,'error')}});$$('[data-archive]').forEach(x=>x.onclick=async()=>{try{await api('archive_announcement',{method:'POST',body:{id:+x.dataset.archive}});await loadAnnouncements();render()}catch(e){toast(e.message,'error')}})}else $('#enablePush')?.addEventListener('click',enablePush)}
  if(S.route==='more'){$('#moreHours')?.addEventListener('click',myHoursModal);$('#logout')?.addEventListener('click',async()=>{try{await api('logout',{method:'POST'})}catch{}clearAuth();render()})}
}

function render(){const app=$('#app');if(!S.user){app.innerHTML=loginView();bindLogin();return}if(!isAdmin()&&!['home','schedule','requests','announcements','more'].includes(S.route))S.route='home';if(isAdmin()&&!['home','schedule','create','requests','announcements','absences','hours','more'].includes(S.route))S.route='home';let out='';if(S.route==='home')out=homeView();else if(S.route==='schedule')out=scheduleView();else if(S.route==='create')out=createView();else if(S.route==='requests')out=requestsView();else if(S.route==='announcements')out=announcementsView();else if(S.route==='absences')out=absencesView();else if(S.route==='hours')out=hoursView();else out=moreView();app.innerHTML=out;bindView()}

async function boot(){
  if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js?v=current-20260908',{scope:'./'}).catch(()=>{})}
  if(S.token){try{const d=await api('me');S.user=d.user;localStorage.setItem('tm2_user',JSON.stringify(S.user));await hydrate()}catch{clearAuth()}}
  render();
}
window.addEventListener('hashchange',()=>{if(!S.user)return;S.route=(location.hash||'#home').slice(1);render()});
boot();
})();
