(()=>{
'use strict';
const API='https://dlqrhteqodkdkvmrwktu.supabase.co/functions/v1/turni-v2-api';
const PEOPLE=['Umberto','Fabio','Emanuele','Stefania B','Stefania F','Romina','Giada','Giuliano','Manuel','Daniele','Paolo','Marco'];
const ROLE={Umberto:'Responsabile',Fabio:'Responsabile',Emanuele:'Responsabile','Stefania B':'Cassa','Stefania F':'Cassa',Romina:'Cassa',Giada:'Cassa',Giuliano:'Sala',Manuel:'Sala',Daniele:'Sala',Paolo:'Sala',Marco:'Sala / Jolly'};
const TARGET={Giada:30,Marco:16};
const QUICK=['06:30-13:30','07:00-14:00','07:00-15:00','09:00-17:00','10:00-17:00','10:00-18:00','11:00-19:00','11:00-20:00','11:30-20:30','12:00-20:30','12:30-20:30','13:30-20:30','14:30-20:30','16:00-20:00','16:30-20:30','07:00-13:00 / 17:00-20:00','07:00-13:00 / 17:00-20:30','08:00-13:00','RIPOSO','FERIE','PERMESSO','MALATTIA'];
const app=document.getElementById('app');
const S={token:localStorage.getItem('tm2_token')||'',user:null,route:'home',schedule:null,draft:null,week:0,graphDay:0,requests:[],absences:[],announcements:[],busy:false};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=d=>new Intl.DateTimeFormat('it-IT',{weekday:'short',day:'numeric',month:'short'}).format(new Date(d+'T12:00:00'));
const dt=x=>new Intl.DateTimeFormat('it-IT',{dateStyle:'short',timeStyle:'short'}).format(new Date(x));
const hm=t=>{const[a,b]=String(t).split(':').map(Number);return a*60+b};
const spans=s=>!s||['RIPOSO','FERIE','PERMESSO','MALATTIA','MATERNITÀ','—'].includes(String(s).trim())?[]:String(s).split('/').map(x=>x.trim()).map(x=>{const[a,b]=x.split('-').map(z=>z.trim());return[hm(a),hm(b)]}).filter(([a,b])=>b>a);
const shiftHours=s=>spans(s).reduce((z,[a,b])=>z+(b-a)/60,0);
const weekHours=(w,n)=>(w?.schedule?.[n]||[]).reduce((z,s)=>z+shiftHours(s),0);
const nextMonday=()=>{const d=new Date();d.setHours(12,0,0,0);let k=(8-d.getDay())%7;if(!k)k=7;d.setDate(d.getDate()+k);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
async function api(action,{method='GET',body}={}){const r=await fetch(`${API}?action=${encodeURIComponent(action)}`,{method,headers:{'Content-Type':'application/json',...(S.token?{Authorization:`Bearer ${S.token}`}:{})},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({error:'Risposta non valida'}));if(r.status===401&&action!=='login'){logout(false);throw new Error('Sessione scaduta')}if(!r.ok)throw new Error(d.error||'Errore di connessione');return d}
function saveAuth(d){S.token=d.token;S.user=d.user;localStorage.setItem('tm2_token',S.token);localStorage.setItem('tm2_user',JSON.stringify(S.user))}
function logout(renderNow=true){S.token='';S.user=null;localStorage.removeItem('tm2_token');localStorage.removeItem('tm2_user');if(renderNow)renderLogin()}
function isAdmin(){return S.user?.role==='admin'}
function setRoute(r){S.route=r;location.hash=r;render()}
function modeToggle(){const current=document.documentElement.dataset.mode||localStorage.getItem('tm2_mode')||'phone',next=current==='pc'?'phone':'pc';document.documentElement.dataset.mode=next;localStorage.setItem('tm2_mode',next);render()}
function applyMode(){const m=localStorage.getItem('tm2_mode')||((innerWidth>900)?'pc':'phone');document.documentElement.dataset.mode=m}
function navItems(){return isAdmin()?[['home','⌂','Home'],['schedule','📅','Turni'],['generate','✨','Genera'],['requests','📨','Richieste'],['hours','⏱️','Ore'],['announcements','📣','Avvisi']]:[['home','⌂','Home'],['schedule','📅','Turni'],['requests','📨','Richieste'],['announcements','📣','Avvisi']]}
function chrome(content){const nav=navItems();return `<div class="shell"><div class="top"><div class="brand"><div class="mini">E</div><div class="brandtext"><b>Eurospin Torre Maura</b><small>${esc(S.user.displayName)} · ${isAdmin()?'Amministratore':'Dipendente'}</small></div></div><div class="grow"></div><button class="iconbtn" id="modeBtn" type="button">${document.documentElement.dataset.mode==='pc'?'💻':'📱'}</button><button class="btn ghost" id="logoutBtn" type="button">Esci</button></div><div class="nav">${nav.map(([r,i,t])=>`<button type="button" data-route="${r}" class="${S.route===r?'active':''}">${i} ${t}</button>`).join('')}</div>${content}</div><div class="bottom">${nav.slice(0,5).map(([r,i,t])=>`<button type="button" data-route="${r}" class="${S.route===r?'active':''}">${i}<br>${t}</button>`).join('')}</div>`}
function bindChrome(){document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>setRoute(b.dataset.route));document.getElementById('logoutBtn')?.addEventListener('click',async()=>{try{await api('logout',{method:'POST'})}catch{}logout()});document.getElementById('modeBtn')?.addEventListener('click',modeToggle)}
function home(){const cards=isAdmin()?[['generate','✨','Nuovi Turni','Genera 3 settimane con ferie, richieste e riposi'],['schedule','📅','Turni pubblicati','Consulta e modifica le settimane pubblicate'],['requests','📨','Richieste dipendenti','Accetta o rifiuta turno, riposo, ferie e permessi'],['hours','⏱️','Conteggio ore','Controlla ore contrattuali e straordinari'],['announcements','📣','Avvisi','Pubblica comunicazioni ai dipendenti']]:[['schedule','📅','I miei turni','Consulta la turnazione pubblicata'],['requests','📨','Fai una richiesta','Turno, riposo, ferie, permesso o messaggio'],['announcements','📣','Avvisi','Comunicazioni del negozio']];return chrome(`<section class="hero"><h1>${isAdmin()?'Amministrazione turni':'Area dipendente'}</h1><p>Nuovo portale · un’unica app, senza ricaricare pagina.</p></section><div class="grid">${cards.map(([r,e,t,d])=>`<section class="card homecard" data-home="${r}"><div class="emoji">${e}</div><div><b>${t}</b><p>${d}</p></div></section>`).join('')}</div>`)}
async function ensureSchedule(){if(S.schedule!==null)return;try{S.schedule=(await api('get_schedule')).schedule}catch(e){S.schedule=false}}
function scheduleData(){return S.draft||S.schedule?.data||null}
function scheduleView(){const data=scheduleData();if(!data?.weeks?.length)return chrome(`<section class="hero"><h1>Turni</h1><p>Turnazione pubblicata</p></section><section class="card"><div class="notice">Non ci sono ancora turni pubblicati.</div></section>`);S.week=Math.max(0,Math.min(S.week,data.weeks.length-1));const w=data.weeks[S.week],names=isAdmin()?PEOPLE:[S.user.employeeName];return chrome(`<section class="hero"><h1>${S.draft?'Bozza turni':'Turni pubblicati'}</h1><p>${fmt(w.dates[0])} – ${fmt(w.dates[6])}</p></section><div class="tabs">${data.weeks.map((x,i)=>`<button type="button" data-week="${i}" class="${i===S.week?'active':''}">Settimana ${i+1} · ${fmt(x.dates[0])}</button>`).join('')}</div>${graph(w,names)}<section class="card"><h2>Turnazione</h2><div class="tablewrap"><table class="turntable"><thead><tr><th>Persona</th>${w.dates.map(d=>`<th>${esc(fmt(d))}</th>`).join('')}<th>Ore</th></tr></thead><tbody>${names.map(n=>`<tr><td><b>${esc(n)}</b><br><small>${esc(ROLE[n])}</small></td>${w.dates.map((d,i)=>{const s=w.schedule[n]?.[i]||'RIPOSO';return `<td>${isAdmin()&&S.draft?`<button class="shift ${spans(s).length?'':'off'}" data-edit="${esc(n)}" data-day="${i}">${esc(s)}</button>`:`<span class="shift ${spans(s).length?'':'off'}">${esc(s)}</span>`}</td>`}).join('')}<td class="hours">${weekHours(w,n)}h</td></tr>`).join('')}</tbody></table></div></section>${isAdmin()&&S.draft?`<div class="toolbar"><button class="btn blue" id="publishDraft">Pubblica queste 3 settimane</button><button class="btn ghost" id="discardDraft">Annulla bozza</button></div>`:''}`)}
function graph(w,names=PEOPLE){const start=390,end=1230,range=end-start,d=Math.min(S.graphDay,6),pct=v=>Math.max(0,Math.min(100,(v-start)/range*100));return `<section class="card"><h2>Grafico giornaliero</h2><div class="graphdays">${w.dates.map((x,i)=>`<button type="button" data-gday="${i}" class="${i===d?'active':''}">${esc(fmt(x))}</button>`).join('')}</div><div class="graphscroll"><div class="graph">${names.map(n=>{const s=w.schedule[n]?.[d]||'RIPOSO';return `<div class="growrow"><div class="gname"><b>${esc(n)}</b><small>${esc(s)}</small></div><div class="gtrack">${spans(s).map(([a,b])=>`<div class="gbar" style="left:${pct(a)}%;width:${Math.max(.5,pct(b)-pct(a))}%"><span>${Math.floor(a/60).toString().padStart(2,'0')}:${String(a%60).padStart(2,'0')}–${Math.floor(b/60).toString().padStart(2,'0')}:${String(b%60).padStart(2,'0')}</span></div>`).join('')}</div></div>`}).join('')}</div></div></section>`}
async function loadAbsences(){S.absences=(await api('absences')).absences||[]}
function generateView(){const start=S.draft?.startDate||nextMonday();return chrome(`<section class="hero"><h1>Genera 3 settimane</h1><p>Il calcolo viene eseguito sul server: PC e iPhone ricevono lo stesso risultato.</p></section><div class="grid"><section class="card"><h2>🏖️ Assenze programmate</h2><div class="formrow"><div class="field"><label>Dipendente</label><select id="absPerson">${PEOPLE.map(n=>`<option>${esc(n)}</option>`).join('')}</select></div><div class="field"><label>Tipo</label><select id="absType"><option>FERIE</option><option>MALATTIA</option><option>PERMESSO</option></select></div><div class="field"><label>Dal</label><input id="absFrom" type="date"></div><div class="field"><label>Al</label><input id="absTo" type="date"></div></div><button class="btn blue" id="addAbs" type="button">Aggiungi assenza</button><div class="list" style="margin-top:10px">${S.absences.length?S.absences.map(a=>`<div class="item"><b>${esc(a.employee_name)}</b> · ${esc(a.absence_type)}<br><small>${esc(a.date_from)} → ${esc(a.date_to)}</small> <button class="btn danger" data-delabs="${a.id}" style="float:right;padding:6px 9px">Rimuovi</button></div>`).join(''):'<div class="notice">Nessuna assenza inserita.</div>'}</div></section><section class="card"><h2>⚙️ Generazione</h2><div class="field"><label>Lunedì iniziale</label><input id="startDate" type="date" value="${esc(start)}"></div><p>Priorità: richieste accettate → copertura → minimo spezzati → minimo straordinario → distribuzione equa.</p><button class="btn primary" id="doGenerate" type="button" ${S.busy?'disabled':''}>${S.busy?'Sto calcolando…':'Genera 3 settimane'}</button><div id="genMsg"></div></section></div>${S.draft?draftSummary():''}`)}
function draftSummary(){const max=[];let splits=0;for(const w of S.draft.weeks){splits+=w.meta?.splitCount||0;for(const [n,h] of Object.entries(w.meta?.weekHours||{})){const ex=Math.max(0,Number(h)-(TARGET[n]||40));max.push({n,h:Number(h),ex})}}const maxEx=Math.max(0,...max.map(x=>x.ex));return `<section class="card" style="margin-top:12px"><h2>Bozza generata</h2><div class="summary"><div class="stat"><b>3</b><small>settimane</small></div><div class="stat"><b>${splits}</b><small>spezzati totali</small></div><div class="stat"><b>${maxEx}h</b><small>massimo extra individuale</small></div><div class="stat"><b>${esc(S.draft.generatedAt?dt(S.draft.generatedAt):'')}</b><small>generata</small></div></div><div style="margin-top:10px"><button class="btn blue" id="openDraft" type="button">Apri e controlla la bozza</button></div></section>`}
async function loadRequests(){S.requests=(await api('my_requests')).requests||[]}
function reqBadge(s){return s==='ACCETTATA'?'<span class="badge ok">Accettata</span>':s==='RIFIUTATA'?'<span class="badge no">Rifiutata</span>':'<span class="badge pending">Da valutare</span>'}
function requestsView(){if(isAdmin())return adminRequests();return employeeRequests()}
function employeeRequests(){return chrome(`<section class="hero"><h1>Richieste</h1><p>Invia una richiesta a Eurospin.</p></section><div class="grid"><section class="card"><h2>Nuova richiesta</h2><div class="form"><div class="field"><label>Tipo</label><select id="reqKind"><option value="TURNO">Cambio turno</option><option value="RIPOSO">Giorno di riposo</option><option value="FERIE">Ferie</option><option value="PERMESSO">Permesso</option><option value="ALTRO">Altro</option></select></div><div class="formrow"><div class="field"><label>Giorno</label><input id="reqDate" type="date"></div><div class="field"><label>Fino al</label><input id="reqEnd" type="date"></div><div class="field" id="wantedWrap"><label>Turno richiesto</label><select id="reqShift">${QUICK.filter(x=>!['FERIE','PERMESSO','MALATTIA'].includes(x)).map(x=>`<option>${esc(x)}</option>`).join('')}</select></div></div><div class="field"><label>Messaggio</label><textarea id="reqMsg" placeholder="Scrivi eventuali dettagli…"></textarea></div><button class="btn blue" id="sendReq" type="button">Invia richiesta</button></div></section><section class="card"><h2>Le mie richieste</h2><div class="list">${S.requests.length?S.requests.map(r=>`<div class="item"><div class="meta">${dt(r.created_at)}</div><b>${esc(r.kind)}</b> ${reqBadge(r.status)}<br><small>${esc(r.request_date||'')} ${r.end_date&&r.end_date!==r.request_date?'→ '+esc(r.end_date):''}</small>${r.wanted_shift?`<p>Turno: <b>${esc(r.wanted_shift)}</b></p>`:''}${r.message?`<p>${esc(r.message)}</p>`:''}${r.reply?`<div class="notice">Risposta: ${esc(r.reply)}</div>`:''}</div>`).join(''):'<div class="notice">Nessuna richiesta.</div>'}</div></section></div>`)}
function adminRequests(){const open=S.requests.filter(r=>r.status==='DA_VALUTARE'),closed=S.requests.filter(r=>r.status!=='DA_VALUTARE');return chrome(`<section class="hero"><h1>Richieste dipendenti</h1><p>Le richieste accettate vengono considerate automaticamente dal generatore.</p></section><div class="grid"><section class="card"><h2>Aperte · ${open.length}</h2><div class="list">${open.length?open.map(r=>requestAdminCard(r,true)).join(''):'<div class="notice">Nessuna richiesta aperta.</div>'}</div></section><section class="card"><h2>Chiuse · ${closed.length}</h2><div class="list">${closed.slice(0,30).map(r=>requestAdminCard(r,false)).join('')||'<div class="notice">Nessuna richiesta chiusa.</div>'}</div></section></div>`)}
function requestAdminCard(r,actions){return `<div class="item"><div class="meta">${dt(r.created_at)} · ${esc(r.employee_name)}</div><b>${esc(r.kind)}</b> ${reqBadge(r.status)}<br><small>${esc(r.request_date||'')} ${r.end_date&&r.end_date!==r.request_date?'→ '+esc(r.end_date):''}</small>${r.wanted_shift?`<p>Turno richiesto: <b>${esc(r.wanted_shift)}</b></p>`:''}${r.message?`<p>${esc(r.message)}</p>`:''}${actions?`<div class="toolbar"><button class="btn blue" data-resolve="${r.id}" data-status="ACCETTATA">Accetta</button><button class="btn ghost" data-resolve="${r.id}" data-status="RIFIUTATA">Rifiuta</button></div>`:''}</div>`}
function hoursView(){const data=S.schedule?.data;if(!data?.weeks?.length)return chrome(`<section class="hero"><h1>Conteggio ore</h1></section><section class="card"><div class="notice">Nessun turno pubblicato.</div></section>`);return chrome(`<section class="hero"><h1>Conteggio ore</h1><p>Ore settimanali e straordinari della turnazione pubblicata.</p></section>${data.weeks.map((w,i)=>`<section class="card" style="margin-bottom:10px"><h2>Settimana ${i+1} · ${fmt(w.dates[0])}</h2><div class="summary">${PEOPLE.map(n=>{const h=weekHours(w,n),t=TARGET[n]||40,e=Math.max(0,h-t);return `<div class="stat"><small>${esc(n)}</small><b>${h}h</b><small>${e?`+${e}h straordinario`:`target ${t}h`}</small></div>`}).join('')}</div></section>`).join('')}`)}
async function loadAnnouncements(){S.announcements=(await api('announcements')).announcements||[]}
function announcementsView(){return chrome(`<section class="hero"><h1>Avvisi</h1><p>Comunicazioni del negozio.</p></section>${isAdmin()?`<section class="card"><h2>Nuovo avviso</h2><div class="field"><textarea id="annMsg" placeholder="Scrivi un avviso…"></textarea></div><button class="btn blue" id="sendAnn">Pubblica</button></section>`:''}<section class="card" style="margin-top:10px"><h2>Avvisi attivi</h2><div class="list">${S.announcements.length?S.announcements.map(a=>`<div class="item"><div class="meta">${dt(a.created_at)}</div><p>${esc(a.message)}</p>${isAdmin()?`<button class="btn ghost" data-archive="${a.id}">Archivia</button>`:''}</div>`).join(''):'<div class="notice">Nessun avviso.</div>'}</div></section>`)}
function editModal(n,d){const w=S.draft?.weeks?.[S.week];if(!w)return;const cur=w.schedule[n][d]||'RIPOSO';document.body.insertAdjacentHTML('beforeend',`<div class="modalback" id="editBack"><div class="modal"><h3>${esc(n)} · ${esc(fmt(w.dates[d]))}</h3><div class="field"><label>Turno</label><select id="editShift">${[...new Set([cur,...QUICK])].map(s=>`<option ${s===cur?'selected':''}>${esc(s)}</option>`).join('')}</select></div><div class="toolbar"><button class="btn ghost" id="editCancel">Annulla</button><button class="btn primary" id="editSave">Salva</button></div></div></div>`);document.getElementById('editCancel').onclick=()=>document.getElementById('editBack').remove();document.getElementById('editSave').onclick=()=>{w.schedule[n][d]=document.getElementById('editShift').value;document.getElementById('editBack').remove();render()}}
function renderLogin(){app.innerHTML=`<div class="login"><div class="loginbox"><section class="hero"><div class="logo" style="margin:0 auto 12px">E</div><h1>Eurospin Torre Maura</h1><p>Nuovo portale turni</p></section><section class="card"><div class="form"><div class="field"><label>Account</label><input class="biginput" id="loginUser" autocomplete="username" placeholder="Eurospin"></div><div class="field"><label>Password</label><input class="biginput" id="loginPass" type="password" inputmode="numeric" autocomplete="current-password"></div><button class="btn blue" id="loginBtn">Accedi</button><div id="loginMsg"></div></div></section></div></div>`;document.getElementById('loginBtn').onclick=login;document.getElementById('loginPass').onkeydown=e=>{if(e.key==='Enter')login()}}
async function login(){const b=document.getElementById('loginBtn'),m=document.getElementById('loginMsg');b.disabled=true;b.textContent='Accesso…';try{const d=await api('login',{method:'POST',body:{username:document.getElementById('loginUser').value.trim(),password:document.getElementById('loginPass').value}});saveAuth(d);S.route='home';location.hash='home';await hydrate();render()}catch(e){m.innerHTML=`<div class="notice error">${esc(e.message)}</div>`}finally{b.disabled=false;b.textContent='Accedi'}}
async function hydrate(){await Promise.all([ensureSchedule(),loadRequests().catch(()=>{}),loadAnnouncements().catch(()=>{}),isAdmin()?loadAbsences().catch(()=>{}):Promise.resolve()])}
function render(){if(!S.user){renderLogin();return}let out='';if(S.route==='schedule')out=scheduleView();else if(S.route==='generate'&&isAdmin())out=generateView();else if(S.route==='requests')out=requestsView();else if(S.route==='hours'&&isAdmin())out=hoursView();else if(S.route==='announcements')out=announcementsView();else out=home();app.innerHTML=out;bindChrome();bindView()}
function bindView(){document.querySelectorAll('[data-home]').forEach(x=>x.onclick=()=>setRoute(x.dataset.home));document.querySelectorAll('[data-week]').forEach(x=>x.onclick=()=>{S.week=+x.dataset.week;S.graphDay=0;render()});document.querySelectorAll('[data-gday]').forEach(x=>x.onclick=()=>{S.graphDay=+x.dataset.gday;render()});document.querySelectorAll('[data-edit]').forEach(x=>x.onclick=()=>editModal(x.dataset.edit,+x.dataset.day));document.getElementById('openDraft')?.addEventListener('click',()=>{S.route='schedule';S.week=0;S.graphDay=0;render()});document.getElementById('discardDraft')?.addEventListener('click',()=>{if(confirm('Eliminare la bozza?')){S.draft=null;setRoute('generate')}});document.getElementById('publishDraft')?.addEventListener('click',publishDraft);document.getElementById('addAbs')?.addEventListener('click',addAbs);document.querySelectorAll('[data-delabs]').forEach(x=>x.onclick=()=>delAbs(+x.dataset.delabs));document.getElementById('doGenerate')?.addEventListener('click',doGenerate);document.getElementById('sendReq')?.addEventListener('click',sendRequest);document.querySelectorAll('[data-resolve]').forEach(x=>x.onclick=()=>resolveRequest(+x.dataset.resolve,x.dataset.status));document.getElementById('sendAnn')?.addEventListener('click',sendAnnouncement);document.querySelectorAll('[data-archive]').forEach(x=>x.onclick=()=>archiveAnnouncement(+x.dataset.archive))}
async function addAbs(){const p=document.getElementById('absPerson').value,t=document.getElementById('absType').value,f=document.getElementById('absFrom').value,z=document.getElementById('absTo').value||f;if(!f||!z||z<f)return alert('Controlla le date');await api('add_absence',{method:'POST',body:{employeeName:p,type:t,from:f,to:z}});await loadAbsences();S.draft=null;render()}
async function delAbs(id){if(!confirm('Rimuovere questa assenza?'))return;await api('delete_absence',{method:'POST',body:{id}});await loadAbsences();S.draft=null;render()}
async function doGenerate(){if(S.busy)return;const start=document.getElementById('startDate').value;if(!start)return;S.busy=true;render();try{const d=await api('generate',{method:'POST',body:{startDate:start}});S.draft=d.schedule;S.week=0;S.graphDay=0;S.route='schedule';render()}catch(e){S.route='generate';render();setTimeout(()=>{const m=document.getElementById('genMsg');if(m)m.innerHTML=`<div class="notice error">${esc(e.message)}</div>`},0)}finally{S.busy=false}}
async function publishDraft(){if(!S.draft)return;if(!confirm('Pubblicare queste 3 settimane?'))return;await api('publish',{method:'POST',body:{schedule:S.draft}});S.draft=null;S.schedule=null;await ensureSchedule();alert('Turni pubblicati.');render()}
async function sendRequest(){const kind=document.getElementById('reqKind').value,date=document.getElementById('reqDate').value,end=document.getElementById('reqEnd').value||date,shift=kind==='TURNO'?document.getElementById('reqShift').value:null,msg=document.getElementById('reqMsg').value.trim();if(kind!=='ALTRO'&&!date)return alert('Seleziona il giorno');await api('create_request',{method:'POST',body:{kind,requestDate:date||null,endDate:end||null,wantedShift:shift,message:msg}});await loadRequests();render()}
async function resolveRequest(id,status){if(!confirm(status==='ACCETTATA'?'Accettare questa richiesta?':'Rifiutare questa richiesta?'))return;await api('resolve_request',{method:'POST',body:{id,status,reply:status==='ACCETTATA'?'Richiesta accettata da Eurospin.':'Richiesta rifiutata da Eurospin.'}});await Promise.all([loadRequests(),loadAbsences()]);render()}
async function sendAnnouncement(){const m=document.getElementById('annMsg').value.trim();if(!m)return;await api('create_announcement',{method:'POST',body:{message:m}});await loadAnnouncements();render()}
async function archiveAnnouncement(id){await api('archive_announcement',{method:'POST',body:{id}});await loadAnnouncements();render()}
async function boot(){applyMode();S.route=(location.hash||'#home').slice(1);if(S.token){try{const d=await api('me');S.user=d.user;await hydrate();render();return}catch{}}renderLogin()}
window.addEventListener('hashchange',()=>{if(!S.user)return;S.route=(location.hash||'#home').slice(1);render()});boot();
})();