(()=>{
'use strict';
const API='https://dlqrhteqodkdkvmrwktu.supabase.co/functions/v1/turni-v2-api-v3';
const LOGO='https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Eurospin_New_Logo.svg/512px-Eurospin_New_Logo.svg.png';
const PEOPLE=['Umberto','Fabio','Emanuele','Stefania B','Stefania F','Romina','Giada','Giuliano','Manuel','Daniele','Paolo','Marco'];
const ROLE={Umberto:'Responsabile',Fabio:'Responsabile',Emanuele:'Responsabile','Stefania B':'Cassa','Stefania F':'Cassa',Romina:'Cassa',Giada:'Cassa',Giuliano:'Sala',Manuel:'Sala',Daniele:'Sala',Paolo:'Sala',Marco:'Sala / Jolly'};
const TARGET={Giada:30,Marco:16};
const QUICK=['06:30-13:30','07:00-14:00','07:00-15:00','09:00-17:00','10:00-17:00','10:00-18:00','11:00-19:00','11:00-20:00','11:30-20:30','12:00-20:30','12:30-20:30','13:30-20:30','14:30-20:30','16:00-20:00','16:30-20:30','07:00-13:00 / 17:00-20:00','07:00-13:00 / 17:00-20:30','08:00-13:00','RIPOSO','FERIE','PERMESSO','MALATTIA'];
const app=document.getElementById('app');
const S={token:localStorage.getItem('tm2_token')||'',user:null,route:'home',schedule:null,draft:null,week:0,graphDay:0,requests:[],absences:[],announcements:[],busy:false};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=d=>new Intl.DateTimeFormat('it-IT',{weekday:'short',day:'numeric',month:'short'}).format(new Date(d+'T12:00:00'));
const dt=x=>new Intl.DateTimeFormat('it-IT',{dateStyle:'short',timeStyle:'short'}).format(new Date(x));
const hm=t=>{const[a,b]=String(t).split(':').map(Number);return a*60+b};
const spans=s=>!s||['RIPOSO','FERIE','PERMESSO','MALATTIA','MATERNITÀ','—'].includes(String(s).trim())?[]:String(s).split('/').map(x=>x.trim()).map(x=>{const[a,b]=x.split('-').map(z=>z.trim());return[hm(a),hm(b)]}).filter(([a,b])=>b>a);
const shiftHours=s=>spans(s).reduce((z,[a,b])=>z+(b-a)/60,0);
const weekHours=(w,n)=>(w?.schedule?.[n]||[]).reduce((z,s)=>z+shiftHours(s),0);
const nextMonday=()=>{const d=new Date();d.setHours(12,0,0,0);let k=(8-d.getDay())%7;if(!k)k=7;d.setDate(d.getDate()+k);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
async function api(action,{method='GET',body}={}){const r=await fetch(`${API}?action=${encodeURIComponent(action)}`,{method,headers:{'Content-Type':'application/json',...(S.token?{Authorization:`Bearer ${S.token}`}:{})},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({error:'Risposta non valida'}));if(r.status===401&&action!=='login'){logout(false);throw new Error('Sessione scaduta')}if(!r.ok)throw new Error(d.error||'Errore di connessione');return d}
function saveAuth(d){S.token=d.token;S.user=d.user;localStorage.setItem('tm2_token',S.token);localStorage.setItem('tm2_user',JSON.stringify(S.user))}
function logout(renderNow=true){S.token='';S.user=null;localStorage.removeItem('tm2_token');localStorage.removeItem('tm2_user');if(renderNow)renderLogin()}
const isAdmin=()=>S.user?.role==='admin';
function setRoute(r){S.route=r;location.hash=r;render()}
function modeToggle(){const current=document.documentElement.dataset.mode||localStorage.getItem('tm2_mode')||'phone',next=current==='pc'?'phone':'pc';document.documentElement.dataset.mode=next;localStorage.setItem('tm2_mode',next);render()}
function applyMode(){const m=localStorage.getItem('tm2_mode')||((innerWidth>900)?'pc':'phone');document.documentElement.dataset.mode=m}
function navItems(){return isAdmin()?[['home','⌂','Home'],['schedule','▦','Turni'],['generate','✦','Nuovi turni'],['requests','✉','Richieste'],['hours','◷','Ore'],['announcements','●','Avvisi']]:[['home','⌂','Home'],['schedule','▦','Turni'],['requests','✉','Richieste'],['announcements','●','Avvisi']]}
function chrome(content){const nav=navItems();return `<div class="appbg"></div><div class="shell"><header class="top"><div class="brand"><img src="${LOGO}" class="brandlogo" alt="Eurospin"><div class="brandtext"><b>Eurospin Torre Maura</b><small>${esc(S.user.displayName)} · ${isAdmin()?'Amministratore':'Dipendente'}</small></div></div><div class="grow"></div><button class="iconbtn" id="modeBtn" type="button" aria-label="Cambia vista">${document.documentElement.dataset.mode==='pc'?'Desktop':'Mobile'}</button><button class="btn ghost compact" id="logoutBtn" type="button">Esci</button></header><nav class="nav">${nav.map(([r,i,t])=>`<button type="button" data-route="${r}" class="${S.route===r?'active':''}"><span>${i}</span>${t}</button>`).join('')}</nav>${content}</div><nav class="bottom">${nav.slice(0,5).map(([r,i,t])=>`<button type="button" data-route="${r}" class="${S.route===r?'active':''}"><span>${i}</span><small>${t}</small></button>`).join('')}</nav>`}
function bindChrome(){document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>setRoute(b.dataset.route));document.getElementById('logoutBtn')?.addEventListener('click',async()=>{try{await api('logout',{method:'POST'})}catch{}logout()});document.getElementById('modeBtn')?.addEventListener('click',modeToggle)}
function pendingCount(){return S.requests.filter(r=>r.status==='DA_VALUTARE').length}
function home(){const p=pendingCount(),cards=isAdmin()?[['generate','✦','Nuovi turni','Genera e controlla tre settimane','Generazione'],['schedule','▦','Turni pubblicati','Consulta la turnazione ufficiale','Turnazione'],['requests','✉','Richieste dipendenti',p?`${p} richieste da valutare`:'Tutto gestito','Richieste'],['hours','◷','Conteggio ore','Ore, extra e distribuzione','Controllo'],['announcements','●','Avvisi','Comunicazioni al team','Comunicazioni']]:[['schedule','▦','I miei turni','La tua turnazione pubblicata','Turnazione'],['requests','✉','Fai una richiesta','Cambio turno, riposo, ferie o permesso','Richieste'],['announcements','●','Avvisi','Comunicazioni del negozio','Comunicazioni']];return chrome(`<section class="hero premiumhero"><div><span class="eyebrow">${isAdmin()?'AREA AMMINISTRATORE':'AREA DIPENDENTE'}</span><h1>${isAdmin()?'Gestione turni':'Ciao, '+esc(S.user.displayName)}</h1><p>Eurospin Torre Maura · organizzazione semplice, chiara e sempre aggiornata.</p></div><img src="${LOGO}" class="herologo" alt=""></section>${isAdmin()?`<section class="quickstats"><div><span>Richieste aperte</span><b>${p}</b></div><div><span>Turno centrale Resp.</span><b>10–17</b></div><div><span>Motore pesante</span><b>Render</b></div></section>`:''}<div class="grid homegrid">${cards.map(([r,e,t,d,k])=>`<section class="card homecard" data-home="${r}"><div class="cardicon">${e}</div><div class="cardcopy"><span class="kicker">${k}</span><b>${t}</b><p>${d}</p></div><span class="arrow">›</span></section>`).join('')}</div>`)}
async function ensureSchedule(force=false){if(S.schedule!==null&&!force)return;try{S.schedule=(await api('get_schedule')).schedule}catch{S.schedule=false}}
function scheduleData(){return S.draft||S.schedule?.data||null}
function scheduleTable(w,names,editable=false){return `<div class="tablewrap"><table class="turntable"><thead><tr><th>Persona</th>${w.dates.map(d=>`<th>${esc(fmt(d))}</th>`).join('')}<th>Ore</th></tr></thead><tbody>${names.map(n=>`<tr><td><b>${esc(n)}</b><small>${esc(ROLE[n])}</small></td>${w.dates.map((d,i)=>{const s=w.schedule?.[n]?.[i]||'RIPOSO';return `<td>${editable?`<button class="shift ${spans(s).length?'':'off'}" data-edit="${esc(n)}" data-day="${i}">${esc(s)}</button>`:`<span class="shift ${spans(s).length?'':'off'}">${esc(s)}</span>`}</td>`}).join('')}<td class="hours">${weekHours(w,n)}h</td></tr>`).join('')}</tbody></table></div>`}
function scheduleView(){const data=scheduleData();if(!data?.weeks?.length)return chrome(`<section class="hero"><span class="eyebrow">TURNI</span><h1>Turnazione</h1><p>Non ci sono ancora turni pubblicati.</p></section><section class="card"><div class="empty">Nessuna turnazione disponibile.</div></section>`);S.week=Math.max(0,Math.min(S.week,data.weeks.length-1));const w=data.weeks[S.week],names=isAdmin()?PEOPLE:[S.user.employeeName];return chrome(`<section class="hero"><span class="eyebrow">${S.draft?'BOZZA':'PUBBLICATA'}</span><h1>${S.draft?'Controlla la bozza':'Turni'}</h1><p>${fmt(w.dates[0])} – ${fmt(w.dates[6])}</p></section><div class="tabs">${data.weeks.map((x,i)=>`<button type="button" data-week="${i}" class="${i===S.week?'active':''}">Settimana ${i+1}<small>${fmt(x.dates[0])}</small></button>`).join('')}</div>${graph(w,names)}<section class="card"><div class="sectionhead"><div><span class="kicker">SETTIMANA ${S.week+1}</span><h2>Turnazione</h2></div>${data.engine?`<span class="engine">${esc(data.engine)}</span>`:''}</div>${scheduleTable(w,names,isAdmin()&&!!S.draft)}</section>${isAdmin()&&S.draft?`<div class="stickyactions"><button class="btn ghost" id="discardDraft">Annulla bozza</button><button class="btn primary" id="publishDraft">Pubblica 3 settimane</button></div>`:''}`)}
function graph(w,names=PEOPLE){const start=390,end=1230,range=end-start,d=Math.min(S.graphDay,6),pct=v=>Math.max(0,Math.min(100,(v-start)/range*100));return `<section class="card graphcard"><div class="sectionhead"><div><span class="kicker">COPERTURA</span><h2>Grafico giornaliero</h2></div></div><div class="graphdays">${w.dates.map((x,i)=>`<button type="button" data-gday="${i}" class="${i===d?'active':''}">${esc(fmt(x))}</button>`).join('')}</div><div class="graphscroll"><div class="graph">${names.map(n=>{const s=w.schedule?.[n]?.[d]||'RIPOSO';return `<div class="growrow"><div class="gname"><b>${esc(n)}</b><small>${esc(s)}</small></div><div class="gtrack">${spans(s).map(([a,b])=>`<div class="gbar" style="left:${pct(a)}%;width:${Math.max(.5,pct(b)-pct(a))}%"><span>${Math.floor(a/60).toString().padStart(2,'0')}:${String(a%60).padStart(2,'0')}–${Math.floor(b/60).toString().padStart(2,'0')}:${String(b%60).padStart(2,'0')}</span></div>`).join('')}</div></div>`}).join('')}</div></div></section>`}
async function loadAbsences(){S.absences=(await api('absences')).absences||[]}
function pendingRequestCards(){const open=S.requests.filter(r=>r.status==='DA_VALUTARE');return `<section class="card requestpanel"><div class="sectionhead"><div><span class="kicker">DA VALUTARE</span><h2>Richieste · ${open.length}</h2></div><button class="btn ghost compact" data-route="requests">Apri tutte</button></div>${open.length?`<div class="list">${open.map(r=>requestAdminCard(r,true,true)).join('')}</div>`:'<div class="empty">Nessuna richiesta aperta.</div>'}</section>`}
function generateView(){const start=S.draft?.startDate||nextMonday();return chrome(`<section class="hero"><span class="eyebrow">NUOVI TURNI</span><h1>Genera 3 settimane</h1><p>Turni normali con motore stabile; con 2 assenti il calcolo pesante viene spostato su Render.</p></section>${pendingRequestCards()}<div class="grid generategrid"><section class="card"><div class="sectionhead"><div><span class="kicker">ASSENZE</span><h2>Ferie e permessi</h2></div></div><div class="formrow"><div class="field"><label>Dipendente</label><select id="absPerson">${PEOPLE.map(n=>`<option>${esc(n)}</option>`).join('')}</select></div><div class="field"><label>Tipo</label><select id="absType"><option>FERIE</option><option>MALATTIA</option><option>PERMESSO</option></select></div><div class="field"><label>Dal</label><input id="absFrom" type="date"></div><div class="field"><label>Al</label><input id="absTo" type="date"></div></div><button class="btn blue" id="addAbs" type="button">Aggiungi assenza</button><div class="list compactlist">${S.absences.length?S.absences.map(a=>`<div class="item inlineitem"><div><b>${esc(a.employee_name)}</b><small>${esc(a.absence_type)} · ${esc(a.date_from)} → ${esc(a.date_to)}</small></div><button class="btn danger compact" data-delabs="${a.id}">Rimuovi</button></div>`).join(''):'<div class="empty">Nessuna assenza inserita.</div>'}</div></section><section class="card generator"><span class="kicker">GENERATORE</span><h2>Calcolo turni</h2><div class="field"><label>Lunedì iniziale</label><input id="startDate" type="date" value="${esc(start)}"></div><div class="rulechips"><span>Resp. centrale 10–17</span><span>Equità</span><span>Extra minimo</span><span>Max 2 spezzati con 2 assenti</span></div><p>Con 2 persone assenti: chi lavora domenica riposa una sola volta lun–sab; chi riposa domenica lavora tutti i 6 giorni. Straordinario massimo +3h, obiettivo 0.</p><button class="btn primary big" id="doGenerate" type="button" ${S.busy?'disabled':''}>${S.busy?'Calcolo in corso…':'Genera 3 settimane'}</button><div id="genMsg"></div></section></div>${S.draft?draftSummary():''}`)}
function draftSummary(){let splits=0,maxEx=0;for(const w of S.draft.weeks||[]){splits+=w.meta?.splitCount||0;for(const n of [...CASH_NAMES(),...FLOOR_NAMES()]){const h=Number(w.meta?.weekHours?.[n]??weekHours(w,n)),e=Math.max(0,h-(TARGET[n]||40));maxEx=Math.max(maxEx,e)}}return `<section class="card resultcard"><span class="kicker">RISULTATO</span><h2>Bozza pronta</h2><div class="summary"><div class="stat"><b>3</b><small>settimane</small></div><div class="stat"><b>${splits}</b><small>spezzati</small></div><div class="stat"><b>${maxEx}h</b><small>extra massimo</small></div><div class="stat"><b>10–17</b><small>centrale Resp.</small></div></div><button class="btn blue" id="openDraft">Apri e controlla</button></section>`}
const CASH_NAMES=()=>['Stefania B','Stefania F','Romina','Giada'];
const FLOOR_NAMES=()=>['Giuliano','Manuel','Daniele','Paolo','Marco'];
async function loadRequests(){S.requests=(await api('my_requests')).requests||[]}
function reqBadge(s){return s==='ACCETTATA'?'<span class="badge ok">Accettata</span>':s==='RIFIUTATA'?'<span class="badge no">Rifiutata</span>':'<span class="badge pending">Da valutare</span>'}
function requestsView(){return isAdmin()?adminRequests():employeeRequests()}
function employeeRequests(){return chrome(`<section class="hero"><span class="eyebrow">RICHIESTE</span><h1>Parla con il responsabile</h1><p>Richiedi un cambio turno, un riposo, ferie o permesso.</p></section><div class="grid"><section class="card"><span class="kicker">NUOVA</span><h2>Invia richiesta</h2><div class="form"><div class="field"><label>Tipo</label><select id="reqKind"><option value="TURNO">Cambio turno</option><option value="RIPOSO">Giorno di riposo</option><option value="FERIE">Ferie</option><option value="PERMESSO">Permesso</option><option value="ALTRO">Altro</option></select></div><div class="formrow three"><div class="field"><label>Giorno</label><input id="reqDate" type="date"></div><div class="field"><label>Fino al</label><input id="reqEnd" type="date"></div><div class="field" id="wantedWrap"><label>Turno richiesto</label><select id="reqShift">${QUICK.filter(x=>!['FERIE','PERMESSO','MALATTIA'].includes(x)).map(x=>`<option>${esc(x)}</option>`).join('')}</select></div></div><div class="field"><label>Messaggio</label><textarea id="reqMsg" placeholder="Scrivi eventuali dettagli…"></textarea></div><button class="btn primary" id="sendReq">Invia richiesta</button></div></section><section class="card"><span class="kicker">STORICO</span><h2>Le mie richieste</h2><div class="list">${S.requests.length?S.requests.map(r=>`<div class="item"><div class="meta">${dt(r.created_at)}</div><div class="requesttitle"><b>${esc(r.kind)}</b>${reqBadge(r.status)}</div><small>${esc(r.request_date||'')} ${r.end_date&&r.end_date!==r.request_date?'→ '+esc(r.end_date):''}</small>${r.wanted_shift?`<p>Turno: <b>${esc(r.wanted_shift)}</b></p>`:''}${r.message?`<p>${esc(r.message)}</p>`:''}${r.reply?`<div class="notice">${esc(r.reply)}</div>`:''}</div>`).join(''):'<div class="empty">Nessuna richiesta.</div>'}</div></section></div>`)}
function adminRequests(){const open=S.requests.filter(r=>r.status==='DA_VALUTARE'),closed=S.requests.filter(r=>r.status!=='DA_VALUTARE');return chrome(`<section class="hero"><span class="eyebrow">RICHIESTE</span><h1>Richieste dipendenti</h1><p>Visualizza la turnazione prima di decidere e applica subito gli scambi quando è possibile.</p></section><div class="grid"><section class="card"><div class="sectionhead"><div><span class="kicker">APERTE</span><h2>Da valutare · ${open.length}</h2></div></div><div class="list">${open.length?open.map(r=>requestAdminCard(r,true,false)).join(''):'<div class="empty">Nessuna richiesta aperta.</div>'}</div></section><section class="card"><span class="kicker">CHIUSE</span><h2>Storico</h2><div class="list">${closed.slice(0,40).map(r=>requestAdminCard(r,false,false)).join('')||'<div class="empty">Nessuna richiesta chiusa.</div>'}</div></section></div>`)}
function requestAdminCard(r,actions,mini){return `<div class="item requestitem"><div class="meta">${dt(r.created_at)} · ${esc(r.employee_name)}</div><div class="requesttitle"><b>${esc(r.kind)}</b>${reqBadge(r.status)}</div><small>${esc(r.request_date||'')} ${r.end_date&&r.end_date!==r.request_date?'→ '+esc(r.end_date):''}</small>${r.wanted_shift?`<p>Turno richiesto: <b>${esc(r.wanted_shift)}</b></p>`:''}${!mini&&r.message?`<p>${esc(r.message)}</p>`:''}${actions?`<div class="toolbar requestactions"><button class="btn preview" data-preview="${r.id}">Vedi turnazione</button><button class="btn blue" data-resolve="${r.id}" data-status="ACCETTATA">Accetta</button><button class="btn ghost" data-resolve="${r.id}" data-status="RIFIUTATA">Rifiuta</button></div>`:''}${r.reply&&!actions?`<div class="notice">${esc(r.reply)}</div>`:''}</div>`}
function hoursView(){const data=S.schedule?.data;if(!data?.weeks?.length)return chrome(`<section class="hero"><span class="eyebrow">ORE</span><h1>Conteggio ore</h1></section><section class="card"><div class="empty">Nessun turno pubblicato.</div></section>`);return chrome(`<section class="hero"><span class="eyebrow">CONTROLLO</span><h1>Conteggio ore</h1><p>Target contrattuali e straordinari della turnazione pubblicata.</p></section>${data.weeks.map((w,i)=>`<section class="card weekhours"><div class="sectionhead"><div><span class="kicker">SETTIMANA ${i+1}</span><h2>${fmt(w.dates[0])}</h2></div></div><div class="summary peoplehours">${PEOPLE.map(n=>{const h=weekHours(w,n),t=TARGET[n]||40,e=RESP_NAMES().includes(n)?0:Math.max(0,h-t);return `<div class="stat ${e>3?'warn':''}"><small>${esc(n)}</small><b>${h}h</b><small>${RESP_NAMES().includes(n)?'forfettario':e?`+${e}h extra`:`target ${t}h`}</small></div>`}).join('')}</div></section>`).join('')}`)}
const RESP_NAMES=()=>['Umberto','Fabio','Emanuele'];
async function loadAnnouncements(){S.announcements=(await api('announcements')).announcements||[]}
function announcementsView(){return chrome(`<section class="hero"><span class="eyebrow">AVVISI</span><h1>Comunicazioni</h1><p>Informazioni importanti per il team.</p></section>${isAdmin()?`<section class="card"><span class="kicker">NUOVO</span><h2>Pubblica avviso</h2><div class="field"><textarea id="annMsg" placeholder="Scrivi un avviso…"></textarea></div><button class="btn primary" id="sendAnn">Pubblica</button></section>`:''}<section class="card spaced"><span class="kicker">ATTIVI</span><h2>Avvisi</h2><div class="list">${S.announcements.length?S.announcements.map(a=>`<div class="item"><div class="meta">${dt(a.created_at)}</div><p>${esc(a.message)}</p>${isAdmin()?`<button class="btn ghost compact" data-archive="${a.id}">Archivia</button>`:''}</div>`).join(''):'<div class="empty">Nessun avviso.</div>'}</div></section>`)}
function editModal(n,d){const w=S.draft?.weeks?.[S.week];if(!w)return;const cur=w.schedule[n][d]||'RIPOSO';document.body.insertAdjacentHTML('beforeend',`<div class="modalback" id="editBack"><div class="modal"><div class="modalhandle"></div><span class="kicker">MODIFICA TURNO</span><h3>${esc(n)} · ${esc(fmt(w.dates[d]))}</h3><div class="field"><label>Turno</label><select id="editShift">${[...new Set([cur,...QUICK])].map(s=>`<option ${s===cur?'selected':''}>${esc(s)}</option>`).join('')}</select></div><div class="toolbar"><button class="btn ghost" id="editCancel">Annulla</button><button class="btn primary" id="editSave">Salva</button></div></div></div>`);document.getElementById('editCancel').onclick=()=>document.getElementById('editBack').remove();document.getElementById('editSave').onclick=()=>{w.schedule[n][d]=document.getElementById('editShift').value;document.getElementById('editBack').remove();render()}}
async function previewRequest(id){try{const d=await api('preview_request',{method:'POST',body:{id}});showRequestPreview(d.request,d.preview)}catch(e){alert(e.message)}}
function showRequestPreview(r,p){const changes=p?.changes||[],week=p?.data?.weeks?.[p.weekIndex];document.body.insertAdjacentHTML('beforeend',`<div class="modalback" id="previewBack"><div class="modal requestmodal"><div class="modalhandle"></div><span class="kicker">VEDI TURNAZIONE</span><h3>${esc(r.employee_name)} · ${esc(r.kind)}</h3><p class="modalintro">${esc(r.request_date||'')}${r.wanted_shift?' · '+esc(r.wanted_shift):''}</p>${p?.applicable?`<div class="changes"><h4>Cambiamenti necessari</h4>${changes.map(c=>`<div class="change"><b>${esc(c.employee)}</b><span>${esc(c.date)}</span><div><del>${esc(c.from)}</del><strong>→ ${esc(c.to)}</strong></div><small>${esc(c.note||'')}</small></div>`).join('')}</div>${week?`<div class="previewtable"><h4>Settimana interessata</h4>${scheduleTable(week,PEOPLE,false)}</div>`:''}<div class="stickyactions inmodal"><button class="btn ghost" id="previewClose">Chiudi</button><button class="btn primary" id="applyRequest" data-id="${r.id}">Accetta e applica</button></div>`:`<div class="notice error">${esc(p?.reason||'Questa richiesta non è applicabile automaticamente.')}</div><div class="stickyactions inmodal"><button class="btn ghost" id="previewClose">Chiudi</button><button class="btn blue" id="acceptOnly" data-id="${r.id}">Accetta senza modifica automatica</button></div>`}</div></div>`);document.getElementById('previewClose').onclick=()=>document.getElementById('previewBack').remove();document.getElementById('applyRequest')?.addEventListener('click',()=>applyRequest(r.id));document.getElementById('acceptOnly')?.addEventListener('click',()=>{document.getElementById('previewBack').remove();resolveRequest(r.id,'ACCETTATA')})}
async function applyRequest(id){if(!confirm('Accettare la richiesta e applicare subito questi cambi alla turnazione pubblicata?'))return;try{const d=await api('apply_request',{method:'POST',body:{id}});document.getElementById('previewBack')?.remove();S.schedule=d.schedule;await loadRequests();alert('Richiesta applicata. '+(d.changes||[]).map(c=>`${c.employee}: ${c.from} → ${c.to}`).join(' · '));render()}catch(e){alert(e.message)}}
function renderLogin(){app.innerHTML=`<div class="login"><div class="loginbox"><div class="loginbrand"><img src="${LOGO}" alt="Eurospin"><span>TORRE MAURA</span></div><section class="card logincard"><span class="kicker">PORTALE TURNI</span><h1>Benvenuto</h1><p>Accedi al tuo spazio Eurospin.</p><div class="form"><div class="field"><label>Account</label><input class="biginput" id="loginUser" autocomplete="username" placeholder="Eurospin"></div><div class="field"><label>Password</label><input class="biginput" id="loginPass" type="password" inputmode="numeric" autocomplete="current-password"></div><button class="btn primary big" id="loginBtn">Accedi</button><div id="loginMsg"></div></div></section></div></div>`;document.getElementById('loginBtn').onclick=login;document.getElementById('loginPass').onkeydown=e=>{if(e.key==='Enter')login()}}
async function login(){const b=document.getElementById('loginBtn'),m=document.getElementById('loginMsg');b.disabled=true;b.textContent='Accesso…';try{const d=await api('login',{method:'POST',body:{username:document.getElementById('loginUser').value.trim(),password:document.getElementById('loginPass').value}});saveAuth(d);S.route='home';location.hash='home';await hydrate();render()}catch(e){m.innerHTML=`<div class="notice error">${esc(e.message)}</div>`}finally{b.disabled=false;b.textContent='Accedi'}}
async function hydrate(){await Promise.all([ensureSchedule(),loadRequests().catch(()=>{}),loadAnnouncements().catch(()=>{}),isAdmin()?loadAbsences().catch(()=>{}):Promise.resolve()])}
function render(){if(!S.user){renderLogin();return}let out='';if(S.route==='schedule')out=scheduleView();else if(S.route==='generate'&&isAdmin())out=generateView();else if(S.route==='requests')out=requestsView();else if(S.route==='hours'&&isAdmin())out=hoursView();else if(S.route==='announcements')out=announcementsView();else out=home();app.innerHTML=out;bindChrome();bindView()}
function bindView(){document.querySelectorAll('[data-home]').forEach(x=>x.onclick=()=>setRoute(x.dataset.home));document.querySelectorAll('[data-week]').forEach(x=>x.onclick=()=>{S.week=+x.dataset.week;S.graphDay=0;render()});document.querySelectorAll('[data-gday]').forEach(x=>x.onclick=()=>{S.graphDay=+x.dataset.gday;render()});document.querySelectorAll('[data-edit]').forEach(x=>x.onclick=()=>editModal(x.dataset.edit,+x.dataset.day));document.querySelectorAll('[data-preview]').forEach(x=>x.onclick=()=>previewRequest(+x.dataset.preview));document.getElementById('openDraft')?.addEventListener('click',()=>{S.route='schedule';S.week=0;S.graphDay=0;render()});document.getElementById('discardDraft')?.addEventListener('click',()=>{if(confirm('Eliminare la bozza?')){S.draft=null;setRoute('generate')}});document.getElementById('publishDraft')?.addEventListener('click',publishDraft);document.getElementById('addAbs')?.addEventListener('click',addAbs);document.querySelectorAll('[data-delabs]').forEach(x=>x.onclick=()=>delAbs(+x.dataset.delabs));document.getElementById('doGenerate')?.addEventListener('click',doGenerate);document.getElementById('sendReq')?.addEventListener('click',sendRequest);document.querySelectorAll('[data-resolve]').forEach(x=>x.onclick=()=>resolveRequest(+x.dataset.resolve,x.dataset.status));document.getElementById('sendAnn')?.addEventListener('click',sendAnnouncement);document.querySelectorAll('[data-archive]').forEach(x=>x.onclick=()=>archiveAnnouncement(+x.dataset.archive))}
async function addAbs(){const p=document.getElementById('absPerson').value,t=document.getElementById('absType').value,f=document.getElementById('absFrom').value,z=document.getElementById('absTo').value||f;if(!f||!z||z<f)return alert('Controlla le date');await api('add_absence',{method:'POST',body:{employeeName:p,type:t,from:f,to:z}});await loadAbsences();S.draft=null;render()}
async function delAbs(id){if(!confirm('Rimuovere questa assenza?'))return;await api('delete_absence',{method:'POST',body:{id}});await loadAbsences();S.draft=null;render()}
async function doGenerate(){if(S.busy)return;const start=document.getElementById('startDate').value;if(!start)return;S.busy=true;render();try{const d=await api('generate',{method:'POST',body:{startDate:start}});S.draft=d.schedule;S.week=0;S.graphDay=0;S.route='schedule';render()}catch(e){S.route='generate';S.busy=false;render();const m=document.getElementById('genMsg');if(m)m.innerHTML=`<div class="notice error">${esc(e.message)}</div>`;return}S.busy=false}
async function publishDraft(){if(!S.draft)return;if(!confirm('Pubblicare queste 3 settimane?'))return;await api('publish',{method:'POST',body:{schedule:S.draft}});S.draft=null;S.schedule=null;await ensureSchedule(true);alert('Turni pubblicati.');render()}
async function sendRequest(){const kind=document.getElementById('reqKind').value,date=document.getElementById('reqDate').value,end=document.getElementById('reqEnd').value||date,shift=kind==='TURNO'?document.getElementById('reqShift').value:null,msg=document.getElementById('reqMsg').value.trim();if(kind!=='ALTRO'&&!date)return alert('Seleziona il giorno');await api('create_request',{method:'POST',body:{kind,requestDate:date||null,endDate:end||null,wantedShift:shift,message:msg}});await loadRequests();render()}
async function resolveRequest(id,status){if(!confirm(status==='ACCETTATA'?'Accettare questa richiesta?':'Rifiutare questa richiesta?'))return;await api('resolve_request',{method:'POST',body:{id,status,reply:status==='ACCETTATA'?'Richiesta accettata da Eurospin.':'Richiesta rifiutata da Eurospin.'}});await Promise.all([loadRequests(),isAdmin()?loadAbsences():Promise.resolve()]);render()}
async function sendAnnouncement(){const m=document.getElementById('annMsg').value.trim();if(!m)return;await api('create_announcement',{method:'POST',body:{message:m}});await loadAnnouncements();render()}
async function archiveAnnouncement(id){await api('archive_announcement',{method:'POST',body:{id}});await loadAnnouncements();render()}
async function boot(){applyMode();S.route=(location.hash||'#home').slice(1);if(S.token){try{const d=await api('me');S.user=d.user;await hydrate();render();return}catch{}}renderLogin()}
window.addEventListener('hashchange',()=>{if(!S.user)return;S.route=(location.hash||'#home').slice(1);render()});boot();
})();