(()=>{
'use strict';
const API='https://dlqrhteqodkdkvmrwktu.supabase.co/functions/v1/turni-clean-api';
const DEL='https://dlqrhteqodkdkvmrwktu.supabase.co/functions/v1/turni-delete-weeks-v1';
const token=()=>localStorage.getItem('tm2_token')||'';
const user=()=>{try{return JSON.parse(localStorage.getItem('tm2_user')||'{}')}catch{return{}}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=d=>new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(d+'T12:00:00'));
async function getSchedule(){const r=await fetch(`${API}?action=get_schedule`,{headers:{Authorization:`Bearer ${token()}`}});const d=await r.json().catch(()=>({error:'Risposta non valida'}));if(!r.ok)throw new Error(d.error||'Errore');return d.schedule}
async function del(body){const r=await fetch(DEL,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`},body:JSON.stringify(body)});const d=await r.json().catch(()=>({error:'Risposta non valida'}));if(!r.ok)throw new Error(d.error||'Errore');return d}
async function openManager(){document.getElementById('deleteWeeksBack')?.remove();let row;try{row=await getSchedule()}catch(e){alert(e.message);return}const weeks=row?.data?.weeks||[];if(!weeks.length){alert('Non ci sono settimane pubblicate.');return}const back=document.createElement('div');back.id='deleteWeeksBack';back.className='modalback';back.style.zIndex='12500';back.innerHTML=`<div class="modal" style="max-width:560px;width:min(94vw,560px)"><h2 style="margin-top:0">🗑️ Gestisci settimane pubblicate</h2><div class="notice" style="margin-bottom:12px">Puoi cancellare una singola settimana oppure tutte. <b>FERIE, richieste e dipendenti non vengono toccati.</b></div><div style="display:grid;gap:8px">${weeks.map((w,i)=>`<div class="item" style="display:flex;align-items:center;gap:10px;justify-content:space-between"><div><b>Settimana ${i+1}</b><br><small>${esc(fmt(w.dates[0]))} – ${esc(fmt(w.dates[6]))}</small></div><button class="btn danger" data-del-week="${i}" type="button">Cancella</button></div>`).join('')}</div><div style="border-top:1px solid rgba(0,0,0,.12);margin-top:14px;padding-top:14px"><button class="btn danger" id="deleteAllWeeks" type="button" style="width:100%;font-weight:900">CANCELLA TUTTE LE SETTIMANE PUBBLICATE</button></div><div class="toolbar" style="margin-top:12px"><button class="btn ghost" id="deleteWeeksClose" type="button">Chiudi</button></div></div>`;document.body.appendChild(back);back.querySelector('#deleteWeeksClose').onclick=()=>back.remove();back.querySelectorAll('[data-del-week]').forEach(b=>b.onclick=async()=>{const i=+b.dataset.delWeek,w=weeks[i];if(!confirm(`Cancellare la Settimana ${i+1} (${fmt(w.dates[0])} – ${fmt(w.dates[6])})?`))return;b.disabled=true;try{await del({mode:'one',weekIndex:i});back.remove();location.reload()}catch(e){alert(e.message);b.disabled=false}});back.querySelector('#deleteAllWeeks').onclick=async()=>{if(!confirm('Cancellare TUTTE le settimane pubblicate? Questa operazione rimuove solo i turni pubblicati.'))return;const b=back.querySelector('#deleteAllWeeks');b.disabled=true;b.textContent='Cancellazione…';try{await del({mode:'all'});back.remove();location.reload()}catch(e){alert(e.message);b.disabled=false;b.textContent='CANCELLA TUTTE LE SETTIMANE PUBBLICATE'}};back.onclick=e=>{if(e.target===back)back.remove()}}
function mount(){if(user().role!=='admin'||location.hash!=='#schedule'||document.getElementById('deleteWeeksBtn'))return;const hero=[...document.querySelectorAll('.hero')].find(x=>/Turni pubblicati/i.test(x.textContent||''));if(!hero)return;const b=document.createElement('button');b.id='deleteWeeksBtn';b.className='btn danger';b.type='button';b.style.marginTop='10px';b.style.marginLeft='8px';b.textContent='🗑️ Gestisci settimane';b.onclick=openManager;hero.appendChild(b)}
new MutationObserver(mount).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('hashchange',()=>setTimeout(mount,0));setTimeout(mount,250);
})();
