(()=>{
'use strict';
const API='https://dlqrhteqodkdkvmrwktu.supabase.co/functions/v1/turni-clean-api';
const PEOPLE=['Umberto','Fabio','Emanuele','Stefania B','Stefania F','Romina','Giada','Giuliano','Manuel','Daniele','Paolo','Marco'];
const token=()=>localStorage.getItem('tm2_token')||'';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function call(action,body){const r=await fetch(`${API}?action=${encodeURIComponent(action)}`,{method:'POST',headers:{'Content-Type':'application/json',...(token()?{Authorization:`Bearer ${token()}`}:{})},body:JSON.stringify(body)});const d=await r.json().catch(()=>({error:'Risposta non valida'}));if(!r.ok)throw new Error(d.error||'Errore');return d}
function mount(){if(location.hash!=='#generate'||document.getElementById('qrFerieBox'))return;const grid=document.querySelector('#quickRequestsPanel .qr-add-grid');if(!grid)return;const options=PEOPLE.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('');const start=document.getElementById('startDate')?.value||'';const box=document.createElement('div');box.className='item qr-box';box.id='qrFerieBox';box.innerHTML=`<h3>🏖️ FERIE</h3><div class="field"><label>Dipendente</label><select id="qrFeriePerson">${options}</select></div><div class="formrow"><div class="field"><label>Dal</label><input id="qrFerieFrom" type="date" value="${esc(start)}"></div><div class="field"><label>Al</label><input id="qrFerieTo" type="date" value="${esc(start)}"></div></div><button class="btn blue" id="qrAddFerie" type="button">Aggiungi FERIE</button><div id="qrFerieMsg"></div>`;grid.appendChild(box);const summary=document.querySelector('#qrQuickAdd summary');if(summary)summary.textContent='＋ Aggiungi FERIE / RIPOSO / TURNO';document.getElementById('qrAddFerie')?.addEventListener('click',async()=>{const b=document.getElementById('qrAddFerie'),employeeName=document.getElementById('qrFeriePerson')?.value,from=document.getElementById('qrFerieFrom')?.value,to=document.getElementById('qrFerieTo')?.value||from,msg=document.getElementById('qrFerieMsg');if(!from){if(msg)msg.innerHTML='<div class="notice error" style="margin-top:5px;padding:5px 7px">Seleziona la data iniziale.</div>';return}if(to<from){if(msg)msg.innerHTML='<div class="notice error" style="margin-top:5px;padding:5px 7px">La data finale non può precedere quella iniziale.</div>';return}b.disabled=true;try{await call('add_absence',{employeeName,type:'FERIE',from,to});if(msg)msg.innerHTML='<div class="notice" style="margin-top:5px;padding:5px 7px">Ferie salvate.</div>';setTimeout(()=>location.reload(),350)}catch(e){if(msg)msg.innerHTML=`<div class="notice error" style="margin-top:5px;padding:5px 7px">${esc(e.message)}</div>`;b.disabled=false}})}
const obs=new MutationObserver(()=>setTimeout(mount,30));obs.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('hashchange',()=>setTimeout(mount,60));setTimeout(mount,350);
})();
