(()=>{
'use strict';
const API='https://dlqrhteqodkdkvmrwktu.supabase.co/functions/v1/turni-clean-api';
const PEOPLE=['Umberto','Fabio','Emanuele','Stefania B','Stefania F','Romina','Giada','Giuliano','Manuel','Daniele','Paolo','Marco'];
const token=()=>localStorage.getItem('tm2_token')||'';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function call(action,body){const r=await fetch(`${API}?action=${encodeURIComponent(action)}`,{method:'POST',headers:{'Content-Type':'application/json',...(token()?{Authorization:`Bearer ${token()}`}:{})},body:JSON.stringify(body)});const d=await r.json().catch(()=>({error:'Risposta non valida'}));if(!r.ok)throw new Error(d.error||'Errore');return d}
function ensureStyle(){if(document.getElementById('ferieButtonStyle'))return;const s=document.createElement('style');s.id='ferieButtonStyle';s.textContent=`#qrFerieTopBtn{font-weight:800!important;white-space:nowrap}#qrFerieTopBox{margin-top:8px;padding:9px;border:1px solid rgba(120,120,120,.18);border-radius:9px}#qrFerieTopBox[hidden]{display:none!important}#qrFerieTopBox .formrow{display:flex;gap:7px;flex-wrap:wrap}#qrFerieTopBox .field{flex:1;min-width:120px}@media(max-width:700px){#qrFerieTopBtn{font-size:12px!important;padding:6px 8px!important}}`;document.head.appendChild(s)}
function mount(){if(location.hash!=='#generate'||document.getElementById('qrFerieTopBtn'))return;const panel=document.getElementById('quickRequestsPanel');if(!panel)return;ensureStyle();const title=panel.querySelector('.qr-title');if(!title)return;const btn=document.createElement('button');btn.id='qrFerieTopBtn';btn.type='button';btn.className='btn blue';btn.textContent='🏖️ FERIE';title.appendChild(btn);const options=PEOPLE.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('');const start=document.getElementById('startDate')?.value||'';const box=document.createElement('div');box.id='qrFerieTopBox';box.hidden=true;box.innerHTML=`<h3 style="margin:0 0 7px">🏖️ Inserisci FERIE</h3><div class="field"><label>Dipendente</label><select id="qrFeriePerson">${options}</select></div><div class="formrow"><div class="field"><label>Dal</label><input id="qrFerieFrom" type="date" value="${esc(start)}"></div><div class="field"><label>Al</label><input id="qrFerieTo" type="date" value="${esc(start)}"></div></div><button class="btn blue" id="qrAddFerie" type="button">Aggiungi FERIE</button><div id="qrFerieMsg"></div>`;title.insertAdjacentElement('afterend',box);btn.addEventListener('click',()=>{box.hidden=!box.hidden});document.getElementById('qrAddFerie')?.addEventListener('click',async()=>{const b=document.getElementById('qrAddFerie'),employeeName=document.getElementById('qrFeriePerson')?.value,from=document.getElementById('qrFerieFrom')?.value,to=document.getElementById('qrFerieTo')?.value||from,msg=document.getElementById('qrFerieMsg');if(!from){if(msg)msg.innerHTML='<div class="notice error" style="margin-top:5px;padding:5px 7px">Seleziona la data iniziale.</div>';return}if(to<from){if(msg)msg.innerHTML='<div class="notice error" style="margin-top:5px;padding:5px 7px">La data finale non può precedere quella iniziale.</div>';return}b.disabled=true;try{await call('add_absence',{employeeName,type:'FERIE',from,to});if(msg)msg.innerHTML='<div class="notice" style="margin-top:5px;padding:5px 7px">Ferie salvate.</div>';setTimeout(()=>location.reload(),350)}catch(e){if(msg)msg.innerHTML=`<div class="notice error" style="margin-top:5px;padding:5px 7px">${esc(e.message)}</div>`;b.disabled=false}})}
const obs=new MutationObserver(()=>{if(location.hash==='#generate')setTimeout(mount,30)});obs.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('hashchange',()=>setTimeout(mount,60));setTimeout(mount,300);
})();
