(()=>{
'use strict';
const TOOLS='https://dlqrhteqodkdkvmrwktu.supabase.co/functions/v1/turni-admin-tools-api';
const token=()=>localStorage.getItem('tm2_token')||'';
const user=()=>{try{return JSON.parse(localStorage.getItem('tm2_user')||'{}')}catch{return{}}};
const b64=s=>{const p='='.repeat((4-s.length%4)%4),x=(s+p).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(x),a=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)a[i]=raw.charCodeAt(i);return a};
async function call(action,method='GET',body){const r=await fetch(`${TOOLS}?action=${encodeURIComponent(action)}`,{method,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({error:'Risposta non valida'}));if(!r.ok)throw new Error(d.error||'Errore');return d}
async function ensurePush(ask=false){if(user().role!=='employee'||!token())return false;if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window))throw new Error('Le notifiche push non sono supportate su questo dispositivo.');if(ask&&Notification.permission==='default'){const p=await Notification.requestPermission();if(p!=='granted')throw new Error('Permesso notifiche non concesso.')}if(Notification.permission!=='granted')return false;const reg=await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub){const k=await call('vapid_public');sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(k.publicKey)})}await call('register_push','POST',{subscription:sub.toJSON(),userAgent:navigator.userAgent});localStorage.setItem('tm2_push_enabled','1');return true}
function mount(){if(user().role!=='employee'||location.hash!=='#announcements')return;if(document.getElementById('enablePushBtn'))return;const hero=[...document.querySelectorAll('.hero')].find(x=>/^Avvisi/i.test((x.querySelector('h1')?.textContent||'')));if(!hero)return;const b=document.createElement('button');b.id='enablePushBtn';b.type='button';b.className='btn primary';b.style.marginTop='10px';b.textContent=Notification.permission==='granted'?'🔔 Notifiche attive':'🔔 Attiva notifiche';b.onclick=async()=>{b.disabled=true;try{await ensurePush(true);b.textContent='🔔 Notifiche attive';alert('Notifiche attivate su questo dispositivo.')}catch(e){alert(e.message)}finally{b.disabled=false}};hero.appendChild(b)}
new MutationObserver(mount).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('hashchange',()=>setTimeout(mount,0));setTimeout(()=>{mount();if(Notification.permission==='granted'&&user().role==='employee')ensurePush(false).catch(()=>{})},700);
})();
